var qbGeneral = [

{ "question": "Eldest son of Dhirtarashtra","type": "single","options" : {"A": "Dhusaasana","B": "Yudhisthira","C": "Krishna","D": "Duryodana"},"answer": "D"},
{ "question": "Paandu had ___ sons","type": "single","options" : {"A": "4","B": "3","C": "6","D": "5"},"answer": "D"},
{ "question": "How many sisters Duryodhana had?","type": "single","options" : {"A": "2","B": "3","C": "0","D": "1"},"answer": "D"},
{ "question": "Who is elder? Yudhisthira or Duryodhana?","type": "single","options" : {"A": "Duryodhana","B": "Both are same age","C": "One is sister","D": "Yudhisthira"},"answer": "D"},
{ "question": "Whose father was blind? Pandavas or Kauravas?","type": "single","options" : {"A": "Pandavas","B": "No father was blind","C": "Both were blind","D": "Kauravas"},"answer": "D"},
{ "question": "Mother of all Pandavas?","type": "single","options" : {"A": "Kunti","B": "Draupadi","C": "Gandhari","D": "2 mothers"},"answer": "D"},
{ "question": "Who were in forest for longer times","type": "single","options" : {"A": "Kauravas","B": "Saguni","C": "Kings","D": "Pandavas"},"answer": "D"},
{ "question": "Tell the right order of Pandavas:","type": "single","options" : {"A": "Nakul, Sahadev, Bheema, Arjun","B": "Arjun Bheema, Nakul Sahadev","C": "Bheema Duryodhan Arjun Sahadv","D": "Bheema Arjun Nakul Sahadev"},"answer": "D"},
{ "question": "Pick the odd one out:","type": "single","options" : {"A": "Duryodhan","B": "Dhosaasan","C": "Yuyutsu","D": "Arjun"},"answer": "D"},
{ "question": "Sister of Duryodhan ___","type": "single","options" : {"A": "No sister","B": "Dushasana","C": "Paanjaali","D": "Dushala"},"answer": "D"},
{ "question": "How many Sisters for Duryodhan?","type": "single","options" : {"A": "0","B": "99","C": "100","D": "1"},"answer": "D"},
{ "question": "Who was more stronger?","type": "single","options" : {"A": "Duryodhan","B": "Arjun","C": "Yudhisthira","D": "Bheema"},"answer": "D"},
{ "question": "Other than 5 pandavas, there is another brother for them. He is","type": "single","options" : {"A": "Kannan","B": "Krishna","C": "Kubera","D": "Karna"},"answer": "D"},
{ "question": "Karna is born to ___","type": "single","options" : {"A": "Gandhari","B": "Draupadi","C": "Dhusaasala","D": "Kunti"},"answer": "D"},
{ "question": "Dushala mother is ___","type": "single","options" : {"A": "Kunti","B": "Draupadi","C": "Dhusaasala","D": "Gandhari"},"answer": "D"},
{ "question": "Who is bad?","type": "single","options" : {"A": "Gandhari","B": "Bheema","C": "Nakul","D": "Duryodhana"},"answer": "D"},
{ "question": "Mother of Nakula and Arjuna","type": "single","options" : {"A": "Kunti & Madri","B": "Gandhari & Kunti","C": "Kunti","D": "Madri & Kunti"},"answer": "D"},
{ "question": "Who is the wife of Dhritarashtra?","type": "single","options" : {"A": "Kunti","B": "Madri","C": "Dhusala","D": "Gandhari"},"answer": "D"},
{ "question": "Who is the mother of Duryodhana?","type": "single","options" : {"A": "Kunti","B": "Madri","C": "Dhusala","D": "Gandhari"},"answer": "D"},
{ "question": "Lord Krishna's brother is ___","type": "single","options" : {"A": "Rama","B": "Arjun","C": "Bheema","D": "Balarama"},"answer": "D"},
{ "question": "Lord Krishna and Balarama's father is ____","type": "single","options" : {"A": "Paandu","B": "Dhritarashtra","C": "Saguni","D": "Vasudeva"},"answer": "D"},
{ "question": "Duryodhana's mother's brother is ___","type": "single","options" : {"A": "Paandu","B": "Arjun","C": "Kunti","D": "Saguni"},"answer": "D"},
{ "question": "Lord Krishna's father's sister is ___","type": "single","options" : {"A": "Madri","B": "Dhusala","C": "Gandhari","D": "Kunti"},"answer": "D"},
{ "question": "Lord Krishna's sister's name is ___","type": "single","options" : {"A": "Kunti","B": "Draupadi","C": "Vasudeva","D": "Subhadra"},"answer": "D"},
{ "question": "Who married Lord Krishna's sister?","type": "single","options" : {"A": "Bheema","B": "Dharma","C": "Duryodhana","D": "Arjun"},"answer": "D"},
{ "question": "Wife's name of all Pandavas is ___","type": "single","options" : {"A": "Subhadra","B": "Dushasala","C": "Gandeeva","D": "Draupadi"},"answer": "D"},
{ "question": "Where was the big palace of Pandavas and Kauravas was?","type": "single","options" : {"A": "Ayodhya","B": "Bengaluru","C": "Chennai","D": "Hastinapura"},"answer": "D"},
{ "question": "Son of Arjun and Subhadra is ____","type": "single","options" : {"A": "Arjunaa","B": "Bheema","C": "Sahadev","D": "Abhimanyu"},"answer": "D"},
{ "question": "Which is the right combination?","type": "single","options" : {"A": "Bheema - Food","B": "Nakula - Jumping","C": "Sahadev - Shooting","D": "Arjun - Bow/Arrow"},"answer": "D"},
{ "question": "Which is not the right combination?","type": "single","options" : {"A": "Arjun - Bow/Arrow","B": "Nakula - Reading stars","C": "Sahadev - Swords","D": "Bheema - Food"},"answer": "D"},
{ "question": "Capital of India","type": "single","options" : {"A": "Chennai","B": "Bangalore","C": "Kolkata","D": "New Delhi"},"answer": "D"},
{ "question": "Where is this city? (pick more correct one). Bangalore","type": "single","options" : {"A": "India","B": "Tamilnadu","C": "Japan","D": "Karnataka"},"answer": "D"},
{ "question": "Where is this city? (pick more correct one). Chennai","type": "single","options" : {"A": "India","B": "Karnataka","C": "Japan","D": "Tamilnadu"},"answer": "D"},
{ "question": "Capital of Japan","type": "single","options" : {"A": "Osaka","B": "Mukaasa","C": "Cairo","D": "Tokyo"},"answer": "D"},
{ "question": "Capital of America (United States)","type": "single","options" : {"A": "New York","B": "California","C": "Las vegas","D": "Washington DC "},"answer": "D"},
{ "question": "Capital of United Kingdom (UK)","type": "single","options" : {"A": "England","B": "Scotland","C": "Worthing","D": "London"},"answer": "D"},
{ "question": "Capital of Australia","type": "single","options" : {"A": "London","B": "Bangalore","C": "Sydney","D": "Canberra"},"answer": "D"},
{ "question": "Capital of China","type": "single","options" : {"A": "Washington DC","B": "Canberra","C": "Sydney","D": "Beijing"},"answer": "D"},
{ "question": "Capital of South Korea","type": "single","options" : {"A": "Beijing","B": "Canberra","C": "Washington DC","D": "Seoul"},"answer": "D"},
{ "question": "Capital of Bangladesh","type": "single","options" : {"A": "Delhi","B": "Bombay","C": "Bengal","D": "Dhaka"},"answer": "D"},
{ "question": "Capital of Karnataka","type": "single","options" : {"A": "Chennai","B": "Hyderabad","C": "Delhi","D": "Bangalore"},"answer": "D"},
{ "question": "Capital of Tamilnadu","type": "single","options" : {"A": "Bangalore","B": "Hyderabad","C": "Delhi","D": "Chennai"},"answer": "D"},
{ "question": "Capital of Andhra Pradesh","type": "single","options" : {"A": "Hyderabad","B": "Bangalore","C": "Chennai","D": "Amaravati"},"answer": "D"},
{ "question": "Capital of Telangana","type": "single","options" : {"A": "Amaravati","B": "Bangalore","C": "Chennai","D": "Hyderabad"},"answer": "D"},
{ "question": "Capital of Kerala","type": "single","options" : {"A": "Kochi","B": "Kozhikode","C": "Chennai","D": "Tiruvanandapuram"},"answer": "D"},
{ "question": "Capital of Maharashtra","type": "single","options" : {"A": "Kolkata","B": "Bangalore","C": "Chennai","D": "Mumbai"},"answer": "D"},
{ "question": "Mumbai is capital of ___","type": "single","options" : {"A": "Tamil nadu","B": "Kerala","C": "Karnataka","D": "Maharashtra"},"answer": "D"},
{ "question": "Bangalore is capital of ___","type": "single","options" : {"A": "Tamil nadu","B": "Kerala","C": "Maharashtra","D": "Karnataka"},"answer": "D"},
{ "question": "Delhi is capital of ___","type": "single","options" : {"A": "Delhi","B": "America","C": "China","D": "India"},"answer": "D"},
{ "question": "Which country &gt;&gt;&gt;gen_ind","type": "single","options" : {"A": "United States","B": "United Kingdom","C": "China","D": "India"},"answer": "D"},
{ "question": "Which country &gt;&gt;&gt;gen_us","type": "single","options" : {"A": "India","B": "United Kingdom","C": "China","D": "United States"},"answer": "D"},
{ "question": "Which country &gt;&gt;&gt;gen_uk","type": "single","options" : {"A": "India","B": "United States","C": "China","D": "United Kingdom"},"answer": "D"},
{ "question": "Which country &gt;&gt;&gt;gen_aus","type": "single","options" : {"A": "Australia","B": "United States","C": "China","D": "Australia"},"answer": "D"},
{ "question": "Which country &gt;&gt;&gt;gen_china","type": "single","options" : {"A": "Australia","B": "United States","C": "United Kingdom","D": "China"},"answer": "D"},
{ "question": "Which country &gt;&gt;&gt;gen_japan","type": "single","options" : {"A": "United States","B": "Nepal","C": "China","D": "Japan"},"answer": "D"},
{ "question": "Which country &gt;&gt;&gt;gen_nepal","type": "single","options" : {"A": "US","B": "UK","C": "China","D": "Nepal"},"answer": "D"},
{ "question": "Identify place 1 /n&gt;&gt;&gt;gen_indiamap","type": "single","options" : {"A": "India","B": "Bangalore","C": "Chennai","D": "Mumbai"},"answer": "D"},
{ "question": "Identify place 2 /n&gt;&gt;&gt;gen_indiamap","type": "single","options" : {"A": "India","B": "Mumbai","C": "Chennai","D": "Bangalore"},"answer": "D"},
{ "question": "Identify place 3 /n&gt;&gt;&gt;gen_indiamap","type": "single","options" : {"A": "India","B": "Mumbai","C": "Chennai","D": "Delhi"},"answer": "D"},
{ "question": "Identify place 4 /n&gt;&gt;&gt;gen_indiamap","type": "single","options" : {"A": "India","B": "Mumbai","C": "Delhi","D": "Chennai"},"answer": "D"},
{ "question": "Identify place 5 /n&gt;&gt;&gt;gen_indiamap","type": "single","options" : {"A": "Water","B": "Mumbai","C": "Sea","D": "Bay of Bengal Sea"},"answer": "D"},
{ "question": "Identify place 6 /n&gt;&gt;&gt;gen_indiamap","type": "single","options" : {"A": "Water","B": "Mumbai","C": "Sea","D": "Arabian Sea"},"answer": "D"},
{ "question": "Identify place 7 /n&gt;&gt;&gt;gen_indiamap","type": "single","options" : {"A": "Bangalore","B": "Mumbai","C": "Chennai","D": "Kolkata"},"answer": "D"},
{ "question": "5 years once, what do we do to select our leader","type": "single","options" : {"A": "Prayer","B": "Fights","C": "Arguments","D": "Voting"},"answer": "D"},
{ "question": "For voting, what is the age?","type": "single","options" : {"A": "5","B": "3","C": "24","D": "18"},"answer": "D"},
{ "question": "Why are we voting?","type": "single","options" : {"A": "To show we are there","B": "To get food","C": "To get water","D": "To select MLAs"},"answer": "D"},
{ "question": "I earn 100 rupees, I give 30 rs.  My friend earns 50 rs, he gives 15 rupees.  This giving rupees is called as ___","type": "single","options" : {"A": "Money","B": "Donation","C": "Contribution","D": "Tax"},"answer": "D"},
{ "question": "All Tax amount is used for what?","type": "single","options" : {"A": "Tax amount - MLA will eat food","B": "Tax - donate to poor ppl","C": "Tax - put in bank","D": "Tax amount -MLA will put roads"},"answer": "D"},
{ "question": "Full name of him &gt;&gt;&gt;gen_modi","type": "single","options" : {"A": "Narasimha Modi","B": "Damordas Modi","C": "Nirav Modi","D": "Narendra Modi"},"answer": "D"},
{ "question": "He built Indian National Army to fight with British. Who?","type": "single","options" : {"A": "Modi","B": "Gandhi","C": "Nehru","D": "Subhash chandra Bose"},"answer": "D"},
{ "question": "He is not a freedom fighter. Who?","type": "single","options" : {"A": "Gandhi","B": "Nehru","C": "Ambedkar","D": "Kohli"},"answer": "D"},
{ "question": "He wrote the rule book (Constitution). Who is he?  &gt;&gt;&gt;gen_ambedkar","type": "single","options" : {"A": "Narendra Modi","B": "Nehru","C": "Gandhi","D": "Ambedkar"},"answer": "D"},
{ "question": "Identify him &gt;&gt;&gt;gen_arnab","type": "single","options" : {"A": "Virat Kohli","B": "Tendulkar","C": "Santosh","D": "Arnab Goswami"},"answer": "D"},
{ "question": "Identify him &gt;&gt;&gt;gen_azad","type": "single","options" : {"A": "Gandhi","B": "Subhash Chandra Bose","C": "Bhagat singh","D": "Chandra shekar Azad"},"answer": "D"},
{ "question": "Identify him &gt;&gt;&gt;gen_lal","type": "single","options" : {"A": "Nehru","B": "Gandhi","C": "Indira Gandhi","D": "Lal Bahadur Shastri"},"answer": "D"},
{ "question": "Identify him &gt;&gt;&gt;gen_saroj","type": "single","options" : {"A": "Indira Gandhi","B": "Jayalalitha","C": "Old lady","D": "Sarojini Naidu"},"answer": "D"},
{ "question": "Identify him/her &gt;&gt;&gt;gen_bhagat","type": "single","options" : {"A": "Rabindranath Tagore","B": "Subhash Chandra Bose","C": "Army Man","D": "Bhagat Singh"},"answer": "D"},
{ "question": "Identify him/her &gt;&gt;&gt;gen_gandhi","type": "single","options" : {"A": "Old man","B": "Grandpa","C": "Father","D": "Gandhi"},"answer": "D"},
{ "question": "Identify him/her &gt;&gt;&gt;gen_gandhi","type": "single","options" : {"A": "Man of the match","B": "Great Grandfather","C": "Nehru","D": "Father of Nation"},"answer": "D"},
{ "question": "Identify him/her &gt;&gt;&gt;gen_indira","type": "single","options" : {"A": "Sarojini","B": "Laxmibai","C": "Lata","D": "Indira"},"answer": "D"},
{ "question": "Identify him/her &gt;&gt;&gt;gen_indira","type": "single","options" : {"A": "Son of Nehru","B": "Gandhi's daughter","C": "First prime minister","D": "First woman prime minister"},"answer": "D"},
{ "question": "Identify him/her &gt;&gt;&gt;gen_kohli","type": "single","options" : {"A": "Sachin","B": "Bumrah","C": "Rohit","D": "Kohli"},"answer": "D"},
{ "question": "Identify him/her &gt;&gt;&gt;gen_modi","type": "single","options" : {"A": "Shah","B": "Tendulkar","C": "Gandhi","D": "Modi"},"answer": "D"},
{ "question": "Identify him/her &gt;&gt;&gt;gen_nehru","type": "single","options" : {"A": "Gandhi","B": "Indira","C": "Rajiv","D": "Nehru"},"answer": "D"},
{ "question": "Identify him/her &gt;&gt;&gt;gen_nehru","type": "single","options" : {"A": "Gandhi","B": "Lala Lajpat","C": "Indian","D": "First Prime Minister of India"},"answer": "D"},
{ "question": "Identify him/her &gt;&gt;&gt;gen_radhakrish","type": "single","options" : {"A": "Gandhi","B": "Sardar Vallabhai Patel","C": "Nehru","D": "Radhakrishnan"},"answer": "D"},
{ "question": "Identify him/her &gt;&gt;&gt;gen_subhash","type": "single","options" : {"A": "Chandra","B": "Policeman","C": "Bhagat singh","D": "Subhash chandra Bose"},"answer": "D"},
{ "question": "Identify him/her &gt;&gt;&gt;gen_subhash","type": "single","options" : {"A": "Bhagat Singh","B": "Rabindranath Tagore","C": "Army Man","D": "Subhash Chandra Bose"},"answer": "D"},
{ "question": "Identify him/her &gt;&gt;&gt;gen_tagore","type": "single","options" : {"A": "Rabindra Singh","B": "Subhash Chandra Bose","C": "Bhagat Singh","D": "Rabindranath Tagore"},"answer": "D"},
{ "question": "Identify Person 1 &gt;&gt;&gt;gen_akbar","type": "single","options" : {"A": "Humayun","B": "Raja","C": "Kings","D": "Akbar"},"answer": "D"},
{ "question": "Identify Person 2 &gt;&gt;&gt;gen_akbar","type": "single","options" : {"A": "Humayun","B": "Aurangazeb","C": "Akbar","D": "Birbal"},"answer": "D"},
{ "question": "Pick right answer: &gt;&gt;&gt;gen_bhagat","type": "single","options" : {"A": "Died after 99 yrs","B": "Army man","C": "Police","D": "Took the gun and shoot"},"answer": "D"},
{ "question": "Pick right answer: &gt;&gt;&gt;gen_tagore","type": "single","options" : {"A": "Saare Jahaan se","B": "Army","C": "Police","D": "Jana Gana Mana"},"answer": "D"},
{ "question": "Select right phrase for him &gt;&gt;&gt;gen_nehru","type": "single","options" : {"A": "Jai Jawan Jai Kissan","B": "Gandhi","C": "Hey Ram","D": "Children's day"},"answer": "D"},
{ "question": "Select right sentence for him &gt;&gt;&gt;gen_lal","type": "single","options" : {"A": "Father of nation","B": "Children's day","C": "United India from 500 pieces","D": "Jai Jawan Jai Kissan"},"answer": "D"},
{ "question": "Which is right sentence representing him &gt;&gt;&gt;gen_patel","type": "single","options" : {"A": "Father of nation","B": "Children's day","C": "Jai Jawan Jai Kissan","D": "India in 500 pieces - he united"},"answer": "D"},
{ "question": "How old is Masha?","type": "single","options" : {"A": "4","B": "5","C": "6","D": "3"},"answer": "D"},
{ "question": "Where is Masha's house situated? Near?","type": "single","options" : {"A": "Police station","B": "School","C": "Bus station","D": "Railway station"},"answer": "D"},
{ "question": "Who creates problem to whom? Masha or Bear","type": "single","options" : {"A": "Bear creates problems","B": "Parents create","C": "Fox creates","D": "Masha creates problem"},"answer": "D"},
{ "question": "Does Masha have friends?","type": "single","options" : {"A": "No","B": "Only animal friends","C": "","D": "Yes"},"answer": "D"},
{ "question": "Does Masha parents know her naughtiness","type": "single","options" : {"A": "Yes","B": "They encourage","C": "They also play","D": "Parents are not shown"},"answer": "D"},
{ "question": "What is the color of bear?","type": "single","options" : {"A": "Black","B": "Pink","C": "Orange","D": "Brown"},"answer": "D"},
{ "question": "Where does the bear live?","type": "single","options" : {"A": "In Bommanahalli","B": "Inside Nest","C": "Above the hill","D": "House out of a tree"},"answer": "D"},
{ "question": "Can bear do the magic?","type": "single","options" : {"A": "No","B": "Only playing","C": "Only Chess","D": "Yes"},"answer": "D"},
{ "question": "Which is not Masha pet?","type": "single","options" : {"A": "goat","B": "pig","C": "chickens","D": "deer"},"answer": "D"},
{ "question": "Which is Masha's pet?","type": "single","options" : {"A": "cat","B": "dog","C": "deer","D": "pig"},"answer": "D"},
{ "question": "Do Masha's pets like her?","type": "single","options" : {"A": "very much","B": "they jump","C": "they run on her","D": "No, they hide"},"answer": "D"},
{ "question": "Who is the villain in Masha and Bear?","type": "single","options" : {"A": "Tiger","B": "Lion","C": "Rabbit","D": "Hare"},"answer": "D"},
{ "question": "What does the villain in Masha and Bear steal?","type": "single","options" : {"A": "Turnip","B": "Goose","C": "Cider","D": "Carrot"},"answer": "D"},
{ "question": "How many wolves are present?","type": "single","options" : {"A": "One","B": "Three","C": "Four","D": "Two"},"answer": "D"},
{ "question": "Where are the wolves living in?","type": "single","options" : {"A": "Hill","B": "Nest","C": "Tree","D": "Ambulance"},"answer": "D"},
{ "question": "Which are the wild animals in this?","type": "single","options" : {"A": "Hare, Lions","B": "Lions, Tigers, Wolves","C": "Lions, Foxes, Wolves","D": "Hare, Wolves, Squirrels"},"answer": "D"},
{ "question": "What is the name of Masha cousin?","type": "single","options" : {"A": "Rashi","B": "Kashi","C": "Boshi","D": "Dasha"},"answer": "D"},
{ "question": "Who is the Bear's young cousin from China?","type": "single","options" : {"A": "Deer","B": "Wolf","C": "Masha","D": "Panda"},"answer": "D"},
{ "question": "Bear liked She-Bear.  But She-Bear liked in favor of ___.","type": "single","options" : {"A": "Fox","B": "Wolf","C": "China","D": "Black Bear"},"answer": "D"},
{ "question": "Something hatched out of Egg and quickly assumes Bear a parental-figure. What is that something?","type": "single","options" : {"A": "Hen","B": "Cat","C": "Wolf","D": "Penguin"},"answer": "D"},
{ "question": "Someone like Santa-claus who does magical version? Who?","type": "single","options" : {"A": "Bean","B": "Father Don","C": "Father Finch","D": "Father Frost"},"answer": "D"},
{ "question": "Aliens came and crashed on earth. How many eyes they had?","type": "single","options" : {"A": "Three","B": "Two","C": "One","D": "Four"},"answer": "D"},
{ "question": "How many runs when ball goes in the sky and crosses rope","type": "single","options" : {"A": "Four","B": "Two","C": "One","D": "Six"},"answer": "D"},
{ "question": "How many fielders are present in a match","type": "single","options" : {"A": "2","B": "9","C": "3","D": "11"},"answer": "D"},
{ "question": "One who stands behind the stumps is ___","type": "single","options" : {"A": "Bowler","B": "Umpire","C": "Batter","D": "Wicket keeper"},"answer": "D"},
{ "question": "How many runs when ball rolls on the ground and crosses rope","type": "single","options" : {"A": "2","B": "6","C": "1","D": "4"},"answer": "D"},
{ "question": "How many batsmen usually will be on ground?","type": "single","options" : {"A": "10","B": "11","C": "1","D": "2"},"answer": "D"},
{ "question": "How many wickets I should take so that a team gets ALL OUT","type": "single","options" : {"A": "3","B": "11","C": "9","D": "10"},"answer": "D"},
{ "question": "How many runs one should take - we call it Century","type": "single","options" : {"A": "10","B": "50","C": "30","D": "100"},"answer": "D"},
{ "question": "This cricket match is played for 5 days - it is called as ___","type": "single","options" : {"A": "T20","B": "5 days","C": "1 day match","D": "Test Match"},"answer": "D"},
{ "question": "In this match, everyone puts white color shirt","type": "single","options" : {"A": "T20","B": "5 days","C": "1 day match","D": "Test Match"},"answer": "D"},
{ "question": "One who stands behind the stumps is captain.  True/False","type": "single","options" : {"A": "True","B": "","C": "","D": "False"},"answer": "D"},
{ "question": "The fielder next to wicket keeper is called as ___","type": "single","options" : {"A": "Runner","B": "Bowler","C": "Gully","D": "Slip"},"answer": "D"},
{ "question": "The fielder standing just before the batsman is ___","type": "single","options" : {"A": "Runner","B": "Bowler","C": "Slip","D": "Silly point"},"answer": "D"},
{ "question": "There is something above the stump - that is called as ___","type": "single","options" : {"A": "Wicket","B": "Bat","C": "Wood","D": "Bails"},"answer": "D"},
{ "question": "How many stumps will be there in total","type": "single","options" : {"A": "2","B": "3","C": "4","D": "6"},"answer": "D"},
{ "question": "Umpire stands near the ___","type": "single","options" : {"A": "Bowler","B": "Wicket keeper","C": "Batsman","D": "Non-striking Batsman"},"answer": "D"},
{ "question": "How many umpires are in every match on the ground?","type": "single","options" : {"A": "1","B": "3","C": "4","D": "2"},"answer": "D"},
{ "question": "How many umpires are in every match totally?","type": "single","options" : {"A": "1","B": "2","C": "4","D": "3"},"answer": "D"},
{ "question": "Australia did not like Umpire giving out. What can they do?","type": "single","options" : {"A": "They are still out","B": "They must like","C": "They should slap umpire","D": "They will ask Review DRS"},"answer": "D"},
{ "question": "Umpire gives out to Kohli. TV umpire slowly watches video and gives not out. Now, Kohli out or not out?","type": "single","options" : {"A": "Out","B": "Kohli can decide","C": "","D": "Not out"},"answer": "D"},
{ "question": "Can bowlers in the team bat?","type": "single","options" : {"A": "No","B": "Only 2 bowlers","C": "","D": "Yes"},"answer": "D"},
{ "question": "Can batters in the team bowl?","type": "single","options" : {"A": "No","B": "Only 2 batters","C": "","D": "Yes"},"answer": "D"},
{ "question": "Bumrah bowls and catches back the ball for OUT. This is called as ","type": "single","options" : {"A": "Bowled","B": "Caught","C": "Run out","D": "Caught and Bowled"},"answer": "D"},
{ "question": "Batsmen are taking runs. Jadeja throws balls at stumps and removes bails before batsman touches line. It is","type": "single","options" : {"A": "Throw out","B": "Ball out","C": "Stump out","D": "Run out"},"answer": "D"},
{ "question": "Pranev and Kohli are in crease. Bumrah is bowling to Pranev.and Pranev runs. Kohli falls down. Jadeja throws ball at stumps near Pranev. Who is out?","type": "single","options" : {"A": "Kolhi - he only slipped","B": "Kohli - He is the captain","C": "Pranev - why did he push","D": "Pranev"},"answer": "D"},
{ "question": "Bumrah is bowling to Warner and Pranev takes catch. Warner's wicket is for ____","type": "single","options" : {"A": "Kohli - captain","B": "Pranev - catch man","C": "India","D": "Bumrah"},"answer": "D"},
{ "question": "Australia took 235 runs. How much Indians should take to win?","type": "single","options" : {"A": "235","B": "230","C": "234","D": "236"},"answer": "D"},
{ "question": "Australia took 7 wickets.  India took 9 wickets. Who won?","type": "single","options" : {"A": "Australia","B": "India","C": "Wicket-wise Australia","D": "Wickets don’t determine"},"answer": "D"},
{ "question": "Position No 1 ?\n &gt;&gt;&gt;gen_cricket","type": "single","options" : {"A": "Bowler","B": "Gully","C": "Umpire","D": "Wicket keeper"},"answer": "D"},
{ "question": "Position No 2 ?\n &gt;&gt;&gt;gen_cricket","type": "single","options" : {"A": "Cover","B": "Wicket keeper","C": "Umpire","D": "Slip"},"answer": "D"},
{ "question": "Position No 3 ?\n &gt;&gt;&gt;gen_cricket","type": "single","options" : {"A": "Cover","B": "Wicket keeper","C": "Slip","D": "Gully"},"answer": "D"},
{ "question": "Position No 5 ?\n &gt;&gt;&gt;gen_cricket","type": "single","options" : {"A": "Gully","B": "Cover","C": "Slip","D": "Cover"},"answer": "D"},
{ "question": "Position No 6 ?\n &gt;&gt;&gt;gen_cricket","type": "single","options" : {"A": "Gully","B": "Mid wicket","C": "Slip","D": "Third man"},"answer": "D"},
{ "question": "Position No 7 ?\n &gt;&gt;&gt;gen_cricket","type": "single","options" : {"A": "Cover","B": "Gully","C": "Third man","D": "Fine leg"},"answer": "D"},
{ "question": "Position No 8 ?\n &gt;&gt;&gt;gen_cricket","type": "single","options" : {"A": "Fine leg","B": "Gully","C": "Slip","D": "Mid wicket"},"answer": "D"},


]

