var qbLanguageArts = [

{ "question": "Plural of Apple?","type": "single","options" : {"A": "Applies","B": "Applen","C": "Appubs","D": "Apples"},"answer": "D"},
{ "question": "Plural for Baby?","type": "single","options" : {"A": "Baben","B": "Babie","C": "Babes","D": "Babies"},"answer": "D"},
{ "question": "Which is the 1st person?","type": "single","options" : {"A": "1","B": "You","C": "They","D": "I"},"answer": "D"},
{ "question": "Which is the 2nd and 3rd person?","type": "single","options" : {"A": "He & You","B": "I & You","C": "She & He","D": "You & He"},"answer": "D"},
{ "question": "Plural for He / She / It","type": "single","options" : {"A": "You","B": "All","C": "Incorrect Question","D": "They"},"answer": "D"},
{ "question": "If many lions are there, how do u address?","type": "single","options" : {"A": "It","B": "You all","C": "Hey","D": "They"},"answer": "D"},
{ "question": "What is plural of You?","type": "single","options" : {"A": "Yours","B": "Your","C": "None","D": "You"},"answer": "D"},
{ "question": "The hen laid __ egg","type": "single","options" : {"A": "a","B": "the","C": "there","D": "an"},"answer": "D"},
{ "question": "He gave me __ apple.  __ apple was rotten","type": "single","options" : {"A": "a & a","B": "an & an","C": "the & an","D": "an & the"},"answer": "D"},
{ "question": "Our neighbours have shifted to __ new house","type": "single","options" : {"A": "an","B": "the","C": "they","D": "a"},"answer": "D"},
{ "question": "__ pack of wolves attacked __ traveller","type": "single","options" : {"A": "an & an","B": "an & the","C": "the & an","D": "a & a"},"answer": "D"},
{ "question": "__ Taj Mahal was built by Shah Jahan","type": "single","options" : {"A": "a","B": "an","C": "they","D": "the"},"answer": "D"},
{ "question": "___ Ganges is a holy river of __ Hindus","type": "single","options" : {"A": "a & a","B": "a & an","C": "an & an","D": "the & the"},"answer": "D"},
{ "question": "Judy plays __ violin and Joan plays __ guitar","type": "single","options" : {"A": "the & the","B": "a & an","C": "an & an","D": "a & a"},"answer": "D"},
{ "question": "She put ___ letter in __ envelope.","type": "single","options" : {"A": "a","B": "an","C": "the","D": "a & an"},"answer": "D"},
{ "question": "__ train [Use the right article]","type": "single","options" : {"A": "an","B": "the","C": "there","D": "a"},"answer": "D"},
{ "question": "__ glass [Use the right article]","type": "single","options" : {"A": "an","B": "the","C": "there","D": "a"},"answer": "D"},
{ "question": "__ tree [Use the right article]","type": "single","options" : {"A": "an","B": "the","C": "there","D": "a"},"answer": "D"},
{ "question": "__ octopus [Use the right article]","type": "single","options" : {"A": "a","B": "the","C": "there","D": "an"},"answer": "D"},
{ "question": "__ eagle [Use the right article]","type": "single","options" : {"A": "a","B": "the","C": "there","D": "an"},"answer": "D"},
{ "question": "__ ape [Use the right article]","type": "single","options" : {"A": "a","B": "the","C": "there","D": "an"},"answer": "D"},
{ "question": "__ duck [Use the right article]","type": "single","options" : {"A": "an","B": "the","C": "there","D": "a"},"answer": "D"},
{ "question": "__ oven [Use the right article]","type": "single","options" : {"A": "a","B": "the","C": "there","D": "an"},"answer": "D"},
{ "question": "__ insect [Use the right article]","type": "single","options" : {"A": "a","B": "the","C": "there","D": "an"},"answer": "D"},
{ "question": "__ umbrella [Use the right article]","type": "single","options" : {"A": "a","B": "the","C": "there","D": "an"},"answer": "D"},
{ "question": "Replace with Pronoun: [Karan and I] stood first in the class.","type": "single","options" : {"A": "He","B": "She","C": "It","D": "We"},"answer": "D"},
{ "question": "Replace with Pronoun: [Farmers] are ploughing in the field","type": "single","options" : {"A": "It","B": "Them","C": "We","D": "They"},"answer": "D"},
{ "question": "Replace with Pronoun: [The cat] is sleeping","type": "single","options" : {"A": "He","B": "She","C": "They","D": "It"},"answer": "D"},
{ "question": "Replace with Pronoun: [Ankit and Anirud] will go for a movie today","type": "single","options" : {"A": "He","B": "We","C": "She","D": "They"},"answer": "D"},
{ "question": "[Capitals] I saw a ___","type": "single","options" : {"A": "lion","B": "LION","C": "lioN","D": "Lion"},"answer": "D"},
{ "question": "[Capitals] ___ was drinking Boost.","type": "single","options" : {"A": "i","B": "boost","C": "drink","D": "I"},"answer": "D"},
{ "question": "[Capitals] I saw my friend ___","type": "single","options" : {"A": "pranesh","B": "PRANESH","C": "pranesH","D": "Pranesh"},"answer": "D"},
{ "question": "[Capitals] This is my cousing ___","type": "single","options" : {"A": "Raagi","B": "raagini","C": "RAAGINI","D": "Raagini"},"answer": "D"},
{ "question": "[Capitals] I read the book","type": "single","options" : {"A": "Nate The Great","B": "nate the great","C": "NATE THE GREAT","D": "Nate the Great"},"answer": "D"},
{ "question": "[Capitals] the cat in the hat - right way of writing?","type": "single","options" : {"A": "The Cat in the hat","B": "the Cat in the Hat","C": "The cat in the hat","D": "The Cat in the Hat"},"answer": "D"},
{ "question": "[Which word to be Capitalized] my favorite book is jungle book","type": "single","options" : {"A": "Favorite, Jungle","B": "Book","C": "Jungle","D": "My"},"answer": "D"},
{ "question": "[Which word to be Capitalized] on sunday, i will see the movie cars","type": "single","options" : {"A": "I","B": "Cars","C": "Sunday, I, Cars","D": "I, Cars"},"answer": "D"},
{ "question": "[Which word to be Capitalized] did u know shalini is my cousin?","type": "single","options" : {"A": "Shalini","B": "Shalini, Cousin","C": "Did","D": "Did, Shalini, cousin"},"answer": "D"},
{ "question": "Which is not the title of the respect","type": "single","options" : {"A": "Mr.","B": "Dr.","C": "Ms.","D": "Doc."},"answer": "D"},
{ "question": "Which are the right titles of respect?","type": "single","options" : {"A": "Mr Ms Doc","B": "Man, Mr Mister","C": "Master, Mr.","D": "Mr Ms Mrs"},"answer": "D"},
{ "question": "[Use right title] __ Pranev","type": "single","options" : {"A": "Dr.","B": "Ms.","C": "Doc.","D": "Mr."},"answer": "D"},
{ "question": "[Use right title] __ Yogita","type": "single","options" : {"A": "Mr.","B": "Dr.","C": "Doc.","D": "Ms."},"answer": "D"},
{ "question": "[Use right title] __ Lalitharchana","type": "single","options" : {"A": "Mr.","B": "Dr.","C": "Ms.","D": "Mrs."},"answer": "D"},
{ "question": "[Punctuation] My favorite colors are __","type": "single","options" : {"A": "blue and yellow and orange","B": "blue, yellow, orage","C": "blue and yellow, orange","D": "blue, yellow and orange"},"answer": "D"},
{ "question": "[Punctuation] My favorite toys are __","type": "single","options" : {"A": "car doll and fidget","B": "car and fidget and doll","C": "car and fidget and doll","D": "car, doll and fidget"},"answer": "D"},
{ "question": "[Punctuation] Which is right?","type": "single","options" : {"A": "Yes I know him","B": "Yes, I, know him","C": "Yes and I know him","D": "Yes, I know him"},"answer": "D"},
{ "question": "[Punctuation] Which is right?","type": "single","options" : {"A": "Try try try again","B": "Try, try and try again","C": "try and again","D": "Try, try, try again"},"answer": "D"},
{ "question": "[Punctuation] Which is right?  Pranev is ___","type": "single","options" : {"A": "naughty strong boy","B": "naughty, strong, boy","C": "naughty, strong, playful boy","D": "naughty, strong and playful boy"},"answer": "D"},
{ "question": "[Punctuation] Hurray ___ RCB team won the match","type": "single","options" : {"A": ",","B": "?","C": ":","D": "!"},"answer": "D"},
{ "question": "[Punctuation] How are you __","type": "single","options" : {"A": ",","B": "!","C": ":","D": "?"},"answer": "D"},
{ "question": "[Punctuation] I am going to watch a movie today ___","type": "single","options" : {"A": ",","B": "?","C": ":","D": "."},"answer": "D"},
{ "question": "[Punctuation] Ouch __ you pressed my finger __","type": "single","options" : {"A": ", .","B": "! ?","C": "! ?","D": "! ."},"answer": "D"},
{ "question": "[Punctuation] Is it sunny outside __","type": "single","options" : {"A": ",","B": ".","C": ":","D": "?"},"answer": "D"},
{ "question": "[Punctuation] How did you come to school __","type": "single","options" : {"A": ",","B": ".","C": ":","D": "?"},"answer": "D"},
{ "question": "[Punctuation] Hi ___ I am going to school.","type": "single","options" : {"A": ",","B": ".","C": "?","D": "!"},"answer": "D"},
{ "question": "[Punctuation] Which one is used for expressing sudden emotion?","type": "single","options" : {"A": "&lt;&gt;","B": "?","C": ",","D": "!"},"answer": "D"},
{ "question": "Plural of book?","type": "single","options" : {"A": "bookes","B": "bookies","C": "boks","D": "books"},"answer": "D"},
{ "question": "Plural of eraser?","type": "single","options" : {"A": "erasery","B": "eraseries","C": "essers","D": "erasers"},"answer": "D"},
{ "question": "Plural of lunch box?","type": "single","options" : {"A": "lunches box","B": "lunches boxes","C": "","D": "lunch boxes"},"answer": "D"},
{ "question": "Plural of ox?","type": "single","options" : {"A": "oxes","B": "oxs","C": "oxin","D": "oxen"},"answer": "D"},
{ "question": "Plural of match?","type": "single","options" : {"A": "matchs","B": "mathchies","C": "Master, Mr.","D": "matches"},"answer": "D"},
{ "question": "Plural of bus?","type": "single","options" : {"A": "buss","B": "busn","C": "busies","D": "buses"},"answer": "D"},
{ "question": "Plural of potato?","type": "single","options" : {"A": "potatos","B": "potaten","C": "potas","D": "potatoes"},"answer": "D"},
{ "question": "Plural of calf?","type": "single","options" : {"A": "calfs","B": "calfies","C": "calfen","D": "calves"},"answer": "D"},
{ "question": "Plural of baby?","type": "single","options" : {"A": "babes","B": "babys","C": "babyes","D": "babies"},"answer": "D"},
{ "question": "Plural of deer?","type": "single","options" : {"A": "deers","B": "deeries","C": "dreeis","D": "deer"},"answer": "D"},
{ "question": "Plural of fish?","type": "single","options" : {"A": "fishie","B": "fishes","C": "fishs","D": "fish"},"answer": "D"},
{ "question": "Are there words which does not have singular?","type": "single","options" : {"A": "No such word","B": "Sometimes","C": "None of the above","D": "Yes"},"answer": "D"},
{ "question": "Plural of scissors?","type": "single","options" : {"A": "sciss","B": "scissor","C": "scicies","D": "scissors"},"answer": "D"},
{ "question": "Plural of people?","type": "single","options" : {"A": "peop","B": "peoples","C": "pupils","D": "people"},"answer": "D"},
{ "question": "Singular of children?","type": "single","options" : {"A": "childrens","B": "childs","C": "chill","D": "child"},"answer": "D"},
{ "question": "Noun is name of __ __ __ ___","type": "single","options" : {"A": "person boy man thing","B": "person boy girl animal","C": "person thing animal","D": "person place animal thing"},"answer": "D"},
{ "question": "2 kinds of nouns are __ and __","type": "single","options" : {"A": "common come-on","B": "mine and yours","C": "correct and common","D": "common and proper"},"answer": "D"},
{ "question": "Which is not example of common noun?","type": "single","options" : {"A": "hospital","B": "hotel","C": "dog","D": "Kavya"},"answer": "D"},
{ "question": "Which is example of common noun?","type": "single","options" : {"A": "Pranev","B": "Kavya","C": "Pranesh","D": "School"},"answer": "D"},
{ "question": "Which noun has the plural form?","type": "single","options" : {"A": "Plural noun","B": "Proper noun","C": "Pranev noun","D": "Common noun"},"answer": "D"},
{ "question": "Proper noun always starts with ___ ","type": "single","options" : {"A": "The","B": "fullstop","C": "comma","D": "Capital letter"},"answer": "D"},
{ "question": "Pick the pair that are only proper nouns","type": "single","options" : {"A": "Month January","B": "Month Calendar","C": "Date Month","D": "January Febraury"},"answer": "D"},
{ "question": "Pick the pair that are only proper nouns","type": "single","options" : {"A": "Boy, Girl","B": "Pranev, Boy","C": "Pranev, They","D": "John, Tommy"},"answer": "D"},
{ "question": "Pick common noun: The sparrow is a small bird","type": "single","options" : {"A": "Sparrow","B": "small","C": "The","D": "bird"},"answer": "D"},
{ "question": "Pick common noun: Now there are no houses in the city.","type": "single","options" : {"A": "houses","B": "city","C": "there, houses","D": "houses, city"},"answer": "D"},
{ "question": "Pick common noun: It loves to play balls.","type": "single","options" : {"A": "It, balls","B": "play","C": "It","D": "balls"},"answer": "D"},
{ "question": "Pick proper noun: Kavya is such a good girl","type": "single","options" : {"A": "girl","B": "such","C": "good","D": "Kavya"},"answer": "D"},
{ "question": "___ is an action word.","type": "single","options" : {"A": "Noun","B": "Proper","C": "Article","D": "Verb"},"answer": "D"},
{ "question": "Find the verb: Kavya runs very fast","type": "single","options" : {"A": "Kavya","B": "very","C": "the","D": "runs"},"answer": "D"},
{ "question": "Find the verb: The boy stood still","type": "single","options" : {"A": "The","B": "boy","C": "still","D": "stood"},"answer": "D"},
{ "question": "Find the verb: Annie writes will","type": "single","options" : {"A": "Annie","B": "The","C": "will","D": "writes"},"answer": "D"},
{ "question": "Find the verb: The dog chased the cat.","type": "single","options" : {"A": "The","B": "the","C": "dog, cat","D": "chased"},"answer": "D"},
{ "question": "Find the verb: The thief jumped over the wall","type": "single","options" : {"A": "The","B": "thief","C": "wall","D": "jumped"},"answer": "D"},
{ "question": "Verb: Another kind of verb tells what something is ___","type": "single","options" : {"A": "Main verb","B": "Auxillary verb","C": "The verb","D": "Being verb"},"answer": "D"},
{ "question": "Which is the being verb?","type": "single","options" : {"A": "Run","B": "Walk","C": "Go","D": "Am"},"answer": "D"},
{ "question": "Which is not the being verb?","type": "single","options" : {"A": "Am","B": "is","C": "are","D": "come"},"answer": "D"},
{ "question": "Which is being verb set","type": "single","options" : {"A": "are, come","B": "are, go","C": "go, is","D": "am, is"},"answer": "D"},
{ "question": "____ verbs help in making statements or they express links.","type": "single","options" : {"A": "Main verb","B": "The verb","C": "Am verb","D": "Being verb"},"answer": "D"},
{ "question": "[Find the being verb]: He is a good boy","type": "single","options" : {"A": "He","B": "a","C": "boy","D": "is"},"answer": "D"},
{ "question": "[Find the being verb]: I have 20 cars","type": "single","options" : {"A": "20","B": "cars","C": "I","D": "have"},"answer": "D"},
{ "question": "Some verbs do not show 'action'. They are called as ___","type": "single","options" : {"A": "verb","B": "main verb","C": "action verb","D": "being verb"},"answer": "D"},
{ "question": "There ___ book shops across the street [Which being verb you will use?]","type": "single","options" : {"A": "was","B": "am","C": "is","D": "are"},"answer": "D"},
{ "question": "There children ___ far away from home. [Which being verb you will use?]","type": "single","options" : {"A": "was","B": "am","C": "is","D": "were"},"answer": "D"},
{ "question": "Pranev ___ new cars. [Which being verb you will use?]","type": "single","options" : {"A": "have","B": "are","C": "am","D": "has"},"answer": "D"},
{ "question": "Pranev and Kavya ___ many dresses. [Which being verb you will use?]","type": "single","options" : {"A": "has","B": "are","C": "am","D": "have"},"answer": "D"},
{ "question": "[Which word has this meaning:] open ones mouth wide and taking in lots of air.","type": "single","options" : {"A": "breathe","B": "gasp","C": "asthma","D": "yawn"},"answer": "D"},
{ "question": "Tell the meaning: imitators","type": "single","options" : {"A": "people who inject","B": "people who sleep","C": "people who stand","D": "people who copy actions"},"answer": "D"},
{ "question": "Two types of sentences are:","type": "single","options" : {"A": "statements and verbs","B": "questions and verbs","C": "verbs and nouns","D": "statements and questions"},"answer": "D"},
{ "question": "A statement is a stence that states a ___","type": "single","options" : {"A": "question","B": "number","C": "noun","D": "fact"},"answer": "D"},
{ "question": "Every statement contains ___","type": "single","options" : {"A": "there","B": "are","C": "nouns","D": "verb"},"answer": "D"},
{ "question": "Which is the statement","type": "single","options" : {"A": "Where are u?","B": "Who are you?","C": "Did you eat","D": "I ate apple"},"answer": "D"},
{ "question": "A question always ends with ___","type": "single","options" : {"A": "fullstop","B": "exclamation mark","C": "…","D": "question mark"},"answer": "D"},
{ "question": "Sentence that starts with 'who' is ___","type": "single","options" : {"A": "statement","B": "fullstop","C": "exclamation","D": "question"},"answer": "D"},
{ "question": "Why do you think he cried? Example of ___","type": "single","options" : {"A": "Statement","B": "Answer","C": "exclamation","D": "Question"},"answer": "D"},
{ "question": "What are you doing now? Is ___","type": "single","options" : {"A": "Statement","B": "Answer","C": "exclamation","D": "Question"},"answer": "D"},
{ "question": "Sam is playing cricket","type": "single","options" : {"A": "Question","B": "Answer","C": "exclamation","D": "Statement"},"answer": "D"},
{ "question": "Which of these pencils are yours?","type": "single","options" : {"A": "Statement","B": "Answer","C": "exclamation","D": "Question"},"answer": "D"},
{ "question": "[Phonics] make --&gt; Which is silent?","type": "single","options" : {"A": "m","B": "a","C": "k","D": "e"},"answer": "D"},
{ "question": "[Phonics] make --&gt; Which is long?","type": "single","options" : {"A": "m","B": "k","C": "e","D": "a"},"answer": "D"},
{ "question": "[Phonics] huge --&gt; Which is silent?","type": "single","options" : {"A": "h","B": "u","C": "g","D": "e"},"answer": "D"},
{ "question": "[Phonics] huge --&gt; Which is long?","type": "single","options" : {"A": "h","B": "g","C": "e","D": "u"},"answer": "D"},
{ "question": "[Phonics] think --&gt; Which is digraph?","type": "single","options" : {"A": "hi","B": "nk","C": "hink","D": "th"},"answer": "D"},
{ "question": "[Phonics] double consonants: 'better' - Where does the break come?","type": "single","options" : {"A": "bett/er","B": "be/tter","C": "b/ett/er","D": "bet/ter"},"answer": "D"},
{ "question": "[Phonics] double consonants: 'shopping' - Where does the break come?","type": "single","options" : {"A": "shopp/ing","B": "sh/opping","C": "shoppi/ng","D": "shop/ping"},"answer": "D"},
{ "question": "[Phonics] Syllabicate this: himself","type": "single","options" : {"A": "hims/elf","B": "himsel/f","C": "hi/mself","D": "him/self"},"answer": "D"},
{ "question": "[Phonics] Syllabicate this: yellow","type": "single","options" : {"A": "yell/ow","B": "yello/w","C": "/yellow/","D": "yel/low"},"answer": "D"},
{ "question": "[Phonics] Syllabicate this: weather","type": "single","options" : {"A": "wea/ther","B": "we/ather","C": "/weather/","D": "weath/er"},"answer": "D"},
{ "question": "[Phonics] Syllabicate this: exclaimed","type": "single","options" : {"A": "exclaim/ed","B": "excl/aimed","C": "exclaimed/","D": "ex/claimed"},"answer": "D"},
{ "question": "[Phonics] Which has a long 'e' sound?","type": "single","options" : {"A": "break","B": "head","C": "health","D": "eat"},"answer": "D"},
{ "question": "[Phonics] Which has a long 'a' sound?","type": "single","options" : {"A": "leaf","B": "peach","C": "leather","D": "great"},"answer": "D"},
{ "question": "[Phonics] Which has a short 'e' sound?","type": "single","options" : {"A": "leaf","B": "peach","C": "great","D": "leather"},"answer": "D"},
{ "question": "Tell the opposite gender: boy","type": "single","options" : {"A": "boyess","B": "girl","C": "girlte","D": "boyte"},"answer": "D"},
{ "question": "Tell the opposite gender: son","type": "single","options" : {"A": "soness","B": "sun","C": "sons","D": "daughter"},"answer": "D"},
{ "question": "Tell the opposite gender: husband","type": "single","options" : {"A": "lady","B": "gent","C": "man","D": "wife"},"answer": "D"},
{ "question": "Tell the opposite gender: brother","type": "single","options" : {"A": "bro","B": "sis","C": "brothers","D": "sister"},"answer": "D"},
{ "question": "Tell the opposite gender: lioness","type": "single","options" : {"A": "lions","B": "tiger","C": "cat","D": "lion"},"answer": "D"},
{ "question": "Tell the opposite gender: author","type": "single","options" : {"A": "authors","B": "authra","C": "none","D": "authoress"},"answer": "D"},
{ "question": "Tell the opposite gender: actor","type": "single","options" : {"A": "actoress","B": "actors","C": "acss","D": "actress"},"answer": "D"},
{ "question": "Tell the opposite gender: tiger","type": "single","options" : {"A": "tigers","B": "tigeress","C": "none","D": "tigress"},"answer": "D"},
{ "question": "Tell the opposite gender: hunter","type": "single","options" : {"A": "hunters","B": "hunter","C": "hunt","D": "huntress"},"answer": "D"},
{ "question": "Tell the opposite gender: master","type": "single","options" : {"A": "mastress","B": "mister","C": "masters","D": "mistress"},"answer": "D"},
{ "question": "Tell the opposite gender: prince","type": "single","options" : {"A": "princy","B": "princs","C": "princes","D": "princess"},"answer": "D"},
{ "question": "Tell the opposite gender: grandfather","type": "single","options" : {"A": "grandfathress","B": "granny","C": "paatti","D": "grandmother"},"answer": "D"},
{ "question": "Tell the opposite gender: peacock","type": "single","options" : {"A": "peacockess","B": "peas","C": "peanuts","D": "peahen"},"answer": "D"},
{ "question": "Tell the opposite gender: fisherman","type": "single","options" : {"A": "fisherlady","B": "fishress","C": "fishes","D": "fisherwoman"},"answer": "D"},
{ "question": "Select right word: The ___ (king/queen) went into the hall and ate his lunch.","type": "single","options" : {"A": "queen","B": "dog","C": "cat","D": "king"},"answer": "D"},
{ "question": "Select right word: The ___ (prince / princess) played with his friends.","type": "single","options" : {"A": "princess","B": "play","C": "ball","D": "prince"},"answer": "D"},
{ "question": "Select right word: Her ___ (husband/wife) has gone to London.","type": "single","options" : {"A": "wife","B": "london","C": "aeroplane","D": "husband"},"answer": "D"},
{ "question": "Select right word: This is my __ (niece/nephew). She is very intelligent.","type": "single","options" : {"A": "nephew","B": "nieces","C": "nephews","D": "niece"},"answer": "D"},
{ "question": "Tell the opposite gender: horse","type": "single","options" : {"A": "horsees","B": "horses","C": "maress","D": "mare"},"answer": "D"},
{ "question": "Tell the opposite gender: bull","type": "single","options" : {"A": "bulldog","B": "bulless","C": "ox","D": "cow"},"answer": "D"},
{ "question": "Tell the opposite gender: duck","type": "single","options" : {"A": "ducksie","B": "duckess","C": "drik","D": "drake"},"answer": "D"},
{ "question": "Tell the opposite gender: billy goat","type": "single","options" : {"A": "goatess","B": "goats","C": "granny","D": "nanny goat"},"answer": "D"},
{ "question": "[Where to use pronoun]\nOnce when Charlie was walking, Charlie passed a shoe shop.","type": "single","options" : {"A": "Once when he was walking","B": "he was walking to shop","C": "he passed walking","D": "he passed a shoe shop"},"answer": "D"},
{ "question": "The words that are used to replace nouns are called as ___","type": "single","options" : {"A": "verb","B": "being verb","C": "action verb","D": "pronouns"},"answer": "D"},
{ "question": "Which of the following cannot be used as pronoun?","type": "single","options" : {"A": "He","B": "She","C": "I","D": "Girl"},"answer": "D"},
{ "question": "Don’t keep repeating nouns again and again. Use ___","type": "single","options" : {"A": "verb","B": "tomato","C": "common noun","D": "pronouns"},"answer": "D"},
{ "question": "Pronoun is sometimes called as ___","type": "single","options" : {"A": "common noun","B": "proper noun","C": "noun verb","D": "noun helper"},"answer": "D"},
{ "question": "Rajiv is good boy. Rajiv helps. [How to use pronoun]","type": "single","options" : {"A": "He is good boy. He helps.","B": "He is good boy. Rajiv help","C": "Rajiv helps.","D": "Rajiv is good boy. He helps"},"answer": "D"},
{ "question": "While speaking about pronouns, we have ___ persons in English","type": "single","options" : {"A": "one","B": "two","C": "zero","D": "three"},"answer": "D"},
{ "question": "Examples of first person is: ","type": "single","options" : {"A": "I, You","B": "I, He","C": "We, You","D": "I, We"},"answer": "D"},
{ "question": "Examples of first person does not include: ","type": "single","options" : {"A": "I","B": "We","C": "I, We","D": "She"},"answer": "D"},
{ "question": "Examples of second person is: ","type": "single","options" : {"A": "He","B": "She","C": "I","D": "You"},"answer": "D"},
{ "question": "Examples of second person does not include: ","type": "single","options" : {"A": "You","B": "Your","C": "Yours","D": "They"},"answer": "D"},
{ "question": "Examples of third person is: ","type": "single","options" : {"A": "I","B": "Your","C": "We","D": "He"},"answer": "D"},
{ "question": "Examples of second person does not include: ","type": "single","options" : {"A": "He","B": "She","C": "They","D": "You"},"answer": "D"},
{ "question": "First Person is the Person ____","type": "single","options" : {"A": "Drinking","B": "Breathing","C": "Running","D": "Speaking"},"answer": "D"},
{ "question": "Which is the plural of the first person?","type": "single","options" : {"A": "I","B": "They","C": "Them","D": "We"},"answer": "D"},
{ "question": "Which is the plural of 'You'?","type": "single","options" : {"A": "Yous","B": "Yours","C": "Your","D": "You"},"answer": "D"},
{ "question": "Which is the singular of 'You'?","type": "single","options" : {"A": "Yous","B": "Yours","C": "Your","D": "You"},"answer": "D"},
{ "question": "Which is the plural of 'He'?","type": "single","options" : {"A": "Hees","B": "Hes","C": "Her","D": "They"},"answer": "D"},
{ "question": "Which is the plural of 'She'?","type": "single","options" : {"A": "Shers","B": "We","C": "It","D": "They"},"answer": "D"},
{ "question": "Which is the plural of 'It'?","type": "single","options" : {"A": "Its","B": "It","C": "We","D": "They"},"answer": "D"},
{ "question": "It' is First or Second or Third person?","type": "single","options" : {"A": "First","B": "Second","C": "Fifth","D": "Third"},"answer": "D"},
{ "question": "They' is First or Second or Third person?","type": "single","options" : {"A": "First","B": "Second","C": "Fifth","D": "Third"},"answer": "D"},
{ "question": "Third Person Plural is ___","type": "single","options" : {"A": "I","B": "We","C": "He","D": "They"},"answer": "D"},
{ "question": "Second Person Plural is ___","type": "single","options" : {"A": "I","B": "They","C": "He","D": "You"},"answer": "D"},
{ "question": "Identify the pronoun: ___ is a good girl","type": "single","options" : {"A": "He","B": "Kavya","C": "Kenisha","D": "She"},"answer": "D"},
{ "question": "Put the pronoun: Tommy is hungry. __ needs some food.","type": "single","options" : {"A": "He","B": "Tommy","C": "Dog","D": "It"},"answer": "D"},
{ "question": "Put the pronoun: (Alvin and Siya) ____ like to sleep with their dad.","type": "single","options" : {"A": "He","B": "It","C": "Them","D": "They"},"answer": "D"},
{ "question": "Put the pronoun: Why does (Pranev) ___ always try to catch butterflies?","type": "single","options" : {"A": "They","B": "It","C": "Them","D": "He"},"answer": "D"},
{ "question": "Put the pronoun: (Kavya) ___ broker her new toy.","type": "single","options" : {"A": "He","B": "It","C": "Kavya","D": "She"},"answer": "D"},
{ "question": "Put the pronoun: Peter is absent because ___ is not well.","type": "single","options" : {"A": "Peter","B": "Boy","C": "She","D": "He"},"answer": "D"},
{ "question": "Put the pronoun: The man tried to lift the stone, but could not as ___ was too heavy.","type": "single","options" : {"A": "Stone","B": "Man","C": "He","D": "It"},"answer": "D"},
{ "question": "Put the pronoun: The girl sang sweetly. Everyone listened to ___.","type": "single","options" : {"A": "Song","B": "Sang","C": "She","D": "It"},"answer": "D"},
{ "question": "Put the pronoun: Dad could not find his tool, so ___ used a screwdriver instead.","type": "single","options" : {"A": "He","B": "Dad","C": "Screw","D": "It"},"answer": "D"},
{ "question": "First Person / Singular","type": "single","options" : {"A": "We","B": "Us","C": "They","D": "I"},"answer": "D"},
{ "question": "Second Person / Plural","type": "single","options" : {"A": "I","B": "We","C": "Us","D": "You"},"answer": "D"},
{ "question": "Second Person / Singular","type": "single","options" : {"A": "I","B": "We","C": "Us","D": "You"},"answer": "D"},
{ "question": "First Person / Plural","type": "single","options" : {"A": "I","B": "They","C": "Them","D": "We"},"answer": "D"},
{ "question": "Which is Third Person / Singular","type": "single","options" : {"A": "You","B": "I","C": "You","D": "He"},"answer": "D"},
{ "question": "Which is not Third Person / Singular","type": "single","options" : {"A": "He","B": "She","C": "It","D": "I"},"answer": "D"},
{ "question": "Which is Third Person / Plural","type": "single","options" : {"A": "He","B": "She","C": "It","D": "They"},"answer": "D"},
{ "question": "Which is not Third Person / Plural","type": "single","options" : {"A": "They","B": "Them","C": "Them","D": "It"},"answer": "D"},
{ "question": "Replace with Pronoun: (Karan and I) ___ stood first in the class.","type": "single","options" : {"A": "They","B": "Us","C": "I","D": "We"},"answer": "D"},
{ "question": "Replace with Pronoun: (The cat) ___ is sleeping.","type": "single","options" : {"A": "He","B": "She","C": "They","D": "It"},"answer": "D"},
{ "question": "Replace with Pronoun: (Children) ___ are shouting.","type": "single","options" : {"A": "Child","B": "He and She","C": "Them","D": "They"},"answer": "D"},
{ "question": "Pronoun: Which is the 'DOER' of the action?","type": "single","options" : {"A": "Him","B": "Her","C": "Them","D": "He"},"answer": "D"},
{ "question": "Pronoun: Which is the 'DOER' of the action?","type": "single","options" : {"A": "We","B": "Us","C": "Me","D": "I"},"answer": "D"},
{ "question": "Pronoun: Which is not the 'DOER' of the action?","type": "single","options" : {"A": "I","B": "We","C": "He","D": "Him"},"answer": "D"},
{ "question": "Pronoun: Which is the 'RECEIVER' of the action?","type": "single","options" : {"A": "We","B": "I","C": "He","D": "Me"},"answer": "D"},
{ "question": "Pronoun: Which is the 'RECEIVER' of the action?","type": "single","options" : {"A": "They","B": "We","C": "He","D": "Them"},"answer": "D"},
{ "question": "Pronoun: Which is not the 'RECEIVER' of the action?","type": "single","options" : {"A": "Him","B": "Her","C": "Them","D": "They"},"answer": "D"},
{ "question": "Put the pronoun: I gave ___ an apple","type": "single","options" : {"A": "She","B": "Hers","C": "He","D": "Her"},"answer": "D"},
{ "question": "Put the pronoun: I lent ___ my bicycle for a day.","type": "single","options" : {"A": "He","B": "Pranesh","C": "Roshan","D": "Him"},"answer": "D"},
{ "question": "Put the pronoun: Dad gifted ___ a video game.","type": "single","options" : {"A": "I","B": "Pranev","C": "Kavya","D": "Me"},"answer": "D"},
{ "question": "Put the pronoun: I got a letter from ___","type": "single","options" : {"A": "They","B": "Me","C": "We","D": "Them"},"answer": "D"},
{ "question": "Words that describe a noun is called as ___","type": "single","options" : {"A": "Adverb","B": "Noun","C": "Pronoun","D": "Adjective"},"answer": "D"},
{ "question": "[Find the adjective] Gracy wore a pink dress.","type": "single","options" : {"A": "dress","B": "wore","C": "Gracy","D": "pink"},"answer": "D"},
{ "question": "[Find the adjective] Paulo carried a red bag","type": "single","options" : {"A": "carried","B": "Paulo","C": "bag","D": "red"},"answer": "D"},
{ "question": "[Find the adjective] The hungry fox searched for food.","type": "single","options" : {"A": "fox","B": "hungry, fox","C": "food","D": "hungry"},"answer": "D"},
{ "question": "[Find the adjective] The hungry brown fox searched for food.","type": "single","options" : {"A": "fox","B": "hungry","C": "food","D": "hungry, brown"},"answer": "D"},
{ "question": "[Find the adjective] The tree bears sweet fruits","type": "single","options" : {"A": "red","B": "tree","C": "fruit","D": "sweet"},"answer": "D"},
{ "question": "[Find the adjective] The girl played with two dolls.","type": "single","options" : {"A": "girl","B": "The","C": "dolls","D": "two"},"answer": "D"},
{ "question": "[Find the adjective] The picture has ten fishes","type": "single","options" : {"A": "picture","B": "fishes","C": "The","D": "ten"},"answer": "D"},
{ "question": "[Find the adjective] The chocolates were round in shape.","type": "single","options" : {"A": "shape","B": "chocolates","C": "were","D": "round"},"answer": "D"},
{ "question": "[Find the adjective] The chicks have tiny toes and feet","type": "single","options" : {"A": "feet","B": "chicks","C": "toes","D": "tiny"},"answer": "D"},
{ "question": "[Find the adjective] Donald wore a blue cap","type": "single","options" : {"A": "Donald","B": "wore","C": "cap","D": "blue"},"answer": "D"},
{ "question": "[Find the adjective] Daisy is wearing a lovely dress","type": "single","options" : {"A": "dress","B": "wearing","C": "Daisy","D": "lovely"},"answer": "D"},
{ "question": "[Find the adjective] Dennis is a naughty boy","type": "single","options" : {"A": "Dennis","B": "boy","C": "is","D": "naughty"},"answer": "D"},
{ "question": "[Find the adjective] Mother baked two cakes for my birthday.","type": "single","options" : {"A": "birthday","B": "cakes","C": "Mother","D": "two"},"answer": "D"},
{ "question": "[Find the adjective] A red rose blossomed in the garden.","type": "single","options" : {"A": "rose","B": "blossomed","C": "garden","D": "red"},"answer": "D"},
{ "question": "[Find the adjective] He bought six mangoes from the vendor.","type": "single","options" : {"A": "mangoes","B": "vendor","C": "bought","D": "six"},"answer": "D"},
{ "question": "[Find the adjective] My house is huge.","type": "single","options" : {"A": "My","B": "house","C": "is","D": "huge"},"answer": "D"},
{ "question": "[Find the adjective] The old woman lived alone.","type": "single","options" : {"A": "woman","B": "lived","C": "alone","D": "old"},"answer": "D"},
{ "question": "[Find the adjective] He has ten balloons.","type": "single","options" : {"A": "He","B": "has","C": "balloons.","D": "ten"},"answer": "D"},
{ "question": "[Find the adjective] The brown monkey swing on the trees.","type": "single","options" : {"A": "monkey","B": "swing","C": "trees","D": "brown"},"answer": "D"},
{ "question": "Pick the adjective that does not describe Kavya.","type": "single","options" : {"A": "Naughty","B": "Small","C": "Cute","D": "Big"},"answer": "D"},
{ "question": "Pick the adjective that does not describe Pranev","type": "single","options" : {"A": "Jumping","B": "Torture","C": "Beautiful","D": "Bad"},"answer": "D"},
{ "question": "Two letters that make one sound is ___","type": "single","options" : {"A": "Diagram","B": "Digression","C": "Diaphram","D": "Digraph"},"answer": "D"},
{ "question": "Which is not Digraph?","type": "single","options" : {"A": "ck","B": "nk","C": "ng","D": "aei"},"answer": "D"},
{ "question": "brick' - which is digraph?","type": "single","options" : {"A": "br","B": "bri","C": "ick","D": "ck"},"answer": "D"},
{ "question": "clock' - which is digraph?","type": "single","options" : {"A": "br","B": "bri","C": "ick","D": "ck"},"answer": "D"},
{ "question": "stink' - which is digraph?","type": "single","options" : {"A": "st","B": "sti","C": "ti","D": "nk"},"answer": "D"},
{ "question": "wink' - which is digraph?","type": "single","options" : {"A": "wi","B": "ink","C": "wik","D": "nk"},"answer": "D"},
{ "question": "ring' - which is digraph?","type": "single","options" : {"A": "ri","B": "rin","C": "ring","D": "ng"},"answer": "D"},
{ "question": "ghost' - which is digraph?","type": "single","options" : {"A": "ghos","B": "ost","C": "st","D": "gh"},"answer": "D"},
{ "question": "rough' - which is digraph?","type": "single","options" : {"A": "rou","B": "oug","C": "oh","D": "gh"},"answer": "D"},
{ "question": "enough' - which is digraph?","type": "single","options" : {"A": "nou","B": "ug","C": "ugh","D": "gh"},"answer": "D"},
{ "question": "laugh' - which is digraph?","type": "single","options" : {"A": "ugh","B": "lau","C": "lgh","D": "gh"},"answer": "D"},
{ "question": "Conjuction? Nigel and Scott like sports","type": "single","options" : {"A": "like","B": "Scott","C": "Nigel","D": "and"},"answer": "D"},
{ "question": "Conjuction?\nHarry likes basketball but not baseball","type": "single","options" : {"A": "not","B": "likes","C": "baseball","D": "but"},"answer": "D"},
{ "question": "Conjuction?\nWill she come by bus or by train?","type": "single","options" : {"A": "she","B": "come","C": "by","D": "or"},"answer": "D"},
{ "question": "Conjuction?\nDad likes pizza and spaghetti","type": "single","options" : {"A": "likes","B": "pizza","C": "Dad","D": "and"},"answer": "D"},
{ "question": "Conjuction?\nWe could walk or jog to the stadium.","type": "single","options" : {"A": "We","B": "could","C": "to","D": "or","E": "the"},"answer": "D"},
{ "question": "Conjuction?\nShe was always friendly but quiet.","type": "single","options" : {"A": "was","B": "always","C": "friendly","D": "but"},"answer": "D"},
{ "question": "Conjuction?\nThe group will take a train or a bus to the central park.","type": "single","options" : {"A": "group","B": "The","C": "will","D": "or","E": "a"},"answer": "D"},
{ "question": "Conjuction?\nEach one of them looks happy and cheerful.","type": "single","options" : {"A": "looks","B": "of","C": "them","D": "and"},"answer": "D"},
{ "question": "Conjuction?\nThe kids are going to the zoo or the museum.","type": "single","options" : {"A": "are","B": "to","C": "the","D": "or"},"answer": "D"},
{ "question": "Conjuction?\nSeema will read the letter but will not write back.","type": "single","options" : {"A": "will","B": "read","C": "the","D": "but"},"answer": "D"},
{ "question": "Conjuction?\nKristen will be at the library __ at school","type": "single","options" : {"A": "and","B": "but","C": "the","D": "or"},"answer": "D"},
{ "question": "Fill conjuction\nSing the song softly __ sweetly","type": "single","options" : {"A": "or","B": "but","C": "the","D": "and"},"answer": "D"},
{ "question": "Fill conjuction\nWould you want hotdogs __ burgers?","type": "single","options" : {"A": "and","B": "but","C": "the","D": "or"},"answer": "D"},
{ "question": "Fill conjuction\nThis park has water rushing loudly ___ wildly over the rocks.","type": "single","options" : {"A": "or","B": "but","C": "the","D": "and"},"answer": "D"},
{ "question": "Fill conjuction\nThe path to the river __ to the house has been flooded","type": "single","options" : {"A": "or","B": "but","C": "the","D": "and"},"answer": "D"},
{ "question": "Fill conjuction\nShe changed into her jeans ___ t-shirt.","type": "single","options" : {"A": "or","B": "but","C": "the","D": "and"},"answer": "D"},
{ "question": "Fill conjuction\nQuickly ___ thoughtfully, she studied the map.","type": "single","options" : {"A": "or","B": "and","C": "the","D": "but"},"answer": "D"},
{ "question": "Fill conjuction\nRumi sings well __ Nikita is better","type": "single","options" : {"A": "or","B": "and","C": "the","D": "but"},"answer": "D"},
{ "question": "Fill conjuction\nThey were tired __ did not give up.","type": "single","options" : {"A": "or","B": "and","C": "the","D": "but"},"answer": "D"},
{ "question": "Fill conjuction\nI called out several times ___ he did not hear.","type": "single","options" : {"A": "or","B": "and","C": "the","D": "but"},"answer": "D"},
{ "question": "Mom __ Dad will bring the picnic basket.","type": "single","options" : {"A": "or","B": "so","C": "the","D": "and"},"answer": "D"},
{ "question": "We could also have lemon juice __ a pizza","type": "single","options" : {"A": "or","B": "so","C": "the","D": "and"},"answer": "D"},
{ "question": "The weather was very cold __ Steven wore gloves","type": "single","options" : {"A": "or","B": "and","C": "the","D": "so"},"answer": "D"},
{ "question": "John was happy ___ it was a holiday","type": "single","options" : {"A": "or","B": "so","C": "and","D": "because"},"answer": "D"},
{ "question": "Cliff is a good batsman ___ Rohan is better","type": "single","options" : {"A": "or","B": "so","C": "and","D": "but"},"answer": "D"},
{ "question": "Payal saw a rainbow in the sky ___ she jumped with joy.","type": "single","options" : {"A": "or","B": "because","C": "the","D": "so"},"answer": "D"},
{ "question": "What do you want, a pin ___ a pen?","type": "single","options" : {"A": "and","B": "so","C": "the","D": "or"},"answer": "D"},
{ "question": "Julie was a good girl ___ she got a sticker","type": "single","options" : {"A": "or","B": "but","C": "the","D": "so"},"answer": "D"},
{ "question": "Preposition?\nRocky and Ronald are hiding behind the tree.","type": "single","options" : {"A": "are","B": "the","C": "tree","D": "behind"},"answer": "D"},
{ "question": "Preposition?\nThey are looking under the table.","type": "single","options" : {"A": "the","B": "are","C": "looking","D": "under"},"answer": "D"},
{ "question": "Preposition?\nDo you think there are prepositions in every sentence?","type": "single","options" : {"A": "are","B": "every","C": "there","D": "in"},"answer": "D"},
{ "question": "Preposition?\nThe road runs through the village.","type": "single","options" : {"A": "runs","B": "the","C": "village","D": "through"},"answer": "D"},
{ "question": "Preposition?\nWho Is sitting near the window?","type": "single","options" : {"A": "Who","B": "the","C": "is","D": "near"},"answer": "D"},
{ "question": "Preposition?\nLook below the first shelf.","type": "single","options" : {"A": "the","B": "first","C": "Look","D": "below"},"answer": "D"},
{ "question": "Preposition?\nWe will go to the park near my house","type": "single","options" : {"A": "will","B": "go","C": "the","D": "near"},"answer": "D"},
{ "question": "Preposition?\nThe goat jumped over the fence.","type": "single","options" : {"A": "The","B": "jumped","C": "goat","D": "over"},"answer": "D"},
{ "question": "Preposition?\nSita walked through the gate.","type": "single","options" : {"A": "walked","B": "the","C": "Sita","D": "through"},"answer": "D"},
{ "question": "Fill Preposition.\nPlease park your car ___ that shop.","type": "single","options" : {"A": "that","B": "your","C": "Please","D": "near"},"answer": "D"},
{ "question": "Fill Preposition.\nThe thief has a scar ___ his right cheek.","type": "single","options" : {"A": "theif","B": "The","C": "in","D": "on"},"answer": "D"},
{ "question": "Fill Preposition.\nMy friends rested ___ the mango tree.","type": "single","options" : {"A": "in","B": "above","C": "below","D": "on"},"answer": "D"},
{ "question": "Fill Preposition.\nThe mouse hid ___ the cupboard.","type": "single","options" : {"A": "with","B": "water","C": "when","D": "behind"},"answer": "D"},
{ "question": "Fill Preposition.\nHe tossed the ball ___ the window into the garden.","type": "single","options" : {"A": "in","B": "water","C": "when","D": "through"},"answer": "D"},
{ "question": "Fill Preposition.\nThe pillow was tucked ___ the bedcover.","type": "single","options" : {"A": "then","B": "under","C": "bed","D": "in"},"answer": "D"},
{ "question": "Fill Preposition.\nLet us meet ___ Monday.","type": "single","options" : {"A": "inside","B": "outside","C": "above","D": "on"},"answer": "D"},
{ "question": "Fill Preposition.\nJack lives ___ Jill's house.","type": "single","options" : {"A": "top of","B": "bottom","C": "behind","D": "near"},"answer": "D"},
{ "question": "Fill Preposition.\nThe vine is hanging ___ the window.","type": "single","options" : {"A": "on","B": "under","C": "come","D": "over"},"answer": "D"},
{ "question": "Fill Preposition.\nI saw him standing ___ the car.","type": "single","options" : {"A": "above","B": "below","C": "but","D": "near"},"answer": "D"},
{ "question": "Fill Preposition.\nThe little girl sat ___ her mother's lap.","type": "single","options" : {"A": "below","B": "above","C": "in","D": "on"},"answer": "D"},
{ "question": "Fill Preposition.\nJessica jumped ___ the bed","type": "single","options" : {"A": "in","B": "under","C": "below","D": "on"},"answer": "D"},
{ "question": "Fill Preposition.\nThe pencil rolled ___ the table","type": "single","options" : {"A": "","B": "","C": "in","D": "under"},"answer": "D"},
{ "question": "Fill Preposition.\nThe ball fell ___ the bushes.","type": "single","options" : {"A": "","B": "","C": "near","D": "through"},"answer": "D"},
{ "question": "Fill Preposition.\nYou will find the answer ___ page 24.","type": "single","options" : {"A": "","B": "","C": "in","D": "on"},"answer": "D"},
{ "question": "Fill Preposition.\nThe fountain is ___ the temple.","type": "single","options" : {"A": "","B": "","C": "through","D": "near"},"answer": "D"},
{ "question": "Fill Preposition.\nThe children are playing ___ the swings.","type": "single","options" : {"A": "","B": "","C": "in","D": "on"},"answer": "D"},
{ "question": "Fill Preposition.\n'Enter ___ the gates' - commanded the officer.","type": "single","options" : {"A": "","B": "","C": "on","D": "through"},"answer": "D"},
{ "question": "Fill Preposition.\nThere is a hospital ___ my house.","type": "single","options" : {"A": "","B": "","C": "in","D": "near"},"answer": "D"},
{ "question": "Fill Preposition.\nThe dog jumped ___ the fence.","type": "single","options" : {"A": "","B": "","C": "through","D": "over"},"answer": "D"},
{ "question": "Adverb?\nKarim played the guitar skillfully.","type": "single","options" : {"A": "played","B": "the","C": "","D": "skillfully"},"answer": "D"},
{ "question": "Adverb?\nThe king ruled his kingdom wisely.","type": "single","options" : {"A": "The","B": "kingdom","C": "his","D": "wisely"},"answer": "D"},
{ "question": "Adverb?\nMy father laughed loudly.","type": "single","options" : {"A": "My","B": "laughed","C": "","D": "loudly"},"answer": "D"},
{ "question": "Adverb?\nThe bird flew swiftly.","type": "single","options" : {"A": "bird","B": "The","C": "","D": "swiftly"},"answer": "D"},
{ "question": "Adverb?\nJohn waited in the queue patiently.","type": "single","options" : {"A": "waited","B": "in","C": "the","D": "patiently"},"answer": "D"},
{ "question": "Adverb?\nThe baby slept soundly.","type": "single","options" : {"A": "The","B": "slept","C": "babyes","D": "soundly"},"answer": "D"},
{ "question": "Adverb?\nJenny held her trophy proudly","type": "single","options" : {"A": "held","B": "her","C": "trophy","D": "proudly"},"answer": "D"},
{ "question": "Adverb?\nThe woman talked to the beggar kindly","type": "single","options" : {"A": ".","B": "talked","C": "to","D": "kindly"},"answer": "D"},
{ "question": "Adverb?\nShe dressed beautifully","type": "single","options" : {"A": "She","B": "dressed","C": ".","D": "beautifully"},"answer": "D"},
{ "question": "Adverb?\nThe tree was swaying gently","type": "single","options" : {"A": "The","B": "tree","C": "swaying","D": "gently"},"answer": "D"},
{ "question": "Adverb?\nThe sun shone brightly.","type": "single","options" : {"A": "The","B": "sun","C": "shone","D": "brightly"},"answer": "D"},
{ "question": "Fill Adverb.\nThe lady sang ___ (sweet)","type": "single","options" : {"A": "with","B": "sweet","C": "","D": "sweetly"},"answer": "D"},
{ "question": "Fill Adverb.\nThe trian came into the station ___ (sudden)","type": "single","options" : {"A": "on","B": "now","C": "yesterday","D": "suddenly"},"answer": "D"},
{ "question": "Fill Adverb.\nOur teacher asked us to do our work ___ (neat)","type": "single","options" : {"A": "today","B": "tomorrow","C": "clearly","D": "neatly"},"answer": "D"},
{ "question": "Fill Adverb.\nThe children were playing ___(happy) on beach","type": "single","options" : {"A": "sad","B": "so much","C": "this much","D": "happily"},"answer": "D"},
{ "question": "Fill Adverb.\nThe wind blew ___ (soft)","type": "single","options" : {"A": "gently","B": "forcifully","C": "","D": "softly"},"answer": "D"},
{ "question": "Fill Adverb.\nAnne ran ___ (quick) to the room.","type": "single","options" : {"A": "slowly","B": "fastly","C": "now","D": "quickly"},"answer": "D"},
{ "question": "Fill Adverb.\nThe lazy lion walked ___ (slow)","type": "single","options" : {"A": "fiercefully","B": "fastly","C": "slyly","D": "slowly"},"answer": "D"},
{ "question": "Fill Adverb.\nThe dog barked ___","type": "single","options" : {"A": "sweetly","B": "hungrily","C": "slowly","D": "loudly"},"answer": "D"},
{ "question": "Fill Adverb.\nBirds sing ___ in the morning","type": "single","options" : {"A": "bravely","B": "hungrily","C": "slowly","D": "sweetly"},"answer": "D"},
{ "question": "Fill Adverb.\nJohn stared at the burger ___","type": "single","options" : {"A": "bravely","B": "loudly","C": "slowly","D": "hungrily"},"answer": "D"},
{ "question": "Fill Adverb.\nRiva danced ___","type": "single","options" : {"A": "carefully","B": "hungrily","C": "sweetly","D": "beautifully"},"answer": "D"},
{ "question": "Fill Adverb.\nThe wounded cat walked ___","type": "single","options" : {"A": "fastly","B": "sweetly","C": "hungrily","D": "slowly"},"answer": "D"},
{ "question": "Fill Adverb.\nThe cop looked at the thief ___","type": "single","options" : {"A": "beautifully","B": "loudly","C": "bravely","D": "angrily"},"answer": "D"},
{ "question": "Fill Adverb.\nIt is pouring ___","type": "single","options" : {"A": "loudly","B": "slowly","C": "beautifully","D": "heavily"},"answer": "D"},
{ "question": "Fill Adverb.\nThe king fought ___","type": "single","options" : {"A": "slowly","B": "loudly","C": "angrily","D": "bravely"},"answer": "D"},
{ "question": "Fill Adverb.\nThe cat eyed the rat ___","type": "single","options" : {"A": "sweetly","B": "angrily","C": "softly","D": "excitedly"},"answer": "D"},
{ "question": "Fill Adverb.\nThis laptop should be handled ___","type": "single","options" : {"A": "bravely","B": "loudly","C": "sweetly","D": "carefully"},"answer": "D"},

]