qbComputers = [

{ "question": "A Computer is a ___ machine that works very fast","type": "single","options" : {"A": "Black","B": "Electric","C": "Current","D": "Electronic"},"answer": "D"},
{ "question": "A Computer works very ___ and does no mistakes","type": "single","options" : {"A": "Smart","B": "Slow","C": "Bad","D": "Fast"},"answer": "D"},
{ "question": "Calculators are ___ than computers","type": "single","options" : {"A": "Big","B": "Tall","C": "Short","D": "Smaller"},"answer": "D"},
{ "question": "Computers can do more than Calculators","type": "single","options" : {"A": "False","B": "At times","C": "Depends on color","D": "True"},"answer": "D"},
{ "question": "Writing letters can be done by __","type": "single","options" : {"A": "Calc & Computers","B": "Calculators","C": "None","D": "Computers"},"answer": "D"},
{ "question": "I want to only do mathematical calculation. I am fine with ___","type": "single","options" : {"A": "Computer","B": "Monitor","C": "Keyboard","D": "Calculator"},"answer": "D"},
{ "question": "I can draw pictures using ___","type": "single","options" : {"A": "Calculators","B": "Calculator and Monitor","C": "Mouse alone","D": "Computer"},"answer": "D"},
{ "question": "Compute' in Computer means:","type": "single","options" : {"A": "Chocolate","B": "Compound","C": "Complex","D": "Calculate"},"answer": "D"},
{ "question": "Computers can work on its own","type": "single","options" : {"A": "Of course","B": "Never","C": "You need keyboard also","D": "Based on your command"},"answer": "D"},
{ "question": "Which is slow in calculation","type": "single","options" : {"A": "Computers","B": "Keyboard","C": "Mouse","D": "Humans"},"answer": "D"},
{ "question": "Computer can remember less. Humans can remember More","type": "single","options" : {"A": "True","B": "False","C": "Only Humans remember","D": "Other way, Computer More, Human Less"},"answer": "D"},
{ "question": "Which have feelings","type": "single","options" : {"A": "Computers","B": "Both","C": "None","D": "Humans"},"answer": "D"},
{ "question": "Which gets bored in doing work","type": "single","options" : {"A": "Computers","B": "Both","C": "None","D": "Humans"},"answer": "D"},
{ "question": "___ can do complex calculation in seconds","type": "single","options" : {"A": "Calculator","B": "Animals","C": "Humans","D": "Computer"},"answer": "D"},
{ "question": "___ does no mistake","type": "single","options" : {"A": "Keyboard","B": "Humans","C": "Rats","D": "Computer"},"answer": "D"},
{ "question": "Some Machine work like Humans with 2 hands 2 legs. They are called as ___","type": "single","options" : {"A": "Computer Human","B": "Android","C": "Cell Phone","D": "Robot"},"answer": "D"},
{ "question": "The most advanced of all Robots is ___","type": "single","options" : {"A": "ARSIMO","B": "ARCTIC","C": "ARTISTIC","D": "ASIMO"},"answer": "D"},
{ "question": "ASIMO stands for ___","type": "single","options" : {"A": "Advanced Success in Innovative Mobility","B": "Advanced Science in Innovative Mobility","C": "Artifical Step in Innovative Mobility","D": "Advanced Step in Innovative Mobility"},"answer": "D"},
{ "question": "Can computer play music and movies?","type": "single","options" : {"A": "Only Movies","B": "Only Music","C": "Only calculation","D": "Music and Movies both"},"answer": "D"},
{ "question": "Can computer play games?","type": "single","options" : {"A": "Only Music and Movies","B": "No Games","C": "Only Drawing","D": "Games also with Music"},"answer": "D"},
{ "question": "Computer comes in multiple sizes","type": "single","options" : {"A": "No","B": "You cannot see it","C": "As same as calculator","D": "Yes"},"answer": "D"},
{ "question": "A mini computer that fits on your lap is","type": "single","options" : {"A": "Personal computer","B": "Thigh computer","C": "Desktop","D": "Laptop"},"answer": "D"},
{ "question": "This computer can only be kept on desk.","type": "single","options" : {"A": "Personal computer","B": "Laptop","C": "Palmtop","D": "Desktop"},"answer": "D"},
{ "question": "____ computer fits on to your palm","type": "single","options" : {"A": "Desktop","B": "Laptop","C": "Tabletop","D": "Palmtop"},"answer": "D"},
{ "question": "Which is not the part of computer","type": "single","options" : {"A": "CPU","B": "Mouse","C": "Keyboard","D": "Wire"},"answer": "D"},
{ "question": "CPU stands for ___","type": "single","options" : {"A": "Center of Processing","B": "Chip Process Unit","C": "Calloc Unit","D": "Central Processing Unit"},"answer": "D"},
{ "question": "Most calculations are done in ___","type": "single","options" : {"A": "Keyboard","B": "Mouse","C": "Monitor","D": "CPU"},"answer": "D"},
{ "question": "This is the brain of the computer. Which one?","type": "single","options" : {"A": "Computer has no brain","B": "Keyboard","C": "Monitor","D": "CPU"},"answer": "D"},
{ "question": "Pictures and Text are displayed on ___","type": "single","options" : {"A": "Watch","B": "Mouse","C": "Palmtop","D": "Monitor"},"answer": "D"},
{ "question": "Another name of Monitor is ___","type": "single","options" : {"A": "TV","B": "CPU","C": "BPU","D": "VDU"},"answer": "D"},
{ "question": "VDU stands for ____","type": "single","options" : {"A": "Visual Dragging Unit","B": "Visual Disco Unit","C": "Video Display Unit","D": "Visual Display Unit"},"answer": "D"},
{ "question": "____ displays the work done on the computer","type": "single","options" : {"A": "TV","B": "VDI","C": "Mouse","D": "VDU"},"answer": "D"},
{ "question": "Mouse can be without wire ","type": "single","options" : {"A": "False","B": "None","C": "Incorrect question","D": "TRUE"},"answer": "D"},
{ "question": "Mouse is a ___ device with a tail.","type": "single","options" : {"A": "drawing","B": "pinning","C": "calculating","D": "pointing"},"answer": "D"},
{ "question": "Mouse contain ____ buttons at least","type": "single","options" : {"A": "one","B": "three","C": "four","D": "two"},"answer": "D"},
{ "question": "____ is used for drawing pictures","type": "single","options" : {"A": "Stylus","B": "Keyboard","C": "Pencil","D": "Mouse"},"answer": "D"},
{ "question": "Mouse draws the pictures on the ____ of a computer","type": "single","options" : {"A": "Keyboard","B": "Mouse","C": "Wire","D": "Monitor"},"answer": "D"},
{ "question": "______ is used to select an object","type": "single","options" : {"A": "Enter","B": "Hover","C": "Space","D": "Click"},"answer": "D"},
{ "question": "To open a document, which one is used?","type": "single","options" : {"A": "Enter","B": "Click","C": "Space","D": "Double Click"},"answer": "D"},
{ "question": "Display commands on the screen","type": "single","options" : {"A": "Click","B": "Double click","C": "Left click","D": "Right click"},"answer": "D"},
{ "question": "To move an icon from one place to another","type": "single","options" : {"A": "Click","B": "Not possible","C": "Write program","D": "Drag Drop"},"answer": "D"},
{ "question": "Mouse that has Scroll wheel is called as ","type": "single","options" : {"A": "Mouse","B": "Multi media mouse","C": "Bluetooth Mous","D": "Scroll Mouse"},"answer": "D"},
{ "question": "Which of the following is not function of mouse","type": "single","options" : {"A": "Drag Drop","B": "Double Click","C": "Single Click","D": "Triple Click"},"answer": "D"},
{ "question": "Whatever you type on keyboard appears on ___","type": "single","options" : {"A": "Printer","B": "Mouse","C": "Device","D": "Monitor"},"answer": "D"},
{ "question": "Starting the computer is called as ____","type": "single","options" : {"A": "Looting","B": "Starting","C": "Kicking","D": "Booting"},"answer": "D"},
{ "question": "Once you start the computer the ____ appears","type": "single","options" : {"A": "Picture","B": "Game","C": "Teams","D": "Desktop"},"answer": "D"},
{ "question": "When you start all switches on computer (Monitor, CPU), the ____ loads","type": "single","options" : {"A": "Heavy weight","B": "Switches","C": "Wires","D": "Operating system"},"answer": "D"},
{ "question": "Stopping the computer is called as _____","type": "single","options" : {"A": "Lock down","B": "Up down","C": "Fit down","D": "Shut down"},"answer": "D"},
{ "question": "Standard number of keys in Keyboard","type": "single","options" : {"A": "101","B": "102","C": "103","D": "104"},"answer": "D"},
{ "question": "Numpad is present in keyboard for","type": "single","options" : {"A": "Just fun","B": "More powerful","C": "Optional","D": "Fast typing numbers"},"answer": "D"},
{ "question": "Lengthiest key in Keyboard is","type": "single","options" : {"A": "Enter","B": "Num Lock","C": "Caps Lock","D": "Space bar"},"answer": "D"},
{ "question": "Shift and Caps Lock are same","type": "single","options" : {"A": "True","B": "None","C": "Incorrect comparison","D": "FALSE"},"answer": "D"},
{ "question": "This is not the type of keys in the computer","type": "single","options" : {"A": "Number","B": "Alphabets","C": "Cursor keys","D": "Circle keys"},"answer": "D"},
{ "question": "The keyboard is called as _____ keyboard","type": "single","options" : {"A": "ABCDEF","B": "STRING","C": "CHARAC","D": "QWERTY"},"answer": "D"},
{ "question": "Arrow keys are called as ___ keys","type": "single","options" : {"A": "Circle","B": "Special","C": "Number","D": "Cursor"},"answer": "D"},
{ "question": "Cursor is a ___","type": "single","options" : {"A": "sitting line and circle","B": "slanting line","C": "dot and blink","D": "standing line and blink"},"answer": "D"},
{ "question": "Cursor tells the position where ___ character will appear","type": "single","options" : {"A": "Previous","B": "Top","C": "Bottom","D": "Next"},"answer": "D"},
{ "question": "If you type, all letters should be in UPPER case. What should I do?","type": "single","options" : {"A": "Switch UPPER lock","B": "Switch Capital Lock","C": "Switch Num Lock","D": "Switch Caps lock"},"answer": "D"},
{ "question": "Numeric keypad is on the ___ of the keyboard","type": "single","options" : {"A": "Left","B": "Center","C": "Top","D": "Right"},"answer": "D"},
{ "question": "____ enters a space anywhere in the text","type": "single","options" : {"A": "Keybar","B": "Capslock","C": "Emptybar","D": "Spacebar"},"answer": "D"},
{ "question": "I AM LEARNING COMPUTERS: How many times you might have hit space bar?","type": "single","options" : {"A": "2","B": "4","C": "5","D": "3"},"answer": "D"},
{ "question": "Enter key is otherwise called as ___ key","type": "single","options" : {"A": "Big size key","B": "Report key","C": "New line key","D": "Return key"},"answer": "D"},
{ "question": "A, B and C - you need to type in new lines. Which special key you should use?","type": "single","options" : {"A": "Space key","B": "Caps lock","C": "Shift key","D": "Enter key"},"answer": "D"},
{ "question": "FLOWA|R. The cursor is between A & R. You should remove A for spelling correction. Which special key will u use?","type": "single","options" : {"A": "Delete","B": "Enter","C": "Arrow","D": "Backspace"},"answer": "D"},
{ "question": "___ key is used to delete left of the key","type": "single","options" : {"A": "Delete","B": "Enter","C": "Arrow","D": "Backspace"},"answer": "D"},
{ "question": "___ key is used to delete right of the key","type": "single","options" : {"A": "Backspace","B": "Enter","C": "Arrow","D": "Delete"},"answer": "D"},
{ "question": "Many keys have something on the upper portion. To type that, which key you should use?","type": "single","options" : {"A": "Delete","B": "Backspace","C": "Enter","D": "Shift"},"answer": "D"},
{ "question": "Using Shift keys can you type Capital letters","type": "single","options" : {"A": "NO","B": "Only Caps lock","C": "Only Enter key","D": "YES"},"answer": "D"},
{ "question": "Special function keys are at the ___ of the keyboard","type": "single","options" : {"A": "Below","B": "Sideways","C": "On Monitor","D": "Above"},"answer": "D"},
{ "question": "How many function keys are present?","type": "single","options" : {"A": "10","B": "14","C": "8","D": "12"},"answer": "D"},
{ "question": "Which are the additional keys present in Multimedia keys","type": "single","options" : {"A": "Caps lock","B": "Num pad","C": "Function keys","D": "Music control"},"answer": "D"},
{ "question": "DRBOAYEK - this is jumbled. Right one?","type": "single","options" : {"A": "DROPKEY","B": "KREYDORAB","C": "KREYBDOAR","D": "KEYBOARD"},"answer": "D"},
{ "question": "3 Types of mouses are: ","type": "single","options" : {"A": "2-button, 3-button, music","B": "1-button, 2-button, 3-button","C": "1-button, 2-button, multimedia","D": "2-button, 3-button, scroll"},"answer": "D"},
{ "question": "Can I use mouse and go up and down on monitor","type": "single","options" : {"A": "NO","B": "Only when wire is there","C": "Only in Keyboard","D": "YES"},"answer": "D"},
{ "question": "Mouse without a wire is called as ___","type": "single","options" : {"A": "Wireless mouse","B": "No wire mouse","C": "Mouse-o-mouse","D": "Cordless mouse"},"answer": "D"},
{ "question": "Which is not the mouse action?","type": "single","options" : {"A": "Click","B": "Drag","C": "Double-click","D": "Enter"},"answer": "D"},
{ "question": "Click on the mouse is ___","type": "single","options" : {"A": "Smell","B": "Light","C": "Wave","D": "Sound"},"answer": "D"},
{ "question": "Click normally happens on left or right?","type": "single","options" : {"A": "Right","B": "Center","C": "Based on where u keep mouse","D": "Left"},"answer": "D"},
{ "question": "Trash Icon - you double click - what happens","type": "single","options" : {"A": "Trash gets deleted","B": "Computer stops","C": "More trash will come","D": "It opens trash"},"answer": "D"},
{ "question": "Which mouse operation is used for displaying list of commands?","type": "single","options" : {"A": "Click","B": "Double click","C": "Enter","D": "Right click"},"answer": "D"},
{ "question": "When you right click, what appears","type": "single","options" : {"A": "Keyboard light will glow","B": "Caps lock will be ON","C": "Computer will stop","D": "Menu of commands"},"answer": "D"},
{ "question": "To move an object / icon, which mouse operation u use?","type": "single","options" : {"A": "Click","B": "Drag","C": "Double-click","D": "Drag and Drop"},"answer": "D"},
{ "question": "When you are dragging an object, you","type": "single","options" : {"A": "should click and drag","B": "should use the wheel","C": "should Enter and drag","D": "should hold and drag"},"answer": "D"},
{ "question": "You can draw pictures with a mouse","type": "single","options" : {"A": "No","B": "Yes and No","C": "Irrelevant question","D": "Yes"},"answer": "D"},
{ "question": "All computer mouse's will have 3 buttons","type": "single","options" : {"A": "Yes ","B": "Yes and No","C": "Irrelevant question","D": "No"},"answer": "D"},
{ "question": "Which area the computer is not used?","type": "single","options" : {"A": "Education","B": "Railway stations","C": "Banks","D": "Making food"},"answer": "D"},
{ "question": "Which area the comupter is used?","type": "single","options" : {"A": "Heating water","B": "Making food","C": "Making kid sleep","D": "Banks"},"answer": "D"},
{ "question": "Computers are used to make cartoon movies - Example for","type": "single","options" : {"A": "Education","B": "Movie","C": "Banks","D": "Entertainment"},"answer": "D"},
{ "question": "Which of the following is Entertainment industry example of using compute","type": "single","options" : {"A": "Cash Transfer","B": "Finding fever","C": "Learning videos","D": "Listening to music"},"answer": "D"},
{ "question": "Student records in school is kept properly. This work of computer is example of ","type": "single","options" : {"A": "Entertainment","B": "Banks","C": "Railways","D": "Education"},"answer": "D"},
{ "question": "Which is an education example for computer usage?","type": "single","options" : {"A": "Students can know fever","B": "Teachers can talk","C": "Listen music","D": "Students can complete homework"},"answer": "D"},
{ "question": "How much money is your father keeping in bank. Computer helps - An example used in:","type": "single","options" : {"A": "Hospital","B": "Education","C": "Entertainment","D": "Banking"},"answer": "D"},
{ "question": "I want to go in flight from Bangalore to London. Computers help in getting tickets. Example of?","type": "single","options" : {"A": "Railways","B": "Hospitals","C": "Banking","D": "Airports"},"answer": "D"},
{ "question": "Do I have seat in the train I wanted to go Chennai. Computer helps - This is example of","type": "single","options" : {"A": "Airports","B": "Entertainment","C": "Education","D": "Railways"},"answer": "D"},
{ "question": "1 year before I went in train from Bangalore to Chennai. Will computer remember?","type": "single","options" : {"A": "No","B": "It will forget after 7 days","C": "If power goes, it will forget","D": "Yes"},"answer": "D"},
{ "question": "I am having fever and going to hospital. What fever is that? Can doctor use computer and find it?","type": "single","options" : {"A": "No","B": "Only with white computer","C": "Doctor is not needed at all","D": "Yes"},"answer": "D"},
{ "question": "Send and Receive mails using computer. This is computer usage example in __","type": "single","options" : {"A": "Entertainment","B": "Education","C": "Banking","D": "Office"},"answer": "D"},
{ "question": "How is computer used for Army people?","type": "single","options" : {"A": "To put bombs (missile) on criminals","B": "To find where criminals are","C": "To decide where more army is needed","D": "All the above"},"answer": "D"},
{ "question": "Such a big news paper. Can I use computer to design","type": "single","options" : {"A": "No","B": "Buy big size computer","C": "Only in Laptop","D": "Yes"},"answer": "D"},
{ "question": "I want to build house with 3 floors. Can I use computer","type": "single","options" : {"A": "No","B": "Every floor needs computer","C": "Only on paper","D": "Yes"},"answer": "D"},
{ "question": "Computers are of no use in schools","type": "single","options" : {"A": "True","B": "Only for colleges","C": "Only for Army schools","D": "FALSE"},"answer": "D"},
{ "question": "Computers in Banks are used to play games","type": "single","options" : {"A": "True","B": "Only for colleges","C": "Only for Army schools","D": "FALSE"},"answer": "D"},


]