qbHindi = [

{ "question": "Greetings means?","type": "single","options" : {"A": "नकार","B": "नया","C": "जी","D": "नमस्कार"},"answer": "D"},
{ "question": "पढ़ means?","type": "single","options" : {"A": "Dance","B": "Write","C": "Come","D": "Read"},"answer": "D"},
{ "question": "Vowel in Hindi means?","type": "single","options" : {"A": "सरि","B": "वचन","C": "वंदन","D": "स्वर"},"answer": "D"},
{ "question": "पेड़ पर चढ़ें means","type": "single","options" : {"A": "Read loudly","B": "Sleep fast","C": "Eat fast","D": "Climb tree"},"answer": "D"},
{ "question": "Fill blank: अ _ र ","type": "single","options" : {"A": "र ","B": "अनार","C": "सु","D": "ना"},"answer": "D"},
{ "question": "Fill blank: अं गू  _ ","type": "single","options" : {"A": "अं","B": "गू","C": "सु","D": "र"},"answer": "D"},
{ "question": "Fill blank: _ त री ","type": "single","options" : {"A": "अं","B": "गू","C": "त","D": "छ"},"answer": "D"},
{ "question": "Fill blank: ड म _","type": "single","options" : {"A": "ड","B": "गू","C": "म","D": "रू "},"answer": "D"},
{ "question": "Fill blank: त _ _ ज ","type": "single","options" : {"A": "ड","B": "र","C": "बू","D": "रबू"},"answer": "D"},
{ "question": "Fill blank: प _ ग ","type": "single","options" : {"A": "प","B": "त","C": "गू","D": "तं"},"answer": "D"},
{ "question": "Fill blank: ल _","type": "single","options" : {"A": "तू","B": "बू ","C": "दू ","D": "ट्टू"},"answer": "D"},
{ "question": "Fill blank: ष ट _ ण ","type": "single","options" : {"A": "जो","B": "गो ","C": "खो","D": "को"},"answer": "D"},
{ "question": "Fill blank: ह __ ड़ा ","type": "single","options" : {"A": "बा","B": "दौ","C": "गौ ","D": "थौ"},"answer": "D"},
{ "question": "Fill blank: _ ग","type": "single","options" : {"A": "बा","B": "झा ","C": "ग","D": "ज "},"answer": "D"},
{ "question": "Fill blank: ब _","type": "single","options" : {"A": "सा","B": "श","C": "द","D": "स"},"answer": "D"},
{ "question": "Fill blank: _ ल","type": "single","options" : {"A": "ण ","B": "द","C": "प","D": "न"},"answer": "D"},
{ "question": "Fill blank: ह __","type": "single","options" : {"A": "ला","B": "ल ","C": "ता","D": "ल"},"answer": "D"},
{ "question": "Fill blank: म _ र ","type": "single","options" : {"A": "ख","B": "ज","C": "क","D": "ग"},"answer": "D"},
{ "question": "Fill blank: क ल _","type": "single","options" : {"A": "स ","B": "रा ","C": "ड","D": "श"},"answer": "D"},
{ "question": "Fill blank: ब _ क ","type": "single","options" : {"A": "त ","B": "न ","C": "क","D": "त"},"answer": "D"},
{ "question": "Fill blank: _ वन","type": "single","options" : {"A": "बा ","B": "न ","C": "ड","D": "भ"},"answer": "D"},
{ "question": "Fill blank: थ _ मस","type": "single","options" : {"A": "बा ","B": "न ","C": "ड","D": "र"},"answer": "D"},
{ "question": "Fill blank: बर _ द","type": "single","options" : {"A": "त ","B": "न ","C": "क","D": "ग"},"answer": "D"},
{ "question": "Fill blank: अच _ न","type": "single","options" : {"A": "त ","B": "न ","C": "ड","D": "क"},"answer": "D"},
{ "question": "Fill blank: खट _ ल","type": "single","options" : {"A": "त ","B": "न ","C": "ड","D": "म"},"answer": "D"},
{ "question": "थरमस मतलब:","type": "single","options" : {"A": "glass","B": "tumbler","C": "paste","D": "thermas"},"answer": "D"},
{ "question": "बरगद मतलब:","type": "single","options" : {"A": "mango tree","B": "guava tree","C": "apple tree","D": "banyan tree"},"answer": "D"},
{ "question": "अचकन मतलब:","type": "single","options" : {"A": "shirt","B": "pant","C": "baniyan","D": "long coat"},"answer": "D"},
{ "question": "खटमल मतलब:","type": "single","options" : {"A": "cockroach","B": "insect","C": "ant","D": "bed bug"},"answer": "D"},
{ "question": "बच्चा मतलब:","type": "single","options" : {"A": "bag","B": "ball","C": "bud","D": "child"},"answer": "D"},
{ "question": "दुकान मतलब:","type": "single","options" : {"A": "pond","B": "park","C": "house","D": "shop"},"answer": "D"},
{ "question": "गुब्बारे मतलब:","type": "single","options" : {"A": "vessel","B": "flowers","C": "pots","D": "balloons"},"answer": "D"},
{ "question": "टमाटर मतलब:","type": "single","options" : {"A": "vegetable","B": "red fruit","C": "apple","D": "tomato"},"answer": "D"},
{ "question": "खिलौने मतलब:","type": "single","options" : {"A": "paste","B": "phone","C": "doll","D": "toys"},"answer": "D"},
{ "question": "बल्ला मतलब:","type": "single","options" : {"A": "stick","B": "stump","C": "ball","D": "bat"},"answer": "D"},
{ "question": "मछली मतलब:","type": "single","options" : {"A": "alligator","B": "frog","C": "insect","D": "fish"},"answer": "D"},
{ "question": "शैला मतलब:","type": "single","options" : {"A": "frog","B": "vessel","C": "basket","D": "bag"},"answer": "D"},
{ "question": "गाडी मतलब:","type": "single","options" : {"A": "laptop","B": "phone","C": "tree","D": "vehicle"},"answer": "D"},
{ "question": "सब्जियां मतलब:","type": "single","options" : {"A": "beans","B": "carrot","C": "apple","D": "vegetables"},"answer": "D"},
{ "question": "शरबत मतलब:","type": "single","options" : {"A": "milk","B": "water","C": "honey","D": "juice"},"answer": "D"},
{ "question": "सरकस मतलब:","type": "single","options" : {"A": "park","B": "temple","C": "shop","D": "circus"},"answer": "D"},
{ "question": "बरतन  मतलब:","type": "single","options" : {"A": "spoon","B": "plate","C": "comb","D": "vessels"},"answer": "D"},
{ "question": "अदरक मतलब:","type": "single","options" : {"A": "carrot","B": "beans","C": "garlic","D": "ginger"},"answer": "D"},
{ "question": "पहचान &gt;&gt;&gt;hin_ginger","type": "single","options" : {"A": "सब्जियां","B": "टमाटर ","C": "बरगद","D": "अदरक"},"answer": "D"},
{ "question": "पहचान &gt;&gt;&gt;hin_veg","type": "single","options" : {"A": "बरगद","B": "मछली ","C": "टमाटर ","D": "सब्जियां"},"answer": "D"},
{ "question": "पहचान &gt;&gt;&gt;hin_tomato","type": "single","options" : {"A": "बरगद","B": "मछली ","C": "सब्जियां","D": "टमाटर "},"answer": "D"},
{ "question": "पहचान &gt;&gt;&gt;hin_banyan","type": "single","options" : {"A": "टमाटर ","B": "मछली ","C": "सब्जियां","D": "बरगद"},"answer": "D"},
{ "question": "पहचान &gt;&gt;&gt;hin_fish","type": "single","options" : {"A": "सब्जियां","B": "टमाटर ","C": "बरगद","D": "मछली "},"answer": "D"},
{ "question": "बस कर ","type": "single","options" : {"A": "run fast","B": "don’t do","C": "just quiet","D": "just do"},"answer": "D"},
{ "question": "अब बस कर ","type": "single","options" : {"A": "do fast","B": "do later","C": "just don’t do it","D": "just do it now"},"answer": "D"},
{ "question": "छत पर मत चढ़","type": "single","options" : {"A": "don’t run fast","B": "don’t walk fast","C": "don’t jump fast","D": "don’t climb on roof"},"answer": "D"},
{ "question": "अब लड़ मत ","type": "single","options" : {"A": "fight now","B": "don’t jump","C": "jump now","D": "don’t fight now"},"answer": "D"},
{ "question": "घर चल ","type": "single","options" : {"A": "bath home","B": "walk home","C": "sleep home","D": "come home"},"answer": "D"},
{ "question": "पदों और समझो ","type": "single","options" : {"A": "write 2 times","B": "read 2 times","C": "understand and read","D": "read and understand"},"answer": "D"},
{ "question": "रजत बरगद  पर मत चढ़ ","type": "single","options" : {"A": "cut banyan tree","B": "climb banyan","C": "jump out of banyan","D": "do not climb on the silver banyan"},"answer": "D"},
{ "question": "उपवन तक चल ","type": "single","options" : {"A": "fly to park","B": "cycle to park","C": "run to park","D": "walk up to the park"},"answer": "D"},
{ "question": "शलगम और परवल रख ","type": "single","options" : {"A": "don’t keep vegetable","B": "keep turnip","C": "keep parwal","D": "Turnip and parwal keep"},"answer": "D"},
{ "question": "रमन इधर उधर मत टहल","type": "single","options" : {"A": "don’t run here and there","B": "don’t sit here and there","C": "sit silently","D": "raman don’t move here and there"},"answer": "D"},
{ "question": "झगड़ मत ","type": "single","options" : {"A": "don’t run now","B": "fight now","C": "don’t fight now","D": "don’t fight"},"answer": "D"},
{ "question": "अमर सड़क पर मत टहल ","type": "single","options" : {"A": "walk on road properly","B": "don’t sleep on road","C": "don’t walk now","D": "amar, don’t walk on road"},"answer": "D"},
{ "question": "अगर-मगर मत कर ","type": "single","options" : {"A": "sit nothing","B": "do anything","C": "do something","D": "don’t do anything"},"answer": "D"},
{ "question": "अमर कमल पकड़ ","type": "single","options" : {"A": "hold flower","B": "hold lotus","C": "amar lotus","D": "amar, hold flower"},"answer": "D"},
{ "question": "गरम गरम मटर चख","type": "single","options" : {"A": "taste hot jamoon","B": "taste hot hot soup","C": "hot hot milk","D": "hot hot peas taste"},"answer": "D"},
{ "question": "रजत बरगद पर मत चढ़ ","type": "single","options" : {"A": "climb tomato tree","B": "don’t climb tomato tree","C": "climb banyan tree","D": "rajat, don’t climb banyan tree"},"answer": "D"},

]