qbKannada = [

{ "question": "ಏರುತಿಹುದು ಹಾರುತಿಹುದು ನೋಡು ನಮ್ಮ ______","type": "single","options" : {"A": "ಧ್ವಜ","B": "ಬಾಟನಿ","C": "ವಂದನೆ","D": "ಬಾವುಟ"},"answer": "D"},
{ "question": "ತೋರುತಿಹುದು ____ ಹೊಡೆದು","type": "single","options" : {"A": "ಬಾಟನಿ","B": "ವಂದನೆ","C": "ಬಾವುಟ","D": "ಹೊಡೆದು"},"answer": "D"},
{ "question": "ಬಾನಿನಗಲ _______","type": "single","options" : {"A": "ಬಾವುಟ","B": "ವಂದನೆ","C": "ಪಟ","D": "ಪಟಪಟ"},"answer": "D"},
{ "question": "ಕೇಸರಿ ಬಿಳಿ ____ ಮೂರು","type": "single","options" : {"A": "ಧ್ವಜ","B": "ಬಾಟನಿ","C": "ಪಟ","D": "ಹಸಿರು"},"answer": "D"},
{ "question": "ಚರಕವು means","type": "single","options" : {"A": "Blue","B": "Color","C": "Flag","D": "Wheel"},"answer": "D"},
{ "question": "____ ಹಿಡಿದ ಚರಕವು","type": "single","options" : {"A": "ಧ್ವಜ","B": "ಬಾವುಟ","C": "Flag","D": "ಗಾಂಧಿ"},"answer": "D"},
{ "question": "ಇಂತ ಧ್ವಜವು ನಮ್ಮ ____","type": "single","options" : {"A": "ಬಾಟನಿ","B": "ಬಾವುಟ","C": "ಗಾಂಧಿ","D": "ಧ್ವಜವು"},"answer": "D"},
{ "question": "ಕೆಂಪು ಕಿರಣ ತುಂಬಿ ಗಗನ. 'ಕೆಂಪು ' means","type": "single","options" : {"A": "blue","B": "sky","C": "green","D": "red"},"answer": "D"},
{ "question": "ಕೇಸರಿ means in English?","type": "single","options" : {"A": "Sweet","B": "Rangoli","C": "Paint","D": "Saffron"},"answer": "D"},
{ "question": "Namma Baavuta poem is written by","type": "single","options" : {"A": "Rabindranath Tagore","B": "Nehru","C": "Rajkumar","D": "Kayyara Kinhanna Rai"},"answer": "D"},
{ "question": "Vowel in Kannada means?","type": "single","options" : {"A": "ವ್ಯಂಜನ","B": "ಬಾವುಟ","C": "ಧ್ವಜ","D": "ಸ್ವರ"},"answer": "D"},
{ "question": "Fill blank: ಗ ರ ಗ _ ","type": "single","options" : {"A": "ಗ","B": "ರ","C": "ಡಿ","D": "ಸ"},"answer": "D"},
{ "question": "Fill blank: ದ _ ರ","type": "single","options" : {"A": "ಗ","B": "ರ","C": "ಡಿ","D": "ಸ"},"answer": "D"},
{ "question": "Fill blank: _ ರ ಸ","type": "single","options" : {"A": "ಗ","B": "ರ","C": "ಸ","D": "ಅ"},"answer": "D"},
{ "question": "ಇದು ಏನು &gt;&gt;&gt;kan_dasara","type": "single","options" : {"A": "ಗರಗಸ ","B": "ಸರ","C": "ರಸ","D": "ದಸರಾ"},"answer": "D"},
{ "question": "ಇದು ಏನು &gt;&gt;&gt;kan_king","type": "single","options" : {"A": "ಗರಗಸ ","B": "ಸರ","C": "ದಸರಾ","D": "ಅರಸ"},"answer": "D"},
{ "question": "ಕನ್ನಡದಲ್ಲಿ ಹೇಳಿ : Chain","type": "single","options" : {"A": "ಗರಗಸ ","B": "ಅರಸ","C": "ದಸರಾ","D": "ಸರ"},"answer": "D"},
{ "question": "ಇದು ಏನು &gt;&gt;&gt;kan_snak","type": "single","options" : {"A": "ಉರಗ","B": "ಅರಸ","C": "ದಸರಾ","D": "ಹಾವು"},"answer": "D"},
{ "question": "ಇದು ಏನು &gt;&gt;&gt;kan_reptile","type": "single","options" : {"A": "ಅರಸ","B": "ದಾಸರ","C": "ಹಾವು","D": "ಉರಗ"},"answer": "D"},
{ "question": "Fill blank: _ ರ ಗ","type": "single","options" : {"A": "ರ","B": "ಗ","C": "ಹಾ","D": "ಉ"},"answer": "D"},
{ "question": "Fill blank: ಜ _ ","type": "single","options" : {"A": "ರ","B": "ಗ","C": "ಹಾ","D": "ನ"},"answer": "D"},
{ "question": "Fill blank: ನ _ ರ ","type": "single","options" : {"A": "ರ","B": "ಸ","C": "ಹಾ","D": "ಗ"},"answer": "D"},
{ "question": "ಇದು ಏನು \n &gt;&gt;&gt;kan_tree","type": "single","options" : {"A": "ಗರಗಸ ","B": "ಅರಸ","C": "ದಸರಾ","D": "ಮರ"},"answer": "D"},
{ "question": "ಕನ್ನಡದಲ್ಲಿ ಹೇಳಿ : Forest","type": "single","options" : {"A": "ಗರಗಸ ","B": "ಅರಸ","C": "ದಸರಾ","D": "ಬನ"},"answer": "D"},
{ "question": "ಕನ್ನಡದಲ್ಲಿ ಹೇಳಿ : Tree","type": "single","options" : {"A": "ದಸರಾ","B": "ನಗರ ","C": "ಜನ","D": "ಮರ"},"answer": "D"},
{ "question": "ಕನ್ನಡದಲ್ಲಿ ಹೇಳಿ : City","type": "single","options" : {"A": "ದಸರಾ","B": "ಮರ","C": "ಜನ","D": "ನಗರ "},"answer": "D"},
{ "question": "ಕನ್ನಡದಲ್ಲಿ ಹೇಳಿ : People","type": "single","options" : {"A": "ದಸರಾ","B": "ಮರ","C": "ಮರ","D": "ಜನ"},"answer": "D"},
{ "question": "Fill blank: ಗ _","type": "single","options" : {"A": "ಮ","B": "ಗ","C": "ಪ","D": "ಜ"},"answer": "D"},
{ "question": "Fill blank: ಗ _ ನ","type": "single","options" : {"A": "ತ","B": "ಮ","C": "ರ ","D": "ಗ"},"answer": "D"},
{ "question": "ಗಗನ' ಅಂದರೆ","type": "single","options" : {"A": "forest","B": "tree","C": "king","D": "sky"},"answer": "D"},
{ "question": "ಸಮ' ಅಂದರೆ","type": "single","options" : {"A": "tree","B": "king","C": "garden","D": "equal"},"answer": "D"},
{ "question": "ನಗರ' ಅಂದರೆ","type": "single","options" : {"A": "tree","B": "king","C": "garden","D": "city"},"answer": "D"},
{ "question": "ಪಟ' ಅಂದರೆ","type": "single","options" : {"A": "tree","B": "king","C": "garden","D": "kite"},"answer": "D"},
{ "question": "ನಯನ' ಅಂದರೆ","type": "single","options" : {"A": "smile","B": "tree","C": "king","D": "eye"},"answer": "D"},
{ "question": "ವನ' ಅಂದರೆ","type": "single","options" : {"A": "tree","B": "king","C": "garden","D": "forest"},"answer": "D"},
{ "question": "ಚಮಚ' ಅಂದರೆ","type": "single","options" : {"A": "iron","B": "rod","C": "pen","D": "spoon"},"answer": "D"},
{ "question": "ಇದು ಏನು &gt;&gt;&gt;kan_eye","type": "single","options" : {"A": "ಚಮಚ","B": "ಮರ","C": "ದಸರಾ","D": "ನಯನ"},"answer": "D"},
{ "question": "ಇದು ಏನು &gt;&gt;&gt;kan_spoon","type": "single","options" : {"A": "ನಯನ","B": "ಚಮಚ","C": "ಮರ","D": "ಚಮಚ"},"answer": "D"},
{ "question": "ಕನ್ನಡದಲ್ಲಿ ಹೇಳಿ : Kite","type": "single","options" : {"A": "ನಯನ","B": "ಚಮಚ","C": "ಮರ","D": "ಪಟ"},"answer": "D"},
{ "question": "ಕನ್ನಡದಲ್ಲಿ ಹೇಳಿ : Eye","type": "single","options" : {"A": "ನಯನ","B": "ಚಮಚ","C": "ಪಟ","D": "ನಯನ"},"answer": "D"},
{ "question": "ಕನ್ನಡದಲ್ಲಿ ಹೇಳಿ : Forest","type": "single","options" : {"A": "ನಯನ","B": "ಚಮಚ","C": "ಪಟ","D": "ವನ"},"answer": "D"},
{ "question": "ಕನ್ನಡದಲ್ಲಿ ಹೇಳಿ : Spoon","type": "single","options" : {"A": "ಪಟ","B": "ನಯನ","C": "ವನ","D": "ಚಮಚ"},"answer": "D"},
{ "question": "Fill blank: ಚ ಮ _","type": "single","options" : {"A": "ಮ","B": "ನ","C": "ಯ","D": "ಚ"},"answer": "D"},
{ "question": "Fill blank: _ ಯ ನ","type": "single","options" : {"A": "ಯ","B": "ವ","C": "ರ","D": "ನ"},"answer": "D"},
{ "question": "ವಚನ' ಅಂದರೆ","type": "single","options" : {"A": "sky","B": "fight","C": "argue","D": "promise"},"answer": "D"},
{ "question": "ನಯನ' ಅಂದರೆ","type": "single","options" : {"A": "promise","B": "argue","C": "sky","D": "eye"},"answer": "D"},
{ "question": "ಉದಯ' ಅಂದರೆ","type": "single","options" : {"A": "name","B": "sky","C": "water","D": "sun rise"},"answer": "D"},

]