qbLiterature = [

{ "question": "Fill the blank: _____ FOX","type": "single","options" : {"A": "Wonderful","B": "Ferocious","C": "Whom","D": "Fantastic"},"answer": "D"},
{ "question": "Fill the blank: Apple ____","type": "single","options" : {"A": "Juice","B": "Strange","C": "Water","D": "Cider"},"answer": "D"},
{ "question": "Author of Fantastic Mr. Fox","type": "single","options" : {"A": "Ronald Regan","B": "Donald Trump","C": "Modi","D": "Roald Dahl"},"answer": "D"},
{ "question": "How many farmers were there in story","type": "single","options" : {"A": "None","B": "One","C": "Two","D": "Three"},"answer": "D"},
{ "question": "Which is not the farmer name","type": "single","options" : {"A": "Boggis","B": "Bunce","C": "Bean","D": "Boston"},"answer": "D"},
{ "question": "Who is the chicken farmer?","type": "single","options" : {"A": "Boston","B": "Bunce","C": "Bean","D": "Boggis"},"answer": "D"},
{ "question": "Boggis was quite ____","type": "single","options" : {"A": "thin","B": "tall","C": "short","D": "fat"},"answer": "D"},
{ "question": "Bunce was _______ farmer","type": "single","options" : {"A": "Cabbage","B": "Chicken","C": "Duck","D": "Duck & Goose"},"answer": "D"},
{ "question": "Which farmer was too short?","type": "single","options" : {"A": "Boggis","B": "Boston","C": "Bean","D": "Bunce"},"answer": "D"},
{ "question": "Which farmer made one disgusting paste to eat?","type": "single","options" : {"A": "Boggis","B": "Boston","C": "Bean","D": "Bunce"},"answer": "D"},
{ "question": "Which farmer was cleverst of all?","type": "single","options" : {"A": "Boggis","B": "Boston","C": "Bunce","D": "Bean"},"answer": "D"},
{ "question": "Bean never had food at all and only gallons of ______","type": "single","options" : {"A": "Water","B": "Apple","C": "Sapota juice","D": "Cider"},"answer": "D"},
{ "question": "All 3 farmers were mean and ___","type": "single","options" : {"A": "waste","B": "tall","C": "hasty","D": "nasty"},"answer": "D"},
{ "question": "All 3 farmers were nasty and ___","type": "single","options" : {"A": "hasty","B": "tall","C": "short","D": "mean"},"answer": "D"},
{ "question": "Boggis was keeping ___ of chickens","type": "single","options" : {"A": "hundreds","B": "hens","C": "tens","D": "thousands"},"answer": "D"},
{ "question": "How many chickens Boggies eats for Lunch?","type": "single","options" : {"A": "4","B": "2","C": "1","D": "3"},"answer": "D"},
{ "question": "How many chickens Boggies eats for Dinner?","type": "single","options" : {"A": "4","B": "2","C": "1","D": "3"},"answer": "D"},
{ "question": "Bunce was goose and ___ farmer","type": "single","options" : {"A": "hen","B": "cock","C": "truck","D": "duck"},"answer": "D"},
{ "question": "Who was pot bellied among farmers","type": "single","options" : {"A": "Boggis","B": "Boston","C": "Bean","D": "Bunce"},"answer": "D"},
{ "question": "Who was dwarf amongst farmers","type": "single","options" : {"A": "Boggis","B": "Boston","C": "Bean","D": "Bunce"},"answer": "D"},
{ "question": "Is Bunce short or tall farmer","type": "single","options" : {"A": "tall","B": "fat","C": "lean","D": "short"},"answer": "D"},
{ "question": "Bunce and Boggis are ___","type": "single","options" : {"A": "Police","B": "Teachers","C": "Workers","D": "Farmers"},"answer": "D"},
{ "question": "Bunce food is ____ and goose livers","type": "single","options" : {"A": "chicken","B": "paste","C": "pasta","D": "doughnuts"},"answer": "D"},
{ "question": "Bunce used to ___ the livers","type": "single","options" : {"A": "smash","B": "squeeze","C": "mix","D": "mash"},"answer": "D"},
{ "question": "Bunce mashes ___ and makes into a paste","type": "single","options" : {"A": "goose","B": "duck","C": "stomach","D": "livers"},"answer": "D"},
{ "question": "Eating so many livers making into a paste makes Bunce ___","type": "single","options" : {"A": "soft guy","B": "cool man","C": "laughing man","D": "temper man"},"answer": "D"},
{ "question": "By eating paste with doghnuts, Bunce gets his tummy __","type": "single","options" : {"A": "look so good","B": "healthy","C": "tummy strong","D": "tummy ache"},"answer": "D"},
{ "question": "Bean was a turkey and ___ farmer","type": "single","options" : {"A": "chicken","B": "goose","C": "doughnut","D": "apple"},"answer": "D"},
{ "question": "Bean was an apple and ___ farmer","type": "single","options" : {"A": "goose","B": "apple","C": "chicken","D": "turkey"},"answer": "D"},
{ "question": "Bean's Turkey is a ___","type": "single","options" : {"A": "animal","B": "insect","C": "food","D": "bird"},"answer": "D"},
{ "question": "Bean kept all his Turkeys in a ___","type": "single","options" : {"A": "house","B": "box","C": "nest","D": "orchard"},"answer": "D"},
{ "question": "A piece of land where many trees are grown is __","type": "single","options" : {"A": "park","B": "hill","C": "garden","D": "orchard"},"answer": "D"},
{ "question": "Orchard means ___","type": "single","options" : {"A": "bird park","B": "animal park ","C": "garden ","D": "trees in cluster"},"answer": "D"},
{ "question": "Bean was clever because ___","type": "single","options" : {"A": "he was thin","B": "he ate turkeys","C": "he drank turkey juice","D": "he drank apple cider"},"answer": "D"},
{ "question": "Cider means ___","type": "single","options" : {"A": "squash apple juice","B": "apple pieces","C": "juice of turkey","D": "make apple ferment and juice"},"answer": "D"},
{ "question": "Select the incorrect relation ","type": "single","options" : {"A": "Bean Cider","B": "Bunce livers","C": "Boggis Chicken","D": "Bean Liver"},"answer": "D"},
{ "question": "All the farmers are crooks. Crooks means ___","type": "single","options" : {"A": "a bad word","B": "a good word","C": "shabby person","D": "dishonest person"},"answer": "D"},
{ "question": "Bean drank ___ of cider from fermented apples","type": "single","options" : {"A": "kilos","B": "milli litre","C": "litres","D": "gallons"},"answer": "D"},
{ "question": "Select the correct relation ","type": "single","options" : {"A": "Bunce Clever","B": "Boggis Tummy ache","C": "Bean Chicken","D": "Bean Lean"},"answer": "D"},
{ "question": "Where was the wood?","type": "single","options" : {"A": "On Valley","B": "Below Valley","C": "Below Hill","D": "On hill"},"answer": "D"},
{ "question": "There was a wood above hill. 'Wood' means?","type": "single","options" : {"A": "Kattai","B": "Tree","C": "Furniture","D": "Forest"},"answer": "D"},
{ "question": "Where were foxes living? Choose more right answer","type": "single","options" : {"A": "In the woods","B": "In the tree","C": "In the hole above tree","D": "In the hole under tree"},"answer": "D"},
{ "question": "How many small foxes were there for Mr/Mrs. Fix","type": "single","options" : {"A": "1","B": "2","C": "3","D": "4"},"answer": "D"},
{ "question": "When does Mr. fox say to Mrs. fox for eating?","type": "single","options" : {"A": "Morning","B": "Night","C": "Afternoon","D": "Evening"},"answer": "D"},
{ "question": "Do you need plump chicken from Boggis? - Who says this?","type": "single","options" : {"A": "Mrs. Fox says to Mr. fox","B": "Fox to Mr. Boggis","C": "Mr. Boggis to Fox","D": "Mr. Fox says to Mrs. fox"},"answer": "D"},
{ "question": "After Mrs fox tells what she wants Mr. Fox ___","type": "single","options" : {"A": "will say no","B": "will sleep in the valley","C": "will go morning to attack Boggis","D": "will creep down into valley"},"answer": "D"},
{ "question": "Mr. Fox will creep down into the valley - What does 'creep' mean?","type": "single","options" : {"A": "Run quietly","B": "Walk with fire","C": "Take gun with you","D": "Move quietly carefully"},"answer": "D"},
{ "question": "Do the farmers know Mr Fox is going to come and steal?","type": "single","options" : {"A": "No","B": "Only Bean knows","C": "Only Boggis knew","D": "Yes"},"answer": "D"},
{ "question": "Who was so generous to give away freely to fox?","type": "single","options" : {"A": "Boggis","B": "Bean","C": "Boggis and Bunce","D": "None"},"answer": "D"},
{ "question": "If all farmers know, who is coming to steal, what do they do?","type": "single","options" : {"A": "Leave it","B": "Put net and catch fox","C": "Put fire and catch fox","D": "Shoot and catch fox"},"answer": "D"},
{ "question": "Were the farmers able to shoot the fox which came to steal?","type": "single","options" : {"A": "Yes","B": "Its tail","C": "Its Nose","D": "No"},"answer": "D"},
{ "question": "Did Fox escape when it approached the farm?","type": "single","options" : {"A": "No","B": "Half escape - tail gone","C": "It never came","D": "Yes"},"answer": "D"},
{ "question": "If fox escapes, how did it escape?","type": "single","options" : {"A": "By shooting farmer","B": "By putting fire on farmer","C": "By hearing sound","D": "By smelling in wind"},"answer": "D"},
{ "question": "When fox knew Boggis was hiding at House No.1, …","type": "single","options" : {"A": "it escaped","B": "It went to house 2","C": "It went tired","D": "It went to House 4"},"answer": "D"},
{ "question": "[Dang and blast that lousy beast!]  What does lousy mean?","type": "single","options" : {"A": "loose pant","B": "loose","C": "very unclean","D": "very bad"},"answer": "D"},
{ "question": "[Dang and blast that lousy beast!]  What does Dang mean?","type": "single","options" : {"A": "express happiness","B": "express love","C": "express sad","D": "express anger"},"answer": "D"},
{ "question": "[I'd like to rip his guts out]. Who said?","type": "single","options" : {"A": "Boggis","B": "Bean","C": "Brunce","D": "Bunce"},"answer": "D"},
{ "question": "[He must be killed.] Who said?","type": "single","options" : {"A": "Boggis","B": "Bunce","C": "Brunce","D": "Bean"},"answer": "D"},
{ "question": "[He must be killed.] Who should be killed?","type": "single","options" : {"A": "Boggis","B": "Bunce","C": "Bean","D": "Fox"},"answer": "D"},
{ "question": "Boggis said 'How on earth can we catch the blighter?' Blighter means?","type": "single","options" : {"A": "Person with cunning","B": "Person with clever","C": "Person too soft","D": "Person with Irritation"},"answer": "D"},
{ "question": "'I have a plan' Who said this?","type": "single","options" : {"A": "Boggis","B": "Bunce","C": "Fox","D": "Bean"},"answer": "D"},
{ "question": "Did the farmers shoot the fox when it came near farm?","type": "single","options" : {"A": "Yes","B": "Only tail","C": "Only nose","D": "No"},"answer": "D"},
{ "question": "What was the idea Bean gave?","type": "single","options" : {"A": "Lets put bomb on fox","B": "Lets put stones on fox","C": "Let us not disturb fox","D": "Lets go near tree and kill"},"answer": "D"},
{ "question": "But first, we should find the hole? Which hole?","type": "single","options" : {"A": "Wherever turkey lives","B": "wherever goose lives","C": "hold next to tree","D": "wherever fox lives"},"answer": "D"},
{ "question": "I know where the hole is - Up in the wood on the hill. Who said?","type": "single","options" : {"A": "Boggis","B": "Bunce","C": "Fox","D": "Bean"},"answer": "D"},
{ "question": "Did Boggis give the idea of going to hole and shoot?","type": "single","options" : {"A": "No","B": "Yes, Boggis","C": "No, Bunce","D": "Bean gave idea"},"answer": "D"},
{ "question": "Mrs. Fox said she will have ___ tonight","type": "single","options" : {"A": "Apple cider","B": "Fox","C": "Goose & Duck","D": "Duck"},"answer": "D"},
{ "question": "Which farmer has the ducks to bring?","type": "single","options" : {"A": "Boggis","B": "Bean","C": "Fox","D": "Bunce"},"answer": "D"},
{ "question": "Was Mr. Fox confident and farmers wont find him?","type": "single","options" : {"A": "No, it was nervous","B": "Mrs. fox went","C": "Mr. Fox cried","D": "Yes, it was"},"answer": "D"},
{ "question": "Which farmer has this smell?  The fumes of cider around him like poisonous gases!","type": "single","options" : {"A": "Boggis","B": "Bunce","C": "Fox","D": "Bean"},"answer": "D"},
{ "question": "Which farmer has this smell?  Filthy rotten chicken stink.","type": "single","options" : {"A": "Bunce","B": "Bean","C": "Fox","D": "Boggis"},"answer": "D"},
{ "question": "Where were the farmers when Mr.Fox trying to step outside?","type": "single","options" : {"A": "In farm","B": "On tree","C": "With Guns","D": "Outside hole entrance"},"answer": "D"},
{ "question": "Farmers were 'Crouching' behind a tree with gun loaded. What does 'Crouching' mean?","type": "single","options" : {"A": "Keep body stiff","B": "Keep legs stiff","C": "Sleep on the ground","D": "Bend legs and body close to ground"},"answer": "D"},
{ "question": "Farmers were 'Crouching' behind a tree with gun loaded. Gun loaded means?","type": "single","options" : {"A": "Gun tied to stone","B": "Gun with fire","C": "Gun with trigger","D": "Gun with bullets"},"answer": "D"},
{ "question": "Mr. Fox was able to 'smell' the farmer?","type": "single","options" : {"A": "Yes","B": "No","C": "No because nose was paining","D": "No because wind in opposite direction"},"answer": "D"},
{ "question": "Which is the first part of fox came out of tunnel while coming out","type": "single","options" : {"A": "Eyes","B": "Tail","C": "Legs","D": "Nose"},"answer": "D"},
{ "question": "Did the fox 'sniff' while coming out of tunnel?","type": "single","options" : {"A": "No","B": "It spit","C": "It roared","D": "Yes"},"answer": "D"},
{ "question": "Did the fox sniff once while coming out of tunnel?","type": "single","options" : {"A": "Yes","B": "100 times","C": "For every finger once","D": "For every inch forward"},"answer": "D"},
{ "question": "Why was Mr. Fox careful when coming out of tunnel?","type": "single","options" : {"A": "Because Lion was outside","B": "Because it know mouse will run away","C": "Because it was raining","D": "Because something wrong can happen"},"answer": "D"},
{ "question": "When Mr. Fox came out was there any noise","type": "single","options" : {"A": "Yes, big bang","B": "Yes, gun shoot","C": "No - dead silent","D": "Yes, soft noise"},"answer": "D"},
{ "question": "When there was some soft noise, Mr. Fox waited long time and thought ___","type": "single","options" : {"A": "It was because of lion","B": "It was a cat","C": "It was a bird","D": "It was some field-mouse"},"answer": "D"},
{ "question": "The wood was murky and very still. 'Murky' means ___","type": "single","options" : {"A": "dark","B": "dark and scarry","C": "dark and watery","D": "dark and dirty"},"answer": "D"},
{ "question": "After Mr. Fox came out fully, what happened?","type": "single","options" : {"A": "Nothing, it ran","B": "It heard small sound behind tree","C": "It saw Mr. Bean","D": "It caught something bright behind tree"},"answer": "D"},
{ "question": "Mr. Fox night-eyes caught a glint of something bright. 'Glint' means ___","type": "single","options" : {"A": "to look yuck","B": "to noisy","C": "to heat","D": "to shine"},"answer": "D"},
{ "question": "'Bang Bang Bang' - Whats that??","type": "single","options" : {"A": "High Silence","B": "Pour water","C": "Stone falling","D": "Sudden explosion"},"answer": "D"},
{ "question": "Did the farmers shoot?","type": "single","options" : {"A": "No, Fox escaped","B": "No bullets in gun","C": "Police came and stopped","D": "Yes, Farmers shot"},"answer": "D"},
{ "question": "Who came finally after the shooting and checked if Mr. Fox is dead?","type": "single","options" : {"A": "Boggis","B": "Bunce","C": "Fox","D": "Bean"},"answer": "D"},
{ "question": "Finally, what did farmers shoot?","type": "single","options" : {"A": "Some Rats","B": "Nothing","C": "Fox's nose","D": "Fox's tail"},"answer": "D"},
{ "question": "When Mr. Fox saw some light behind tree, what did Mr. fox do?","type": "single","options" : {"A": "It ran to river","B": "It jumped above tree","C": "It threw stones","D": "It went inside hole"},"answer": "D"},
{ "question": "When farmers came from behind tree, did they see blood?","type": "single","options" : {"A": "They saw rat","B": "They saw oil","C": "They saw old blood","D": "They saw Fox's blood"},"answer": "D"},
{ "question": "Did the farmers shoot the fox at right time to kill?","type": "single","options" : {"A": "They shot right time","B": "There are no bullets","C": "Rain came in between","D": "They shot a bit late"},"answer": "D"},
{ "question": "After the fox escaped inside, what did farmers do?","type": "single","options" : {"A": "They waited until it came again out","B": "They pour fire inside","C": "They pour water inside tunnel","D": "They thought of digging him out"},"answer": "D"},
{ "question": "When they thought of digging tunnel, Bunce said __","type": "single","options" : {"A": "there are more snakes in","B": "there are more wolves","C": "there is some insects","D": "there is whole fox family"},"answer": "D"},
{ "question": "How was the plan to dig the tunnel to catch fox?","type": "single","options" : {"A": "Using fire","B": "Using screw driver","C": "Using boxes","D": "Using shovel"},"answer": "D"},
{ "question": "Were the farmers ready to kill Mr. Fox or all its family?","type": "single","options" : {"A": "Only Mr. Fox","B": "Only Mr Mrs. Fox - no kids","C": "All foxes in jail","D": "Full family"},"answer": "D"},
{ "question": "What did Mrs. Fox do after Mr. fox lost the tail?","type": "single","options" : {"A": "Mrs. Fox pour water on stump","B": "Mrs. Fox put oil on Mr. Fox's stump","C": "Mrs. Fox put fire on stmp","D": "Mrs. Fox was licking stump of Mr. Fox"},"answer": "D"},
{ "question": "Whose tail was finest in the miles around?","type": "single","options" : {"A": "Mrs. Fox","B": "Fox babies","C": "Bean's tail","D": "Mr. Fox"},"answer": "D"},
{ "question": "Did Mr. Fox say 'It hurts'?","type": "single","options" : {"A": "It said 'lightly'","B": "No, it said","C": "No, because bone was there","D": "Yes, it said"},"answer": "D"},
{ "question": "Who said this? ''Don’t worry Dad! It will grow again'","type": "single","options" : {"A": "Mrs. Fox","B": "Mr. Bean","C": "Mr. Fox","D": "Fox's child"},"answer": "D"},
{ "question": "'The tail will never grow again' - Who said that?","type": "single","options" : {"A": "Mrs. Fox","B": "Mr. Bean","C": "Fox's child","D": "Mr. Fox"},"answer": "D"},
{ "question": "Mrs. Fox was ___ licking the stump of Mr. Fox.","type": "single","options" : {"A": "Fastly","B": "Slowly","C": "Quickly","D": "Tenderly"},"answer": "D"},
{ "question": "Who looked very glum? after losing the tail.","type": "single","options" : {"A": "Mrs. Fox","B": "Mr. Bean","C": "Fox's child","D": "Mr. Fox"},"answer": "D"},
{ "question": "Mr. Fox looked too ___ after losing tail.","type": "single","options" : {"A": "sad","B": "happy","C": "joyful","D": "glum"},"answer": "D"},
{ "question": "Mr. Fox looked glum after losing tail. Which is the right usage of glum?","type": "single","options" : {"A": "After seeing Bigil movie, I was glum","B": "After eating Icecream, I looked glum","C": "After I saw Toy story, I was glum","D": "After losing running race, I looked glum"},"answer": "D"},
{ "question": "Very sad and quiet - which word?","type": "single","options" : {"A": "Sad","B": "Geek","C": "Sombre","D": "Glum"},"answer": "D"},
{ "question": "What food the foxes ate that night?","type": "single","options" : {"A": "Chicken","B": "Goose","C": "Only small foxes ate","D": "None ate any food"},"answer": "D"},
{ "question": "Who all slept that night inside the tunnel","type": "single","options" : {"A": "Mr. Fox","B": "Mrs. Fox","C": "Mr and Mrs. Fox","D": "Mrs. Fox and small foxes"},"answer": "D"},
{ "question": "Why was Mr. Fox unable to sleep full night?","type": "single","options" : {"A": "To safeguard wife and children from farmers","B": "To see if snake will come","C": "Because of rain","D": "Because of pain"},"answer": "D"},
{ "question": "After losing the tail, but Mr. Fox was still alive - Mr. Fox felt ___","type": "single","options" : {"A": "sad","B": "painful","C": "angry","D": "happy"},"answer": "D"},
{ "question": "Mr. Fox was telling we should move out of hole. Is that true?","type": "single","options" : {"A": "No, false","B": "Yes, but 2 days later","C": "No, to shoot farmers","D": "Yes, true"},"answer": "D"},
{ "question": "What noise did Mr. Fox hear as he was telling we should move as soon as possible.","type": "single","options" : {"A": "Big Lion roaring ","B": "Bean was shouting","C": "Gun shooting noise","D": "Shovels were making scraping noise"},"answer": "D"},
{ "question": "What is called 'scraping'?","type": "single","options" : {"A": "it is a noise","B": "it is a music","C": "it is Bean","D": "to remove something from surface"},"answer": "D"},
{ "question": "Which is the right usage of 'scraping'.","type": "single","options" : {"A": "I was scraping the paper to cut into 2 pieces","B": "I was scraping my hair with comb","C": "I was scraping off my hair since it is big","D": "I was scraping bubble gum stuck on table"},"answer": "D"},
{ "question": "Who said this? 'Wake up! They are digging us out.'","type": "single","options" : {"A": "Mrs. Fox","B": "Small Foxes","C": "Mr. Bean","D": "Mr. Fox"},"answer": "D"},
{ "question": "Who said this? 'They will kill my children'","type": "single","options" : {"A": "Bean","B": "Bunce","C": "Boggis","D": "Mrs. Fox"},"answer": "D"},
{ "question": "'Don’t worry. They will not kill us' Who said this?","type": "single","options" : {"A": "Bean","B": "Small Fox","C": "Mrs. Fox","D": "Mr. Fox"},"answer": "D"},
{ "question": "Select the right match:","type": "single","options" : {"A": "Mr. Fox -- Worried","B": "Mrs. Fox -- Bold","C": "Mrs. Fox --Angry","D": "Mrs. Fox -- worried"},"answer": "D"},
{ "question": "'Small stones and bits of earth began falling from ___ of the tunnel'.","type": "single","options" : {"A": "Bottom","B": "Sides","C": "Under","D": "Top"},"answer": "D"},
{ "question": "'How will they kill us?' Who said?","type": "single","options" : {"A": "Mr. Fox","B": "Mrs. Fox","C": "Mr. Bean","D": "Small Foxes"},"answer": "D"},
{ "question": "'Will there be dogs?' Who said?","type": "single","options" : {"A": "Mr. Fox","B": "Mrs. Fox","C": "Mr. Bean","D": "Small Foxes"},"answer": "D"},
{ "question": "Who started crying after hearing the screaching sounds?","type": "single","options" : {"A": "Mr. Fox","B": "Small Foxes","C": "Mr. Bean","D": "Mrs. Fox"},"answer": "D"},
{ "question": "Who closely gathered those 4 small fox kids since they were on utter fear?","type": "single","options" : {"A": "Mr. Fox","B": "Small Foxes","C": "Mr. Bean","D": "Mrs. Fox"},"answer": "D"},
{ "question": "'Suddenly there was a loud ___ above their heads.'","type": "single","options" : {"A": "cry","B": "water","C": "rain","D": "crunch"},"answer": "D"},
{ "question": "The groundnut is so hard. I had to ___ in my mouth and eat.","type": "single","options" : {"A": "lick","B": "suck","C": "sip","D": "crunch"},"answer": "D"},
{ "question": "The sight of loud crunch is an ___ thing seemed to frighten the foxes.","type": "single","options" : {"A": "happy","B": "crunchy","C": "scraping","D": "awful"},"answer": "D"},
{ "question": "'Very bad and unpleasant' - which word fits in.?","type": "single","options" : {"A": "Dirty","B": "Nasty","C": "Sad","D": "Awful"},"answer": "D"},
{ "question": "As soon as they saw the shovels piercing the ceiling, it had an ___ effect upon Mr. Fox","type": "single","options" : {"A": "Happy","B": "Sad","C": "Water","D": "Electric"},"answer": "D"},
{ "question": "What was the idea Mr. Fox came up with?","type": "single","options" : {"A": "Talk to lion and kill the farmers","B": "Put fire on the farmers and escape","C": "Be silent and run away","D": "A fox can dig more deeper and depper to escape"},"answer": "D"},
{ "question": "For escaping which fox was digging faster?","type": "single","options" : {"A": "Mr. Fox","B": "Mrs. Fox","C": "Small Foxes","D": "Everyone"},"answer": "D"},
{ "question": "'Come on, Go deep and deep.. Fast!' Who said that?","type": "single","options" : {"A": "Mrs. Fox","B": "Small Foxes","C": "Everyone","D": "Mr. Fox"},"answer": "D"},
{ "question": "Did the tunnel grow longer and longer when all the foxes started digging in?","type": "single","options" : {"A": "No, only few centimetres","B": "No, too much water was there","C": "Yes, but the farmers were fast","D": "Yes, it started going deeper"},"answer": "D"},
{ "question": "As all the foxes were digging deeper and deeper ____","type": "single","options" : {"A": "Farmers came to know and put fire","B": "Rain started pouring","C": "Mrs. Fox become tired","D": "Gradually, scruning and scraping of shovels become fainter"},"answer": "D"},
{ "question": "As the foxes were digging and digging, the ____ of shovels became fainter","type": "single","options" : {"A": "sound","B": "shining","C": "scintillating","D": "scrunching"},"answer": "D"},
{ "question": "The dry and crispy yellow leaves ___ under my foot","type": "single","options" : {"A": "folded","B": "foiled","C": "scratched","D": "scrunched"},"answer": "D"},
{ "question": "After how long, did the foxes stop digging?","type": "single","options" : {"A": "They never stopped","B": "after 2 hr","C": "after 3 hours","D": "after 1 hr"},"answer": "D"},
{ "question": "Did the foxes become happy after digging for 1 hour continously?","type": "single","options" : {"A": "No, Farmers came all sides","B": "No, Snake was ther","C": "Slightly happy","D": "Oh, Yes!"},"answer": "D"},
{ "question": "After digging continuously for such a long hour, all the foxes sat and ___ for breath.","type": "single","options" : {"A": "searching","B": "bathing","C": "washing","D": "panting"},"answer": "D"},
{ "question": "'If you father wasn’t there for us, we would have been killed'. Who said that?","type": "single","options" : {"A": "Mother to Father","B": "Farmer to father","C": "Kids to mother","D": "Mother to kids"},"answer": "D"},
{ "question": "'Your father is a fantastic fox'. Who said this?","type": "single","options" : {"A": "Mrs. Fox","B": "Small Foxes","C": "Bean","D": "Mr. Fox"},"answer": "D"},
{ "question": "'I ran so far and stopped and I was ___ for breath'.","type": "single","options" : {"A": "searching","B": "hardly","C": "breathing","D": "panting"},"answer": "D"},
{ "question": "Farmers were digging ___","type": "single","options" : {"A": "whole of the night","B": "3 hrs","C": "5 hrs","D": "until next morning"},"answer": "D"},
{ "question": "How big the hole was which farmers were digging?","type": "single","options" : {"A": "They were 15 feet down","B": "It was 1 person tall","C": "It was 5 kilometres","D": "It was 1 full house tall"},"answer": "D"},
{ "question": "They were not still able to reach the Fox's tunnel. 'Whose rotten idea was that' Who asked?","type": "single","options" : {"A": "Bunce","B": "Bean","C": "Mr. Fox","D": "Boggis"},"answer": "D"},
{ "question": "'Whose rotten idea was this'? Rotten means __","type": "single","options" : {"A": "Black one","B": "Difficult one","C": "Hard one","D": "Not fresh"},"answer": "D"},
{ "question": "___ Vegetables.  How do you express if the vegetables are old and spoiled","type": "single","options" : {"A": "Bad","B": "Old","C": "Round","D": "Rotten"},"answer": "D"},
{ "question": "Whose idea was to dig dig and dig?","type": "single","options" : {"A": "Boggis","B": "Bunce","C": "Mr. Fox","D": "Bean"},"answer": "D"},
{ "question": "Who was angry even after so much digging they were not able to reach the tunnel?","type": "single","options" : {"A": "Bunce","B": "Bean","C": "Mr. Fox","D": "Boggis"},"answer": "D"},
{ "question": "'I am going to get that fox. I am not giving in'.  'giving in' means?","type": "single","options" : {"A": "giving apple cider","B": "giving shovel","C": "not harming fox","D": "not leaving"},"answer": "D"},
{ "question": "After so many attempts to catch the mango on the tree, I ___ up","type": "single","options" : {"A": "went up","B": "try up","C": "jump up","D": "gave up"},"answer": "D"},
{ "question": "'I will strung him up over my front porch'. Porch means?","type": "single","options" : {"A": "Tummy","B": "Stomach","C": "Above the house","D": "Front side of house"},"answer": "D"},
{ "question": "'dead as a dumpling!'  Dumpling means?","type": "single","options" : {"A": "water packets","B": "doughnut paste","C": "disgusting paste","D": "dish made of variety of batter"},"answer": "D"},
{ "question": "'My mom put Rangoli over house ___'","type": "single","options" : {"A": "top","B": "strangling","C": "torch","D": "porch"},"answer": "D"},
{ "question": "'I don’t think we will get him by digging like this. We have dug up so much'. Who said this?","type": "single","options" : {"A": "Bean","B": "Bunce","C": "Fox","D": "Boggis"},"answer": "D"},
{ "question": "'Do you have any more stupid ideas'? Who asked?","type": "single","options" : {"A": "Bean","B": "Boggis","C": "Fox","D": "Bunce"},"answer": "D"},
{ "question": "Bean cant hear properly any questions because __","type": "single","options" : {"A": "he drinks apple cider","B": "he does not take bath","C": "his eyes are full of galeej","D": "his ear is full of muck and wax"},"answer": "D"},
{ "question": "What was Beans idea after everything failed digging?","type": "single","options" : {"A": "To put fire and get the fox out","B": "To put water and get fox out","C": "To dig more faster with more ppl","D": "To get machines and dig more"},"answer": "D"},
{ "question": "Did Bunce and Boggis agreed new idea of mechanical shovels and machines?","type": "single","options" : {"A": "They shouted back","B": "They did not agree","C": "They ran away","D": "They said good idea"},"answer": "D"},
{ "question": "Who went back to bring machines and mechanical shovels?","type": "single","options" : {"A": "Bean","B": "Boggis","C": "Boggis and Bean","D": "Bean and Bunce"},"answer": "D"},
{ "question": "What if fox came out when 2 farmers went to bring mechanical shovels and machines?","type": "single","options" : {"A": "Bean will put bomb","B": "Foxes already escaped","C": "Put snake on Fox","D": "Boggis will have to shoot fox"},"answer": "D"},
{ "question": "The tiny Bunce trotted after him'. After whom?","type": "single","options" : {"A": "Boggis","B": "Bunce","C": "Fox","D": "Bean"},"answer": "D"},
{ "question": "The tiny Bunce trotted after him'. Trotted means ___","type": "single","options" : {"A": "flying","B": "running","C": "walking","D": "walking more faster"},"answer": "D"},
{ "question": "How many tractors arrived near the tree?","type": "single","options" : {"A": "one","B": "three","C": "four","D": "two"},"answer": "D"},
{ "question": "Who brought tractors to the scene of digging?","type": "single","options" : {"A": "Boggis","B": "Bean","C": "Bunce","D": "Bean & Bunce"},"answer": "D"},
{ "question": "How were the tractors that came?","type": "single","options" : {"A": "caterpillar","B": "enormous and shining","C": "black and white color","D": "enourmous and caterpillar"},"answer": "D"},
{ "question": "How many tractors Bean was driving and Bunce was driving","type": "single","options" : {"A": "Both by Bean","B": "Both by Bunce","C": "2 other drivers","D": "Bean one, Bunce one"},"answer": "D"},
{ "question": "The tractors were looking like ___","type": "single","options" : {"A": "big godzilla","B": "big size dragons","C": "brutal murderers","D": "brutal looking monsters"},"answer": "D"},
{ "question": "What did the tractors do to the tree?","type": "single","options" : {"A": "Tractors did nothing to tree","B": "Tractors burnt the tree","C": "Tractors killed the tree","D": "Tractors toppled the tree"},"answer": "D"},
{ "question": "Tractor uprooted the tree like ___","type": "single","options" : {"A": "flag pole","B": "big size pole","C": "caterpillar","D": "match stick"},"answer": "D"},
{ "question": "'Whats happening dad?' When did the small fox ask like this to father?","type": "single","options" : {"A": "After Mr. Fox was crying loosing tail","B": "After Mrs. Fox cried like anything","C": "After they saw the snake biting","D": "After big size tractor started digging up"},"answer": "D"},
{ "question": "'It is an earthquake' Who told this?","type": "single","options" : {"A": "Mr. Fox","B": "Bean","C": "Small Foxes","D": "Mrs. Fox"},"answer": "D"},
{ "question": "'Our tunnel is getting shorter. See I can see sunlight'. Who said this?","type": "single","options" : {"A": "Mr. Fox","B": "Mrs. Fox","C": "Bean","D": "One small fox"},"answer": "D"},
{ "question": "When everyone started seeing big hole above, what did all the foxes see?","type": "single","options" : {"A": "They saw all farmers angry","B": "They saw heavy sunlight","C": "They saw big tree fallen","D": "They saw 2 black tractors"},"answer": "D"},
{ "question": "After all the foxes saw the two tractors above the hole - What did they all do?","type": "single","options" : {"A": "They just surrendered","B": "They started crying","C": "They jumped into water","D": "They started dig dig and digging more"},"answer": "D"},
{ "question": "As the digging was going, the race was between whom?","type": "single","options" : {"A": "Mr Fox and Bean","B": "Mr Fox and Small foxes","C": "Bean and Boggis","D": "Farmers and foxes"},"answer": "D"},
{ "question": "What was the race all about?","type": "single","options" : {"A": "Which small foxes will run fast","B": "Bean of Bunce who will dig fast","C": "Boggis or Bunce who digs fast?","D": "Whether farmers will dig fast or the foxes"},"answer": "D"},
{ "question": "The race was quite ___ (fill the right apt word)","type": "single","options" : {"A": "faster","B": "slower","C": "deeper","D": "desperate"},"answer": "D"},
{ "question": "Which is the right usage of 'desperate'.","type": "single","options" : {"A": "I was so desperate for studying","B": "I was so desperate after I had icecream","C": "I was desperate to get hurt","D": "I was so desperate to drink water after I got thirsty"},"answer": "D"},
{ "question": "'We are going to make it' - Who said this?","type": "single","options" : {"A": "Mrs. Fox","B": "Bean","C": "Bunce","D": "Mr. Fox"},"answer": "D"},
{ "question": "'We are going to make it' - What is Mr. Fox going to make it?","type": "single","options" : {"A": "Going to dig big hole for swimming","B": "Going to kill farmers","C": "Going to bomb the tractors","D": "Going to escape from farmers"},"answer": "D"},
{ "question": "The __ of the mighty shovels would get louder and louder.","type": "single","options" : {"A": "Color","B": "Creeching","C": "Creed","D": "Crunch"},"answer": "D"},
{ "question": "Were the shovels coming closer to fox as the fox was digging deeper?","type": "single","options" : {"A": "Not that close","B": "Too far","C": "Above the head","D": "Too close"},"answer": "D"},
{ "question": "'Keep going. Don’t give up'  What does 'Give up mean?","type": "single","options" : {"A": "Giving water","B": "Giving food","C": "Giving away confidence","D": "Giving away the fight"},"answer": "D"},
{ "question": "'We will get them any moment now' Who said that?","type": "single","options" : {"A": "All the farmers","B": "All the foxes","C": "The crowd there","D": "Boggis said"},"answer": "D"},
{ "question": "'Have you caught sight of him yet?'  Caught sight means","type": "single","options" : {"A": "Have you caught the ball","B": "Have you caught the tail?","C": "Have you killed the fox?","D": "Have you started seeing?"},"answer": "D"},
{ "question": "'Have you caught sight of him yet?'  Who said this?","type": "single","options" : {"A": "Boggis","B": "Bunce","C": "Fox","D": "Bean"},"answer": "D"},
{ "question": "'I will pick him up with my bucket' Who said that","type": "single","options" : {"A": "Bean","B": "Bunce","C": "Fox","D": "Boggis"},"answer": "D"},
{ "question": "'I will pick him up with my bucket' Pick whom with my bucket?","type": "single","options" : {"A": "Chicken","B": "Boggis","C": "Bunce","D": "Fox"},"answer": "D"},
{ "question": "'I will chop him to pieces' Whom will Bunce chop?","type": "single","options" : {"A": "Carrot","B": "Chicken","C": "Goose & Duck","D": "Fox"},"answer": "D"},
{ "question": "Were they able to achieve at lunch time? Digging and catching the foxes?","type": "single","options" : {"A": "Yes","B": "Much before","C": "They fell down","D": "No"},"answer": "D"},
{ "question": "Did the farmers take rest at Lunch time?","type": "single","options" : {"A": "Yes","B": "Much before","C": "They fell down","D": "No"},"answer": "D"},
{ "question": "'Hey there, Mr. Fox!' - Who said that?","type": "single","options" : {"A": "Bean","B": "Boggis","C": "Mr. Fox","D": "Bunce"},"answer": "D"},
{ "question": "You had your last chicken!' yelled ___","type": "single","options" : {"A": "Bean","B": "Bunce","C": "Mr. Fox","D": "Boggis"},"answer": "D"},
{ "question": "'You will never come prowling around my farm again!' Boggis said. What is prowling?","type": "single","options" : {"A": "Crawling and Crounching","B": "Screeching","C": "Killing","D": "Steal and move quietly"},"answer": "D"},
{ "question": "Bean and Bunce were driving tractors like 'maniacs'. Maniacs means?","type": "single","options" : {"A": "Extreme soft","B": "A little wile","C": "A little tired","D": "Extreme wild"},"answer": "D"},
{ "question": "Bean and Bunce were digging at ___ speed.","type": "single","options" : {"A": "Slow speed because water is there","B": "Careful speed","C": "Long","D": "Terrific"},"answer": "D"},
{ "question": "The fat Boggis was hopping about like a dervish and shouting 'Faster, Faster'.  Dervish means?","type": "single","options" : {"A": "Praying God so much","B": "Dancing","C": "Running","D": "Wild strong rituals"},"answer": "D"},
{ "question": "By 5'0' clock evening did they catch all the foxes?","type": "single","options" : {"A": "Only small foxes","B": "Yes, all foxes killed","C": "They all fell down","D": "No"},"answer": "D"},
{ "question": "The machines dug the hole like ___ of a volcano.","type": "single","options" : {"A": "mouth","B": "open","C": "gate","D": "crater"},"answer": "D"},
{ "question": "Who came rushing to see the extraordinary sight of digging?","type": "single","options" : {"A": "police","B": "animals","C": "friends from hosur","D": "people surrounding villages"},"answer": "D"},
{ "question": "'You must be mad' for digging such a hole. Who said that?","type": "single","options" : {"A": "Bean","B": "Bunce","C": "Fox","D": "People"},"answer": "D"},
{ "question": "When people jeered and laughted, the farmers ___","type": "single","options" : {"A": "become angry and shot at them","B": "become sad","C": "become happy","D": "become more furious and determined"},"answer": "D"},
{ "question": "'We are after ___' farmer said when questioned by people","type": "single","options" : {"A": "5 '0' clock","B": "farmer","C": "digging","D": "fox"},"answer": "D"},
{ "question": "'Extraordinary' means?","type": "single","options" : {"A": "Very ordinary","B": "Less than ordinary","C": "Extra cheese","D": "More than ordinary"},"answer": "D"},
{ "question": "When was the Tractor motor switched off?","type": "single","options" : {"A": "Never","B": "5 '0' clock","C": "7 '0' clock","D": "6 '0' clock"},"answer": "D"},
{ "question": "Who switched off the Tractor?","type": "single","options" : {"A": "Bunce","B": "Boggis","C": "Badger","D": "Bean"},"answer": "D"},
{ "question": "At 6'0' clock did the farmers find the any fox?","type": "single","options" : {"A": "Yes","B": "Only kids","C": "Only Mr. Fox","D": "No"},"answer": "D"},
{ "question": "Who are the two who climbed down from Tractor at 6 in evening after such a long work day?","type": "single","options" : {"A": "Bunce & Boggis","B": "Bean & Boggis","C": "Fox & Bean","D": "Bean & Bunce"},"answer": "D"},
{ "question": "How were Bean when he came out of tractor?","type": "single","options" : {"A": "Energetic","B": "Angry","C": "Sad","D": "Tired"},"answer": "D"},
{ "question": "With so much of anger who was cursing the fox with 'dirty' bad words?","type": "single","options" : {"A": "Bean","B": "Boggis","C": "Badger","D": "Bunce"},"answer": "D"},
{ "question": "'Dang and blast that filthy stinking fox!' Who said this? He keeps on saying 'Dang..Dang..'","type": "single","options" : {"A": "Bean","B": "Bunce","C": "Badger","D": "Boggis"},"answer": "D"},
{ "question": "After so much of tiresome work with tractor, what did 3 farmers do?","type": "single","options" : {"A": "They told they will go home","B": "They told they will sleep","C": "They told we will throw fire inside","D": "They told they will never let him go!"},"answer": "D"},
{ "question": "After all the 3 farmers declared 'will not let him go', who yelled at Mr. fox saying 'Did you hear that, Mr. Fox?'","type": "single","options" : {"A": "Bunce","B": "Boggis","C": "Badger","D": "Bean"},"answer": "D"},
{ "question": "Whats the solemn oath the farmers took after so much of digging?","type": "single","options" : {"A": "That they will die there","B": "That they will catch fox with tail","C": "That they will inform Police and catch all foxes","D": "That they will not go back to farms until fox was caught"},"answer": "D"},
{ "question": "Who asked 'Whats the next move?' after failing?","type": "single","options" : {"A": "Bean","B": "Boggis","C": "Badger","D": "Bunce"},"answer": "D"},
{ "question": "Whats the next move'? - How did Bean answer this?","type": "single","options" : {"A": "Lets go and sleep","B": "Lets put bomb on fox","C": "We all three will go inside the hold","D": "We are sending you down the hole"},"answer": "D"},
{ "question": "You little midget!' Midget means?","type": "single","options" : {"A": "Idiot person","B": "Pot bellied person","C": "Useless person","D": "Very small person"},"answer": "D"},
{ "question": "When he smiled one can see his scarlet gums.  Whose smile we are talking about","type": "single","options" : {"A": "Bunce","B": "Boggis","C": "Badger","D": "Bean"},"answer": "D"},
{ "question": "When he smiled one can see his scarlet gums.  'Scarlet' means?","type": "single","options" : {"A": "Scarry gums","B": "Orange gums","C": "Green orange gums","D": "Bright red gums"},"answer": "D"},
{ "question": "'There is only one thing to do' Whats that one thing?","type": "single","options" : {"A": "To put bomb inside the fox hole","B": "To shift house near the hill itself","C": "To beg fox to come out","D": "To make fox starve and die"},"answer": "D"},
{ "question": "What was the idea after long tiresome Tractor work?","type": "single","options" : {"A": "To go home","B": "To call Police and beat fox","C": "To kill fox by pushing fire","D": "To camp there day and night"},"answer": "D"},
{ "question": "When farmers decided to stay near the hill itself, what did they do?","type": "single","options" : {"A": "They climbed trees and slept there","B": "They lived near a den at the pond","C": "They slept inside the Tractor","D": "They sent messages asking for tents"},"answer": "D"},
{ "question": "'We camp here day and night watching the ___'","type": "single","options" : {"A": "fox","B": "animals","C": "birds","D": "hole"},"answer": "D"},
{ "question": "'We camp here day and night watching…' Camp means?","type": "single","options" : {"A": "Going in a bus","B": "Working whole night","C": "Singing","D": "Sleeping in the tent"},"answer": "D"},
{ "question": "Bean made a sickly smile.  'Sickly' means?","type": "single","options" : {"A": "Angry","B": "Sad","C": "Hapy","D": "Unpleasant"},"answer": "D"},
{ "question": "How many tents did the farmers keep around the Fox hold?","type": "single","options" : {"A": "four","B": "one","C": "zero","D": "three"},"answer": "D"},
{ "question": "After keeping tents around the fox hold, what did farmers do","type": "single","options" : {"A": "Kept more chickens inside hole","B": "Kept more food for fox","C": "Sat outside with guns","D": "Stood outside and ate supper"},"answer": "D"},
{ "question": "In outside tents, Boggis ate __","type": "single","options" : {"A": "Apple cider","B": "Doughnut paste","C": "No eating, only gun","D": "Chicken"},"answer": "D"},
{ "question": "In outside tents, Bunce ate __","type": "single","options" : {"A": "Chicken","B": "Apple cider","C": "No eating, only gun","D": "Doughnut paste"},"answer": "D"},
{ "question": "In outside tents, Bean ate __","type": "single","options" : {"A": "Chicken","B": "Doughnut paste","C": "No eating, only gun","D": "Apple cider"},"answer": "D"},
{ "question": "'Hey fox, can you smell this'? Who shouted?","type": "single","options" : {"A": "Bean","B": "Bunce","C": "Badger","D": "Boggis"},"answer": "D"},
{ "question": "'Hey fox, can you smell this'? Smell what?","type": "single","options" : {"A": "Apple cider","B": "Doughnut paste","C": "Rat","D": "Chicken"},"answer": "D"},
{ "question": "Did the smell of chicken reach the foxes hiding inside the hole?","type": "single","options" : {"A": "No, they were far","B": "That was duck","C": "Rat smell was there","D": "Oh, Yes!"},"answer": "D"},
{ "question": "'Can we snatch the chicken from his hand and eat?' Who said?","type": "single","options" : {"A": "Mrs. Fox","B": "Mr. Fox","C": "Farmers","D": "Small fox"},"answer": "D"},
{ "question": "'Don’t you dare'  - dare for what?","type": "single","options" : {"A": "Dare to come out","B": "Dare to kill farmer","C": "Dare to run away","D": "Dare to snatch chicken"},"answer": "D"},
{ "question": "'Don’t you dare'  - Who said this while responding","type": "single","options" : {"A": "Mrs. Fox","B": "Small fox","C": "Farmers","D": "Mr. Fox"},"answer": "D"},
{ "question": "'How long will it be till we get something to eat?' Who said this","type": "single","options" : {"A": "Mrs. Fox","B": "Mr. Fox","C": "Farmers","D": "Small fox"},"answer": "D"},
{ "question": "How did Father / Mother respond when kids said they were angry and how long they should starve","type": "single","options" : {"A": "They said shut up","B": "They gave water","C": "They gave old bananan","D": "They didn’t reply"},"answer": "D"},
{ "question": "It become night and dark. What did farmers do?","type": "single","options" : {"A": "Switched on Emergency light","B": "Switched on a candle","C": "They slept inside the Tractor","D": "Switched on Tractor headlamps"},"answer": "D"},
{ "question": "Where did the farmers focus the tractor light towards?","type": "single","options" : {"A": "Towards their tents","B": "Towards the sky","C": "Towards the pond","D": "Towards the hole"},"answer": "D"},
{ "question": "What was the plan to check if fox is coming out hole?","type": "single","options" : {"A": "Keep an alarm","B": "Close the door at the hole","C": "Stall a tiger near the tree","D": "Take up turn to keep watch"},"answer": "D"},
{ "question": "How many will sleep and how many will watch?","type": "single","options" : {"A": "2 watch, 1 sleep","B": "3 sleep 0 watch","C": "all 3 will watch","D": "2 will sleep, 1 watch"},"answer": "D"},
{ "question": "'What if the fox digs a hole right through and comes out _____ _____' - farmer said.","type": "single","options" : {"A": "Top side","B": "Below side","C": "Fresh side","D": "Other side"},"answer": "D"},
{ "question": "To avoid fox escaping from otherside, what did farmers do?","type": "single","options" : {"A": "They kept fire all around","B": "They kept Tigers around hole","C": "They poured water inside","D": "They gathered men to keep around"},"answer": "D"},
{ "question": "How many men you have in your farm? - Biggis response?","type": "single","options" : {"A": "30","B": "36","C": "37","D": "35"},"answer": "D"},
{ "question": "How many men you have in your farm? - Bunce response?","type": "single","options" : {"A": "35","B": "30","C": "37","D": "36"},"answer": "D"},
{ "question": "How many men you have in your farm? - Bean response?","type": "single","options" : {"A": "35","B": "30","C": "36","D": "37"},"answer": "D"},
{ "question": "Who asked 'How many men you have in your farm'?","type": "single","options" : {"A": "Bunce","B": "Boggis","C": "Badger","D": "Bean"},"answer": "D"},
{ "question": "Totally how many men in all the farm put together?","type": "single","options" : {"A": "109","B": "110","C": "100","D": "108"},"answer": "D"},
{ "question": "What will all men do now? (whoever are working in farm)","type": "single","options" : {"A": "They sleep around hole","B": "They will make food far farmers","C": "They will chase fox","D": "They stand around the hole"},"answer": "D"},
{ "question": "All the 100+ working men will be given ___ and ____","type": "single","options" : {"A": "Stick and Light","B": "Gun and Stick","C": "Food and water","D": "Gun and Light"},"answer": "D"},
{ "question": "Did all the 100 plus men come after the farmers called them?","type": "single","options" : {"A": "No - that was night","B": "Yes, only half but","C": "No - they were far","D": "Yes."},"answer": "D"},
{ "question": "What did all 100 plus men came and have in their hands.","type": "single","options" : {"A": "Only Gun","B": "Water, Food","C": "Tanks","D": "Gun, Lights, Sticks"},"answer": "D"},
{ "question": "When everyone was around the small hole, what did Mr. Fox do?","type": "single","options" : {"A": "Mr. Fox slept inside","B": "Mr Fox was dancing with kids","C": "Mr. Fox was eating last food","D": "Mr. Fox comes out and sniffs"},"answer": "D"},
{ "question": "Mr Fox sniffed and came inside. Mrs. Fox asked 'Are you sure they are there'. What did Mr. Fox respond","type": "single","options" : {"A": "Not sure","B": "Its too dark","C": "Farmers slept","D": "Positive"},"answer": "D"},
{ "question": "How can Mr. Fox surely tell they are there?","type": "single","options" : {"A": "Because of light","B": "Because of food smell","C": "Because of people's noise","D": "Because of stinky smell"},"answer": "D"},
{ "question": "Whose stinky smell proved that Mr. Fox know that they are there?","type": "single","options" : {"A": "Bunce","B": "Boggis","C": "Badger","D": "Bean"},"answer": "D"},
{ "question": "How many days and nights went on waiting","type": "single","options" : {"A": "2 days, 2 nights","B": "3 days, 2 nights","C": "only one","D": "3 days, 3 nights"},"answer": "D"},
{ "question": "What did fox eat hiding inside the hole for days and nights?","type": "single","options" : {"A": "Only small rats","B": "Some old grains","C": "Old Chicken","D": "Nothing"},"answer": "D"},
{ "question": "'Oh Dad, cant you do ____' We are hungry.","type": "single","options" : {"A": "Nothing","B": "Beat them","C": "Kill them","D": "Something"},"answer": "D"},
{ "question": "'Oh Dad, cant you do….' Who asked? (while starving)","type": "single","options" : {"A": "Mr. Fox","B": "Mrs. Fox","C": "Farmers","D": "Small Foxes"},"answer": "D"},
{ "question": "After starving so much, 'Couldn’t we make a ____ for it, Dad?'","type": "single","options" : {"A": "kill","B": "run","C": "go","D": "dash"},"answer": "D"},
{ "question": "When small foxes said 'couldn’t we make dash of it', Mrs. fox said:","type": "single","options" : {"A": "Yes, lets go!","B": "Ask your dad","C": "Slowly","D": "No No chance at all"},"answer": "D"},
{ "question": "'I refuse to let you go up there and face those ___' Mrs. Fox said","type": "single","options" : {"A": "Fire","B": "Farmers","C": "Kill","D": "Guns"},"answer": "D"},
{ "question": "Instead of facing guns, Mrs. fox let the small foxes to die in ____","type": "single","options" : {"A": "Hole","B": "Water","C": "Hunger","D": "Peace"},"answer": "D"},
{ "question": "What was Mr. Fox doing inside hold 3 days, 3 nights?","type": "single","options" : {"A": "Was making some food","B": "Was looking which farmer is outside","C": "Searching food inside the hole","D": "Did not speak for long time"},"answer": "D"},
{ "question": "When Mr. Fox did not speak at all for long time, what did Mrs. Fox think?","type": "single","options" : {"A": "May be Mr. fox is died","B": "May be Mr. Fox slept","C": "May be Mr. Fox is hungry","D": "May be Mr. Fox is thinking a plan"},"answer": "D"},
{ "question": "After long time not speaking, Did Mr. Fox come up with something?","type": "single","options" : {"A": "No, he was already tired","B": "Yes, he will run","C": "No, he asked small foxes to escape","D": "Yes, He said having an idea"},"answer": "D"},
{ "question": "What did Mr. Fox feel himself on his own idea?","type": "single","options" : {"A": "He said Idea is superb","B": "He said difficult idea","C": "He said offo","D": "He said idea is not that good"},"answer": "D"},
{ "question": "When kids asked 'Dad, whats the idea?' Mr. Fox said ___","type": "single","options" : {"A": "It is bad idea","B": "In this idea, we will loose lives","C": "It is impossible idea","D": "It won't work after all"},"answer": "D"},
{ "question": "What was the idea after long thought from Mr. Fox?","type": "single","options" : {"A": "To burn tractors","B": "To put fire on farmers","C": "To send snakes towards farmers","D": "More digging on other side"},"answer": "D"},
{ "question": "Why did Mr. Fox think 'digging on other side' is not a good idea?","type": "single","options" : {"A": "Because on other side, snakes are there","B": "Because, on all side farmers men are ther","C": "Because, there are many stones","D": "Because, already all foxes are tired"},"answer": "D"},
{ "question": "Why did Mr. Fox think all are tired?","type": "single","options" : {"A": "Because all foxes were digging big size hole","B": "Because foxes are lazy","C": "Because foxes ate Veg food","D": "Because all foxes were hungry 3 days 3 nights"},"answer": "D"},
{ "question": "When Mr. Fox said, it is a bad idea because u r so tired, small foxes said ___ __","type": "single","options" : {"A": "Yes dad, we are tired","B": "No we cannot do","C": "Dad, you only do it","D": "Yes, we can"},"answer": "D"},
{ "question": "Small foxes said 'We can' - What did Mr. Fox think!?","type": "single","options" : {"A": "The children are idiots","B": "The children are brave","C": "The children are naughty","D": "What a fine children we have"},"answer": "D"},
{ "question": "How were small foxes when dad said you have to dig further?","type": "single","options" : {"A": "They were sad","B": "They were lazy","C": "They were strong","D": "They were undefeated"},"answer": "D"},
{ "question": "'Tell us dad what you want us to do!' - Who said ?","type": "single","options" : {"A": "Mr. Fox","B": "Bean","C": "Bunce","D": "Small Foxes"},"answer": "D"},
{ "question": "Who was suffering more and more than all foxes?","type": "single","options" : {"A": "Mr. Fox","B": "Small Foxes","C": "Tiny fox","D": "Mrs. Fox"},"answer": "D"},
{ "question": "When Mrs. Fox said, 'I am so sorry - I don’t think I can help'. Mr. Fox said __","type": "single","options" : {"A": "You cant say like that, we should escape","B": "You sleep","C": "You motivate small foxes","D": "We can handle this by ourselves"},"answer": "D"},
{ "question": "Finally, who started digging the hole on other sides?","type": "single","options" : {"A": "All foxes","B": "Mr. Fox alone","C": "Mrs. Fox and small foxes","D": "Mr. Fox and small foxes"},"answer": "D"},
{ "question": "Did small foxes have any energy to dig further the hole?","type": "single","options" : {"A": "Not at all, they are too small","B": "Only after Mom gave milk","C": "Only after dad gave them some old chicken","D": "Yes, a little bit"},"answer": "D"},
{ "question": "The tunnel began to grow and what did the little fox ask?","type": "single","options" : {"A": "Dad, I am afraid","B": "Dad, I am nervous","C": "Dad, lets go home","D": "Dad, I wish you tell where we are going?"},"answer": "D"},
{ "question": "Did Mr. Fox tell where he is going when the small foxed asked?","type": "single","options" : {"A": "A little bit he said","B": "He was unable to talk","C": "Yes","D": "No"},"answer": "D"},
{ "question": "Why did Mr. Fox not tell where he is going to the children","type": "single","options" : {"A": "Small foxes will be afraid","B": "Small foxes will be nervous","C": "Sound should not come","D": "Small fox will go crazy with excitement"},"answer": "D"},
{ "question": "What did Mr. fox think about children when they would not reach the place which Mr. fox thought","type": "single","options" : {"A": "Farmers will bomb","B": "Police will shoot","C": "Small foxes will run away","D": "Small foxes would die of disappointment"},"answer": "D"},
{ "question": "Did Mr. Fox raise hopes when the tunnel was dug up in different direction","type": "single","options" : {"A": "Yes","B": "He felt happy","C": "He shut up small foxes","D": "No"},"answer": "D"},
{ "question": "When Mr. Fox slowly reached the top, there was a hard thing above head!  What is that?","type": "single","options" : {"A": "Its glass","B": "Its farmer's gun","C": "They are trees","D": "Its wood!"},"answer": "D"},
{ "question": "After Mr. Fox opened the wooden plank, how was Mr. Fox feeling","type": "single","options" : {"A": "Very tired","B": "Very nervous","C": "Very frightened","D": "Excited!"},"answer": "D"},
{ "question": "'I have done it' who said after opening the Wooden planks?","type": "single","options" : {"A": "Small fox","B": "Big Fox","C": "Mrs. fox","D": "Mr. Fox"},"answer": "D"},
{ "question": "What a sight for a hungry fox! _____ Hooray! Hooray!!  (fill it)","type": "single","options" : {"A": "Wow","B": "Cool","C": "Good!","D": "Hallelujah!"},"answer": "D"},
{ "question": "Where did Mr. Fox and small foxes ended up after opening wooden plank","type": "single","options" : {"A": "Big Lions cave","B": "Under the tree","C": "Farmer's bath tub","D": "Large shed with teeming chickens"},"answer": "D"},
{ "question": "Which house did Mr. Fox and small foxes reach after hours of long digging?","type": "single","options" : {"A": "Big Lions cave","B": "Under the tree","C": "Farmer's bath tub","D": "Boggis Chicken House Number 1"},"answer": "D"},
{ "question": "How were the small foxes after reaching chicken house?","type": "single","options" : {"A": "Very tired","B": "Very nervous","C": "Very frightened","D": "Excited!"},"answer": "D"},
{ "question": "Wait, wait! Calm down!! Let us do properly. First of all, everyone have ___ ___ __","type": "single","options" : {"A": "small prayer","B": "small ground nuts","C": "some juice","D": "a drink of water"},"answer": "D"},
{ "question": "Wait! Calm down!! Who said this to control excitement?","type": "single","options" : {"A": "Small fox","B": "Big Fox","C": "Mrs. fox","D": "Mr. Fox"},"answer": "D"},
{ "question": "After eating chickens, where did all the foxes go?","type": "single","options" : {"A": "Went home","B": "Went friend's house","C": "Went near farmers","D": "They went back to tunnel"},"answer": "D"},
{ "question": "Run back with these 3 plump hens and give it to your ____, Mr. Fox said (fill it)","type": "single","options" : {"A": "Aunt","B": "Uncle","C": "Badger","D": "Mother"},"answer": "D"},
{ "question": "Who took chickens to Mrs. Fox?","type": "single","options" : {"A": "Mr. Fox himself","B": "Everyone","C": "Dog","D": "Eldest of children","E": "Rat"},"answer": "D"},
{ "question": "Mommy! He cried - Look, Mummy, look! - Who said this?","type": "single","options" : {"A": "Mr. Fox himself","B": "Everyone","C": "Small Foxes","D": "Eldest of children","E": "Boggis"},"answer": "D"},
{ "question": "How was Mrs. Fox when the child fox arrived with hens?","type": "single","options" : {"A": "Stronger","B": "Sad","C": "Disappointed","D": "Tired and weaker"},"answer": "D"},
{ "question": "After seeing so many chickens with her child, who said 'I am dreaming'","type": "single","options" : {"A": "Small Fox","B": "Small Rat","C": "Big Mouse","D": "Mrs. Fox"},"answer": "D"},
{ "question": "Did Mrs. fox ask where the hens came from?","type": "single","options" : {"A": "No","B": "Mrs. fox cannot talk","C": "Small fox asked","D": "Yes"},"answer": "D"},
{ "question": "What did child fox said to Mrs. fox when asked where the chickens from? He said ___","type": "single","options" : {"A": "First you eat","B": "I don’t know","C": "Dad gave it","D": "Boggis Chicken House"},"answer": "D"},
{ "question": "Oh! What a fantastic fox your father is! Who said this?","type": "single","options" : {"A": "Child Fox","B": "Child Foxes","C": "Mr. Fox","D": "Mrs. Fox","E": "Bruce"},"answer": "D"},
{ "question": "How many small foxes were with Mrs. Fox to give chicken?","type": "single","options" : {"A": "All small foxes","B": "None","C": "Mr. Fox was there","D": "One"},"answer": "D"},
{ "question": "While small fox gave chicken to Mrs. Fox, where was Mr. Fox and other children?","type": "single","options" : {"A": "they ran away","B": "they were bathing","C": "they were in pond","D": "Other end digging another little tunnel"},"answer": "D"},
{ "question": "How many child foxes are with Mr. Fox after eating at Boggis' chicken house?","type": "single","options" : {"A": "1 small fox","B": "2 small foxes","C": "4 small foxes","D": "3 small foxes"},"answer": "D"},
{ "question": "What were the remaining child foxes doing after eating chickens?","type": "single","options" : {"A": "They slept there","B": "They were tired","C": "They ran away on tree","D": "They were digging as dad said"},"answer": "D"},
{ "question": "While the foxes were having the chickens, where were the farmers, Boggis, Bunce and Bruno?","type": "single","options" : {"A": "They were sleeping","B": "They were eating chickens","C": "They were practicing shooting","D": "They were sitting on hill waiting foxes"},"answer": "D"},
{ "question": "When Mr. foxes and small foxes were digging, they heard a sound above their head - what was that?","type": "single","options" : {"A": "Stop now","B": "Shoot them","C": "Who ran now?","D": "Who goes there?"},"answer": "D"},
{ "question": "When Mr. Fox heard 'Who goes there' above their head, who was that?","type": "single","options" : {"A": "Cheetah","B": "Bunce","C": "Boggis","D": "Badger"},"answer": "D"},
{ "question": "When Mr. Fox saw badger, they were ___","type": "single","options" : {"A": "angry at each other","B": "sad at each other","C": "shouted at each other","D": "happy to see each other"},"answer": "D"},
{ "question": "What did Badger say to Mr. Fox sitting so sad?","type": "single","options" : {"A": "Go back, farmers are shooting u","B": "Go back, Cheetah is ther","C": "It is dangerous here","D": "Its chaos here!"},"answer": "D"},
{ "question": "We are all starving to death' - who said this?","type": "single","options" : {"A": "Mr. Fox","B": "Mrs. Fox","C": "Small foxes","D": "Badger"},"answer": "D"},
{ "question": "We are all starving to death' Badger said. Who is that 'we'?","type": "single","options" : {"A": "All farmers","B": "All men helpers","C": "Badgers and wives","D": "Badger, Mole, wives and children"},"answer": "D"},
{ "question": "Foxie, we are going to die and we are finished.  Who said?","type": "single","options" : {"A": "Mr. Fox","B": "Mrs. Fox","C": "Small Fox","D": "Badger"},"answer": "D"},
{ "question": "Mr. Fox said: 'The mess you are in is ______'","type": "single","options" : {"A": "because of you","B": "because of farmers","C": "all chicken fault","D": "all my fault"},"answer": "D"},
{ "question": "At this very minute, ___ is preparing for me and my children, juicy chicken feast. Mr. Fox said","type": "single","options" : {"A": "Boggis","B": "Farmers","C": "Children","D": "She"},"answer": "D"},
{ "question": "When Mr. Fox told Badger, his wife is preparing chickens, Badger said ___","type": "single","options" : {"A": "Give me some","B": "don’t lie","C": "Go man","D": "Stop, you idiot!"},"answer": "D"},
{ "question": "What did Mr. Fox do because everything was his fault?","type": "single","options" : {"A": "He kneeled down","B": "He said sorry","C": "He gave some money","D": "He invited Badger and family for feast"},"answer": "D"},
{ "question": "Who said going near to ears? 'Do you know where we have just been?","type": "single","options" : {"A": "Badger","B": "Small foxes","C": "Weasel","D": "Mr. Fox"},"answer": "D"},
{ "question": "What did Mr. Fox tell Badger after inviting his family to the feast?","type": "single","options" : {"A": "You sleep here","B": "You run away","C": "You also eat some popcorn","D": "You can help us dig more"},"answer": "D"},
{ "question": "When Mr.Fox asked Badger to dig more and more, what was told to small badgers?","type": "single","options" : {"A": "Told them to run away","B": "Told then to shoot farmers","C": "Told them to sleep","D": "Told them to go his house and enjoy dinner"},"answer": "D"},
{ "question": "After Mr. Fox told to small badgers to meet Mrs. Fox and have dinner, they ____","type": "single","options" : {"A": "cant walk so slept","B": "cant move so asked a lift","C": "jumped and wanted food there","D": "jumped through the hole disappeared"},"answer": "D"},
{ "question": "When Badger saw and asked, 'Foxie, what happened to your tail?', Mr. Fox said:","type": "single","options" : {"A": "Tail fell down","B": "Monkey ate the tail","C": "Insects ate the tail","D": "Don’t talk about it please"},"answer": "D"},
{ "question": "For the new tunnel digging, who were there along with Foxes?","type": "single","options" : {"A": "1 Rabbit","B": "4 more small foxes","C": "2 Badgers","D": "Badger"},"answer": "D"},
{ "question": "Who is better in digging tunnel, Badger or Foxes?","type": "single","options" : {"A": "Foxes","B": "Both are equal","C": "None","D": "Badger"},"answer": "D"},
{ "question": "Now that Badger is also helping foxes, new tunnel digging went fast / slow?","type": "single","options" : {"A": "slow","B": "same speed","C": "it stopped","D": "quite fast"},"answer": "D"},
{ "question": "Soon, in the new tunnel they were hitting ___","type": "single","options" : {"A": "some rock","B": "some tree","C": "some water","D": "yet another wooden floor"},"answer": "D"},
{ "question": "In the new tunnel, after reaching wooden floor, Mr. Fox said ___","type": "single","options" : {"A": "We are now in dangerous place","B": "we are in Lion's den","C": "We are below a snake","D": "We are under farm of Bunce"},"answer": "D"},
{ "question": "In the new tunnel, they were underneath the farm of ___","type": "single","options" : {"A": "chicken","B": "cider","C": "juice","D": "ducks and geese"},"answer": "D"},
{ "question": "In the new tunnel, they were underneath ___ farm. whose?","type": "single","options" : {"A": "Boggis","B": "Bean","C": "Carrot","D": "Bunce"},"answer": "D"},
{ "question": "How in the world can you know where we are?' Who asked?","type": "single","options" : {"A": "Lion","B": "Farmer","C": "Boggis","D": "Badger"},"answer": "D"},
{ "question": "How in the world can you know where we are?' Who asked whom?","type": "single","options" : {"A": "Farmer asked wife","B": "Boggis asked Bean","C": "Bean asked Badger","D": "Badger asked Mr. Fox"},"answer": "D"},
{ "question": "How in the world can you know where we are? Whats the answer?","type": "single","options" : {"A": "I don’t know - I just went","B": "Farmers told","C": "His friend fox told","D": "I know these farms blindfold"},"answer": "D"},
{ "question": "In the new tunnel, after opening above Mr. fox said, ____ ___ it again!","type": "single","options" : {"A": "Ran it again","B": "Ate it again","C": "Drank it again","D": "I have done it again!"},"answer": "D"},
{ "question": "In the new tunnel, after opening above Mr. fox said, I have hit ____ on the ___.","type": "single","options" : {"A": "nail on the wall","B": "ball on the wall","C": "hammer on nose","D": "smack on the nose"},"answer": "D"},
{ "question": "From new tunnel, after Badger and small foxes came, they saw ___","type": "single","options" : {"A": "one big lion","B": "a den of lions","C": "a group of snakes","D": "a paradise for hungry animals"},"answer": "D"},
{ "question": "What were present in the bunce house when Fox and Badger reached?","type": "single","options" : {"A": "so much money","B": "thousands of cars","C": "thousands of gold","D": "thousands of finest ducks"},"answer": "D"},
{ "question": "In the Bunce house, above thousands of ducks, were smoked ___ and b___","type": "single","options" : {"A": "smoked nuts and biscuits","B": "smoked peas and biscuits","C": "smoked rice and biscuits","D": "smoked hams and bacon"},"answer": "D"},
{ "question": "At Bunce house, suddenly as though ___ had been released, 3 small foxes jumped","type": "single","options" : {"A": "gun","B": "lever ","C": "gate","D": "Spring"},"answer": "D"},
{ "question": "At Bunce house, he said, Stop!, this is my party. Who said when everyone ran here and there.","type": "single","options" : {"A": "Farmer","B": "Bean","C": "Badger","D": "Mr. Fox"},"answer": "D"},
{ "question": "At Bunce house, everyone chose their food.","type": "single","options" : {"A": "Yes","B": "Badger alone did","C": "Farmer did","D": "No, Mr. Fox did."},"answer": "D"},
{ "question": "At Bunce house, A thread of ____ slid of his jaw and hung","type": "single","options" : {"A": "blood","B": "water","C": "juice","D": "saliva"},"answer": "D"},
{ "question": "We must not overdo it' - Who said?","type": "single","options" : {"A": "Farmer","B": "Boggis","C": "Bunce","D": "Mr. Fox"},"answer": "D"},
{ "question": "We must not overdo it' - We must be ___t and ___y in eating","type": "single","options" : {"A": "feat and windy","B": "fast and tiry","C": "spot and speedy","D": "neat and tidy"},"answer": "D"},
{ "question": "Oh my! You will never see such finer geese in ___ kitchen. Whose kitchen?","type": "single","options" : {"A": "Komaali","B": "Mom's","C": "China","D": "Kings"},"answer": "D"},
{ "question": "Mr. Fox said, Fetch me that ___-____ to climb in Bunce's house","type": "single","options" : {"A": "big-stool","B": "small-stool","C": "rope-stool","D": "step-ladder"},"answer": "D"},
{ "question": "Mr. Fox said, Badger, you liked ____ h__, don’t you?","type": "single","options" : {"A": "salted hen","B": "salted ham","C": "stripped hen","D": "Smoked ham"},"answer": "D"},
{ "question": "Mr. Fox asked, along with hams do you like b___n?  I am mad at it!, Badger replied","type": "single","options" : {"A": "bun","B": "bean","C": "brin","D": "bacon"},"answer": "D"},
{ "question": "When Mr. Fox was taking hams and bacons, 'Dad, we must take some carrots' Who said?","type": "single","options" : {"A": "Rabbits","B": "Badger","C": "Farmers","D": "Small foxes"},"answer": "D"},
{ "question": "When Mr. Fox was taking hams and bacons, 'Dad, we must take some carrots' Carrots for whom?","type": "single","options" : {"A": "Badger","B": "Farmers","C": "Foxes","D": "Rabbits"},"answer": "D"},
{ "question": "Do foxes eat carrots?","type": "single","options" : {"A": "Yes","B": "with Pickle","C": "with sweet","D": "No"},"answer": "D"},
{ "question": "What did Mr. Fox do when small foxes asked for carrots for rabbits","type": "single","options" : {"A": "Mr. Fox got angry","B": "Mr. Fox got tired","C": "Mr. Fox got happy","D": "Mr. Fox praised them"},"answer": "D"},
{ "question": "After piling up all the geese, hams, bacons, carrots - how to carry them? Mr. Fox said","type": "single","options" : {"A": "Send in bus","B": "Lets take big bag","C": "Lets take big box","D": "Lets take Bunce's Push carts"},"answer": "D"},
{ "question": "After push carts were loaded what did animals do?","type": "single","options" : {"A": "they also sat on the cart","B": "they tied with rope","C": "lifted aboe head","D": "Lowered through the tunnel"},"answer": "D"},
{ "question": "When other animals took the push cart, Mr. Fox did ___ to close","type": "single","options" : {"A": "locked with key","B": "shut the door","C": "bombed the house","D": "pulled floorboards carefully"},"answer": "D"},
{ "question": "Where were push carts taken towards?","type": "single","options" : {"A": "towards farmers","B": "towards Big foxes","C": "towards the pond to throw","D": "towards Mrs. Fox for feast"},"answer": "D"},
{ "question": "After push carts were taken from Bunce, how many small foxes left with Mr. Fox","type": "single","options" : {"A": "Two","B": "Four","C": "Twenty","D": "One"},"answer": "D"},
{ "question": "Now, just ___ ____ visit, Mr. Fox said after Bunce and Borris house vists.","type": "single","options" : {"A": "Two more","B": "Three more","C": "no more","D": "One more"},"answer": "D"},
{ "question": "Who guessed it right when Mr. Fox said, 'One more visit'","type": "single","options" : {"A": "Badger","B": "Friend fox","C": "Mrs. Fox","D": "Small fox"},"answer": "D"},
{ "question": "Mr. Fox said, 'One more visit'. Where was that?","type": "single","options" : {"A": "Borris house","B": "Bunce House","C": "Lion Den","D": "Bean house"},"answer": "D"},
{ "question": "As they were digging, Badger asked 'Doesn’t this ___ ___ a bit?'","type": "single","options" : {"A": "make you happy","B": "make you sad","C": "help you","D": "worry you"},"answer": "D"},
{ "question": "Why did Badger say, Fox, doesn’t it worry you? Badger said this is ____","type": "single","options" : {"A": "nonsense","B": "very good","C": "stinky","D": "stealing"},"answer": "D"},
{ "question": "When Badger said, this looks like stealing, Fox said: ","type": "single","options" : {"A": "I already gave money to farmers","B": "It is not - Farmers stole from me","C": "Yes, it is - I don’t bother","D": "Anyone in world will steal if your children are starving"},"answer": "D"},
{ "question": "Look, Farmers are up there to kill us, ___ said.","type": "single","options" : {"A": "Mrs. Fox","B": "Small Fox","C": "Badger","D": "Mr. Fox"},"answer": "D"},
{ "question": "Badger said, 'We are not going to ____ to their level.' Will not kill them.","type": "single","options" : {"A": "run","B": "drown","C": "fly","D": "stoop"},"answer": "D"},
{ "question": "Mr Fox said we will take ___ food here and there to keep our families alive.","type": "single","options" : {"A": "all the","B": "more","C": "colorful","D": "a little"},"answer": "D"},
{ "question": "After Mr. Fox told, we will take only little food, Badger said to fox, ","type": "single","options" : {"A": "I hate you","B": "I dislike you","C": "I Like You","D": "I Love You"},"answer": "D"},
{ "question": "After some time, Badger's paws hit something like ____","type": "single","options" : {"A": "watery fluid","B": "wooden wall","C": "cement wall","D": "solid stone wall"},"answer": "D"},
{ "question": "What did Mr. Fox say when he saw the stone wall.","type": "single","options" : {"A": "This is end, we go back","B": "Hit the wall and break","C": "Farmers are behind the wall","D": "That’s exactly what I wanted looking for"},"answer": "D"},
{ "question": "How was the wall inside the tunnel made with?","type": "single","options" : {"A": "Stone","B": "Glass","C": "Steel","D": "Bricks"},"answer": "D"},
{ "question": "Mr. Fox examined the brick wall and felt, the contact between bricks were ___","type": "single","options" : {"A": "having holes","B": "very tight","C": "very watery","D": "crumply"},"answer": "D"},
{ "question": "How did Mr. Fox get into the brick wall","type": "single","options" : {"A": "hit with big knife","B": "hit with big sword","C": "kick the wall","D": "Bricks were old to be removed"},"answer": "D"},
{ "question": "When Mr. Fox made the hole in the brick wall, who was there?","type": "single","options" : {"A": "2 cats","B": "It’s a badger","C": "It’s a big lion","D": "It’s a rat!"},"answer": "D"},
{ "question": "What did Mr. Rat say when fox holed inside the wall?","type": "single","options" : {"A": "Come join me","B": "Come, lets both eat","C": "Go, farmes are there!","D": "Go away!"},"answer": "D"},
{ "question": "When Rat asked to go away, Mr. Fox said, ___","type": "single","options" : {"A": "Ok, I will go away","B": "Ok, but you also come","C": "I want to eat and go","D": "I shall eat u in one gulp"},"answer": "D"},
{ "question": "After rat ran away, Mr fox made ____ h___","type": "single","options" : {"A": "small hole","B": "round hole","C": "square hole","D": "biggish hole"},"answer": "D"},
{ "question": "What did animals see after jumping through biggish hole?","type": "single","options" : {"A": "One big jar of juice","B": "One big jar of cider","C": "100s of chickens","D": "Bean's vast cellar"},"answer": "D"},
{ "question": "What was inside the cellar?","type": "single","options" : {"A": "Cellar was full of Biriyani","B": "Cellar was full of food","C": "Cellar was full of chicken","D": "Jars and jars of cider"},"answer": "D"},
{ "question": "Who asked 'Where are the turkeys'? After landing into Bean's cellar","type": "single","options" : {"A": "Badger","B": "Rat","C": "Cat","D": "Small fox"},"answer": "D"},
{ "question": "After entering Bean's cellar, what was asked to Mr. Fox","type": "single","options" : {"A": "Where are chickens?","B": "Where is juice?","C": "Where are peas?","D": "Where are turkeys?"},"answer": "D"},
{ "question": "When small foxes asked for Turkeys, Mr. Fox said ___","type": "single","options" : {"A": "It is there in gunny bag","B": "It is in the box","C": "Red bag is carrying those","D": "We have enough food, we don’t need"},"answer": "D"},
{ "question": "In all the big jugs, what was written on it?","type": "single","options" : {"A": "Apple Juice","B": "Juice","C": "Syrup","D": "Cider"},"answer": "D"},
{ "question": "Where was Bean's cellar?","type": "single","options" : {"A": "Right above his farmhouse","B": "Right beside his farmhouse","C": "below a lake","D": "Right under his farmhouse"},"answer": "D"},
{ "question": "Badger said, CIDER, we take it as ____","type": "single","options" : {"A": "beverage","B": "Coffee","C": "Juie","D": "Medicine"},"answer": "D"},
{ "question": "Small fox took the ___ of CIDER and said, wowie!","type": "single","options" : {"A": "spoon","B": "drop","C": "ginna","D": "gulp"},"answer": "D"},
{ "question": "This Cider is pure one, home made, burned in your ____ and boiled in your stomach","type": "single","options" : {"A": "stove","B": "oven","C": "kitchen","D": "throat"},"answer": "D"},
{ "question": "This Cider is pure one, home made, burned in your throat and boiled in your ____","type": "single","options" : {"A": "stove","B": "heater","C": "geyser","D": "stomach"},"answer": "D"},
{ "question": "While drinking Cider, it is like ____ G___, said Badger","type": "single","options" : {"A": "boiled Gold","B": "melted geese","C": "boiled guava","D": "melted Gold"},"answer": "D"},
{ "question": "While drinking Cider, it is like melted Gold - who said?","type": "single","options" : {"A": "Small Fox","B": "Mr. Fox","C": "Rat","D": "Badger"},"answer": "D"},
{ "question": "When everyone was drinking cider, Rat said, you are p_____","type": "single","options" : {"A": "plumpy","B": "prickling","C": "picking","D": "poaching"},"answer": "D"},
{ "question": "How was Rat drinking the Cider?","type": "single","options" : {"A": "sucking through spoon","B": "sucking through straw","C": "sucking in bottle","D": "sucking through rubber tube in jar neck"},"answer": "D"},
{ "question": "While they were drinking cider, they heard _____ voice","type": "single","options" : {"A": "lion's","B": "fox's","C": "Farmer's","D": "women's"},"answer": "D"},
{ "question": "After hearing a voice call in Cellar, animals were ____","type": "single","options" : {"A": "happy","B": "sad","C": "tired","D": "froze "},"answer": "D"},
{ "question": "After hearing a voice call in Cellar, animals were ____","type": "single","options" : {"A": "happy","B": "sad","C": "tired","D": "nervous"},"answer": "D"},
{ "question": "Where was the door to Cider?","type": "single","options" : {"A": "above the head","B": "top of the tree","C": "below the hill","D": "On top of the stone steps"},"answer": "D"},
{ "question": "When woman's voice was heard, Mr. Fox said,","type": "single","options" : {"A": "Run Run!","B": "Jump away!","C": "Disappear and Kill","D": "Quick, Hide!"},"answer": "D"},
{ "question": "Where did the animals hide hearing woman's voice","type": "single","options" : {"A": "Inside a box","B": "Inside a bag","C": "Behind the stones","D": "crouched behind jars"},"answer": "D"},
{ "question": "How was the woman who entered Bean's cellar?","type": "single","options" : {"A": "tall","B": "long","C": "short","D": "fat"},"answer": "D"},
{ "question": "After coming down, where did the woman go?","type": "single","options" : {"A": "Near stones where rat was hiding","B": "Near jars where the door was there","C": "Near Mrs. Bean","D": "Near jars where foxes were hiding"},"answer": "D"},
{ "question": "Who are all hiding inside the cellar?","type": "single","options" : {"A": "None","B": "Badger alone","C": "Rat alone","D": "Fox, small fox and Badger"},"answer": "D"},
{ "question": "It was so silent that Mr. Fox could hear the woman's ___","type": "single","options" : {"A": "chewing","B": "panting","C": "eating","D": "breathing"},"answer": "D"},
{ "question": "What was the huge woman carrying in her hand","type": "single","options" : {"A": "cricket bat","B": "big size pin","C": "big fire band","D": "big rolling pin"},"answer": "D"},
{ "question": "How many ciders he wanted this time, Mrs. Bean?, Woman asked - who wanted?","type": "single","options" : {"A": "Mr. Boggis","B": "Mrs. Woman","C": "Mrs. Fox","D": "Mr. Bean"},"answer": "D"},
{ "question": "How many ciders he wanted this time' - what was the answer from top?","type": "single","options" : {"A": "4-5 jars","B": "7-8 jars","C": "1 jar only","D": "2-3 jars"},"answer": "D"},
{ "question": "When the woman took the jar out, where were the foxes?","type": "single","options" : {"A": "they were inside another hold","B": "they were behind the woman","C": "they were hanging on a rope","D": "they were just behind the next jar"},"answer": "D"},
{ "question": "What was woman wanting from Mr. Bean?","type": "single","options" : {"A": "the head of fox","B": "the body of fox","C": "the eyes of fox","D": "the tail as souvenir"},"answer": "D"},
{ "question": "The tail is runied. Oh No!  You can have ___ instead, said Mrs. Bean","type": "single","options" : {"A": "Legs","B": "Thigh","C": "Hands","D": "Head"},"answer": "D"},
{ "question": "Mrs. Bean said, take tail and ___ in your bedroom","type": "single","options" : {"A": "cook","B": "eat","C": "crush","D": "hang"},"answer": "D"},
{ "question": "Mrs. Bean said, take tail and hang in your ____","type": "single","options" : {"A": "bathroom","B": "car","C": "bike","D": "bedroom"},"answer": "D"},
{ "question": "With how many jars, the woman walked away finally?","type": "single","options" : {"A": "7","B": "1","C": "three","D": "Two"},"answer": "D"},
{ "question": "When the woman took jars away, she suddenly pasued - why?","type": "single","options" : {"A": "power cut","B": "heard fox's sound","C": "heard rat's sound","D": "she smelled rats"},"answer": "D"},
{ "question": "What advice Mrs. Bean gave when she said she can smell rats","type": "single","options" : {"A": "catch rats and put in bottle","B": "allow rats to eat some","C": "shoot them","D": "Poison them"},"answer": "D"},
{ "question": "After she went and door slammed, Rat said to fox ____","type": "single","options" : {"A": "At least go away now","B": "don’t disturb me","C": "I told, she will shoot u","D": "I told, she almost nabbed u"},"answer": "D"},
{ "question": "After she went and door slammed, Rat said to fox ____","type": "single","options" : {"A": "At least go away now","B": "don’t disturb me","C": "I told, she will shoot u","D": "This is my place, go away"},"answer": "D"},
{ "question": "Mr. Fox said to rat, the woman will ____ you","type": "single","options" : {"A": "shoot","B": "kill","C": "pull","D": "Poison"},"answer": "D"},
{ "question": "Foxes took one jar each and disappeared. Rat said ___, ____","type": "single","options" : {"A": "Good, Bye","B": "Run, Run!","C": "Stop, Stop!","D": "Thieves, Burglers"},"answer": "D"},
{ "question": "Mr. Fox paused when he was coming back into tunnel. Why","type": "single","options" : {"A": "Power cut","B": "Rat called him","C": "Badger fell down","D": "To close the bricks in wall"},"answer": "D"},
{ "question": "He has bad manners, Badger said.  Who?","type": "single","options" : {"A": "Cat","B": "Borris","C": "Farmers","D": "Rat"},"answer": "D"},
{ "question": "Is there any rat which is polite?","type": "single","options" : {"A": "Yes","B": "Only father rats","C": "Only mother rats","D": "No"},"answer": "D"},
{ "question": "On the way in tunnel they passed through ____","type": "single","options" : {"A": "a lake","B": "a tree","C": "Badger's house","D": "Bunce Mighty storehouse"},"answer": "D"},
{ "question": "How many jars of ciders were being brought?","type": "single","options" : {"A": "4","B": "Two","C": "9","D": "Three"},"answer": "D"},
{ "question": "Finally, how many were coming with ciders?","type": "single","options" : {"A": "4","B": "Two","C": "9","D": "Three"},"answer": "D"},
{ "question": "While bringing ciders, what were they doing?","type": "single","options" : {"A": "they were dancing","B": "they were shouting","C": "they were crying","D": "they were singing"},"answer": "D"},
{ "question": "When all of them came at last turn of the tunnel, they saw ___","type": "single","options" : {"A": "police waiting to arrest them","B": "lion waiting to kill them","C": "fox waiting to shout at them","D": "large dining-room"},"answer": "D"},
{ "question": "In the large dining room, how many animals were there?","type": "single","options" : {"A": "17","B": "19","C": "22","D": "29"},"answer": "D"},
{ "question": "What were all the animals doing around the table","type": "single","options" : {"A": "they were talking","B": "they were shouting","C": "they were singing","D": "they were feasting"},"answer": "D"},
{ "question": "Mr. Fox ____ Mrs. Fox, Mr Badger ___ Mrs. Badger, Everyone ___ everyone","type": "single","options" : {"A": "shouted","B": "shoot","C": "kissed","D": "hugged"},"answer": "D"},
{ "question": "Many have not eaten for days. So they were silent - why? They were all ____","type": "single","options" : {"A": "meditating","B": "doing yoga","C": "drinking","D": "eating as much as they can"},"answer": "D"},
{ "question": "Many have not eaten for days. So they were silent - Only sound was ___","type": "single","options" : {"A": "drinking","B": "pulling","C": "pushing","D": "crunching"},"answer": "D"},
{ "question": "Badger said with glass of cider, ____ saved our lives this day. Who?","type": "single","options" : {"A": "Mrs. Fox","B": "Small fox","C": "Farmers","D": "Mr. Fox"},"answer": "D"},
{ "question": "I don’t want to give speech, I want to say only one thing.' Who said this?","type": "single","options" : {"A": "Mr. Fox","B": "Badger","C": "Small Fox","D": "Mrs. Fox"},"answer": "D"},
{ "question": "I don’t want to give speech, I want to say only one thing.' What did she say?","type": "single","options" : {"A": "I had the best food","B": "I had the worst time","C": "My Husband eats well","D": "My Husband is a fantastic fox"},"answer": "D"},
{ "question": "Mr. Fox stood up and said, this meal is by courtesy Messers. ____, ____, ____.","type": "single","options" : {"A": "Famer, Rat and Bunce","B": "Badger, Fox and Bean","C": "Badger, Fox and Rat","D": "Boggis, Bunce and Bean"},"answer": "D"},
{ "question": "Now, friends, let us think seriously.  What to think?","type": "single","options" : {"A": "Remaining food where to keep","B": "How to clean the table","C": "Where to go next?","D": "Food for tomorrow and day ater"},"answer": "D"},
{ "question": "The animals decided not to go out after feast, why?","type": "single","options" : {"A": "they cant walk","B": "their stomach is full","C": "their legs are tired","D": "they will be shot"},"answer": "D"},
{ "question": "The animals decided not to go out, how will they get food then?","type": "single","options" : {"A": "farmers will send","B": "enough food is stored already","C": "no food required. Stomach is full","D": "through tunnel to store houses"},"answer": "D"},
{ "question": "Since they have enough food now, Mr. Fox said all of them to _____","type": "single","options" : {"A": "go away","B": "run away","C": "eat together","D": "stay together"},"answer": "D"},
{ "question": "Mr. Fox said, we will make a small / little underground ______","type": "single","options" : {"A": "city","B": "farmhouse","C": "house","D": "village"},"answer": "D"},
{ "question": "Mr. Fox said, we will every day eat like ____","type": "single","options" : {"A": "happy man","B": "farmer","C": "fox","D": "kings"},"answer": "D"},
{ "question": "What happened to the farmers sitting outside?","type": "single","options" : {"A": "Slept","B": "Fell down","C": "Ran away","D": "Waiting"},"answer": "D"},
{ "question": "What happened when farmers were sitting?","type": "single","options" : {"A": "Snake came","B": "It was cold","C": "It was hot","D": "It rained"},"answer": "D"},
{ "question": "When rained outside, what did farmers do?","type": "single","options" : {"A": "they kept umbrella","B": "they were under tree","C": "they went home","D": "they still waited"},"answer": "D"},
{ "question": "Outside, what were farmers having on their laps","type": "single","options" : {"A": "chicken","B": "fox's tail","C": "hats","D": "guns"},"answer": "D"},

]