qbMaths = [

{ "question": "23 + 45 = ?","type": "single","options" : {"A": "86","B": "87","C": "67","D": "68"},"answer": "D"},
{ "question": "Spell this number: 999","type": "single","options" : {"A": "Nine nine nine","B": "Nine hundred and ninety nine","C": "Nine ninety nine","D": "Nine hundred ninety nine"},"answer": "D"},
{ "question": "Spell this number: 919","type": "single","options" : {"A": "Nine hundred and nineteen","B": "Nine nineteen","C": "Nine one nine","D": "Nine hundred nineteen"},"answer": "D"},
{ "question": "One hundred sixty nine is ___","type": "single","options" : {"A": "196","B": "69","C": "96","D": "169"},"answer": "D"},
{ "question": "Nine hundred forty four is ___","type": "single","options" : {"A": "94","B": "449","C": "949","D": "944"},"answer": "D"},
{ "question": "Seven hundred seven is ___","type": "single","options" : {"A": "77","B": "717","C": "7007","D": "707"},"answer": "D"},
{ "question": "Seventeen is ___","type": "single","options" : {"A": "18","B": "71","C": "70","D": "17"},"answer": "D"},
{ "question": "How many hundreds and tens in 565?","type": "single","options" : {"A": "5 hundreds 10 sixties","B": "5 tens 6 hundreds 56 tens","C": "65 tens","D": "5 hundreds 6 tens"},"answer": "D"},
{ "question": "How many hundreds, tens and ones are in 807?","type": "single","options" : {"A": "8 hundreds 7 tens","B": "8 hundreds 17 tens","C": "8 hundreds 0 tems","D": "8 hundres 7 ones"},"answer": "D"},
{ "question": "795 - What is present in one's place?","type": "single","options" : {"A": "795","B": "90","C": "700","D": "5"},"answer": "D"},
{ "question": "What is present in 10's place: 999?","type": "single","options" : {"A": "90","B": "900","C": "999","D": "9"},"answer": "D"},
{ "question": "What is present in 100's place for 65?","type": "single","options" : {"A": "6","B": "5","C": "65","D": "0"},"answer": "D"},
{ "question": "Place value of 5: 659","type": "single","options" : {"A": "5","B": "10","C": "59","D": "50"},"answer": "D"},
{ "question": "Place value of 4: 242","type": "single","options" : {"A": "4","B": "10","C": "42","D": "40"},"answer": "D"},
{ "question": "Face value of 5: 659","type": "single","options" : {"A": "10","B": "50","C": "59","D": "5"},"answer": "D"},
{ "question": "Face value of 4: 242","type": "single","options" : {"A": "40","B": "10","C": "42","D": "4"},"answer": "D"},
{ "question": "Smallest of 373, 412, 296, 369","type": "single","options" : {"A": "373","B": "412","C": "369","D": "296"},"answer": "D"},
{ "question": "Which is correct on?","type": "single","options" : {"A": "373 &gt; 412","B": "315 &lt; 212","C": "125 &gt; 119","D": "373 &gt; 269"},"answer": "D"},
{ "question": "Which is incorrect one?","type": "single","options" : {"A": "412 &gt; 123","B": "296 &gt; 269","C": "421 &gt; 412","D": "312 &gt; 321"},"answer": "D"},
{ "question": "238, 531, 735, 112. Which are the odd numbers?","type": "single","options" : {"A": "531, 238","B": "531, 112","C": "112, 238","D": "531, 735"},"answer": "D"},
{ "question": "238, 531, 735, 112. Which are the even numbers?","type": "single","options" : {"A": "238, 531","B": "735, 112","C": "531, 112","D": "238, 112"},"answer": "D"},
{ "question": "238, 531, 735, 112. How many even and odd numbers are there?","type": "single","options" : {"A": "3 even 1 odd","B": "1 even 2 odd","C": "1 even 3 odd","D": "2 even 2 odd"},"answer": "D"},
{ "question": "Write in expanded form: 497","type": "single","options" : {"A": "400 + 97","B": "4 + 90 + 7","C": "4 + 9 + 7","D": "400 + 90 + 7"},"answer": "D"},
{ "question": "Write in expanded form: 103","type": "single","options" : {"A": "100 + 13","B": "100 + 30 + 3","C": "100 + 1 + 3","D": "100 + 3"},"answer": "D"},
{ "question": "Write in expanded form: 669","type": "single","options" : {"A": "600 + 69 + 9","B": "600 + 69","C": "600 + 90 + 6","D": "600 + 60 + 9"},"answer": "D"},
{ "question": "Write in expanded form: 110","type": "single","options" : {"A": "100 + 10 + 1","B": "100 + 11","C": "10 + 100","D": "100 + 10 + 0"},"answer": "D"},
{ "question": "305, 35, 350 - Ascending order pls.","type": "single","options" : {"A": "350, 305, 35","B": "350, 35, 305","C": "35, 350, 305","D": "35, 305, 350"},"answer": "D"},
{ "question": "169, 81, 712 - put it in Descending order.","type": "single","options" : {"A": "712, 81, 169","B": "169, 81, 712","C": "None of the above","D": "712, 169, 81"},"answer": "D"},
{ "question": "Which is the digit whose face value and place value remains the same","type": "single","options" : {"A": "Tens","B": "Hundreds","C": "All above","D": "Ones"},"answer": "D"},
{ "question": "I am five numbers after 45. I am __","type": "single","options" : {"A": "455","B": "46","C": "51","D": "50"},"answer": "D"},
{ "question": "I am 7 numbers before 19. Which number am I?","type": "single","options" : {"A": "19","B": "17","C": "9","D": "12"},"answer": "D"},
{ "question": "I am between 29 and 31. Which number I am","type": "single","options" : {"A": "29","B": "3","C": "31","D": "30"},"answer": "D"},
{ "question": "250 &gt; 5. Is it true?","type": "single","options" : {"A": "No","B": "May be","C": "None","D": "Yes"},"answer": "D"},
{ "question": "1 less than 751 is ___","type": "single","options" : {"A": "75","B": "7511","C": "651","D": "750"},"answer": "D"},
{ "question": "Rows and Columns of numbers to do addition. They are in a table. That is called as ____ table","type": "single","options" : {"A": "Maths table","B": "English table","C": "Number table","D": "Cayley table"},"answer": "D"},
{ "question": "What is 18 + 0?","type": "single","options" : {"A": "0","B": "81","C": "1","D": "18"},"answer": "D"},
{ "question": "What is 18 + 1?","type": "single","options" : {"A": "18","B": "1","C": "20","D": "19"},"answer": "D"},
{ "question": "23 + 45 = ?","type": "single","options" : {"A": "86","B": "87","C": "67","D": "68"},"answer": "D"},
{ "question": "9 x 6 = ?","type": "single","options" : {"A": "45","B": "96","C": "15","D": "54"},"answer": "D"},
{ "question": "3 x 9 = ?","type": "single","options" : {"A": "12","B": "18","C": "39","D": "27"},"answer": "D"},
{ "question": "6 x 4 = ?","type": "single","options" : {"A": "64","B": "34","C": "44","D": "24"},"answer": "D"},
{ "question": "12 + 29 [Do it on paper]","type": "single","options" : {"A": "1229","B": "149","C": "14","D": "41"},"answer": "D"},
{ "question": "What is face value of 9 in 691?","type": "single","options" : {"A": "90","B": "10","C": "1","D": "9"},"answer": "D"},
{ "question": "Apples with me: 10. Monday I ate 3, Tuesday I ate 4, Left over?","type": "single","options" : {"A": "4","B": "7","C": "2","D": "3"},"answer": "D"},
{ "question": "22 students are in 1-C class. 15 students are boys? How many girls?","type": "single","options" : {"A": "10","B": "22","C": "27","D": "7"},"answer": "D"},
{ "question": "Shop keeper has 50 Icecreams. Morning he sold 20, Evening he sold 25. How many are remaining?","type": "single","options" : {"A": "20","B": "25","C": "45","D": "5"},"answer": "D"},
{ "question": "Mrs. Rogers bought 2 dresses for her birthday. One was 511 Rs. Another was 272 rs. How much did she spend?","type": "single","options" : {"A": "753","B": "511","C": "272","D": "783"},"answer": "D"},
{ "question": "How do you measure this item? &gt;&gt;&gt;maths_milk","type": "single","options" : {"A": "kilo","B": "meter","C": "muzha","D": "litre"},"answer": "D"},
{ "question": "How do you measure this item? &gt;&gt;&gt;maths_sugar","type": "single","options" : {"A": "litre","B": "meter","C": "muzha","D": "kilo"},"answer": "D"},

]